Feature/#9
kodesalon/project pull request #25
Opened 2021-05-12 05:09 UTC by sdrs6921

### 개요
- 이슈 번호 : #9 
- 내용 : Alias VO 객체 구현

### 작업 사항
- value() 테스트 코드 작성
- value() 구현
- alias의 유효성을 검사하는 validateAlias() 테스트 코드 작성
- alias의 유효성 검사 메서드 구현 

### 기타
- private 메서드를 테스트 할 때 직접 테스트 하는 것이 좋은 지 아니면 public을 통해 간접적으로 테스트 하는 것이 좋은 지 궁금합니다.
- 더 테스트 해야 할 코드가 존재하는지 궁금합니다.

2021-05-12 12:21 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/domain/member/vo/AliasTest.java
> +        Method method = alias.getClass().getDeclaredMethod("validateAlias", String.class);
`Reflection` 기술을 이용해서 private 메서드를 테스트 해본 시도는 굳👍
그렇지만 현재 우리팀에서도 `Reflection` 을 이용해서 테스트 코드를 작성하는 건 지양하고 있음.
`Reflection`의 존재 목적이 private 테스트 코드를 작성하기 위해 존재하는 게 아니기 때문

private 메서드 테스트 코드는 어떻게 해야하는지 질문을 줬는데 public 메서드에 대한 테스트를 작성하면서 private 메서드도 테스트 되도록 작성하는게 일반적이야. (coverage test 를 돌려보면 private 메서드까지 테스트가 됐는지 확인할 수 있음)

그런데, private 메서드가 많아지면 테스트 작성이 어려워질 수 있는데 그럴 땐 해당 클래스가 너무 많은 일을 하는 것이 아닌가를 의심해봐야해. (개인적인 의견이지만 나는 private 메서드를 별로 안 좋아합니다. -> public 메서드로만 깔끔하게 짜는 걸 선호)

`validateAlias` 라는 메서드가 꼭 분리될 필요가 있을까 생각해봐도 좋을 듯. 다른 곳에서 사용되는 것이 아니라면 그냥 생성자 내부에 있어도 되지 않을까 싶어~

2021-05-12 12:48 UTC, seonghun127 requested changes
VO 객체 만드는데, 예전보다 더 나아진 거 같아서 보기 좋구만 ㅎㅎㅎ
리뷰 몇개 남겼으니 확인해봐~

PR 코멘트에 남긴 내용에 답을 하자면
* private 메서드의 테스트 코드에 대한 답은 위 single comment에 남겼고
* 지금 테스트 코드는 충분한 듯~ 미쳐 놓친 부분이 있는지 확인하고 싶으면 coverage test로 한번 돌려봐
* 지금 feature 브랜치를 develop에서 딴 거 같은데 이전 PR에서 이야기했던 방식으로 잘하고 있는 듯! (참고로 git flow에는 정답이 없기 때문에 지금 방식이 무조건 좋다라고 생각하면 안돼~)

2021-05-12 12:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/domain/member/vo/Alias.java
> +    public static final String ALIAS_PATTERN = "^[a-zA-Z]{1}[a-zA-Z0-9]{4,11}$";
이 상수는 private 으로 변경해도 되지 않을까?

2021-05-12 12:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/domain/member/vo/Alias.java
> +    private String validateAlias(String alias) throws IllegalFormatException {
이 메서드는 `RuntimeException` 을 던지고 있기 때문에 throws가 따로 필요 없을 듯

2021-05-12 12:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/domain/member/vo/Alias.java
> +        if (Pattern.matches(ALIAS_PATTERN, alias)) {
`Pattern.matches()` 는 내부적으로 매번 주어진 정규표현식을 컴파일(`Pattern.compile()`)하는데 굳이 매번 컴파일 할 필요가 있을까?

`matches()` 메서드 내부 코드 한번 보고 상수로 뺄 수 있는 부분은 빼놓는게 좋아보여
java.util.regex.Pattern#matches

2021-05-12 12:48 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/domain/member/vo/AliasTest.java
> +        //givne
given / when / then 을 주석으로 표현하는 건 좋은데, 해당 영역에 코드가 없다면 지워도 될 듯~

2021-05-12 12:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/domain/member/vo/Alias.java
> +    private String validateAlias(String alias) throws IllegalFormatException {
위 생성자에선 인자에 `final`을 붙여줬는데, 여기엔 없는 이유가 있을까?
`final`을 반드시 붙여야하는 건 아니지만 성빈이랑 이야기해서 컨벤션을 정하고 개발하면 통일성을 높일 수 있을 거 같어~

2021-05-12 12:50 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/domain/member/vo/AliasTest.java
> +        Method method = alias.getClass().getDeclaredMethod("validateAlias", String.class);
이 부분에 대해서 @sefide 도 같이 이야기 해줘도 좋을 거 같어
현재 팀에서 어떻게 이 부분을 처리하는지~ 또는 본인의 생각 등

2021-05-12 12:52 UTC, sdrs6921 commented on src/test/java/com/project/kodesalon/model/domain/member/vo/AliasTest.java
> +        //givne
넵! 없는 부분은 찾아서 반영하겠습니다.

2021-05-12 12:53 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/domain/member/vo/Alias.java
> +    public static final String ALIAS_PATTERN = "^[a-zA-Z]{1}[a-zA-Z0-9]{4,11}$";
상수는 무조건 public static final String으로 하는 게 컨벤션 아니었습니까? private으로 상수를 선언해도 상관없나요?

2021-05-12 12:54 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/domain/member/vo/Alias.java
> +    private String validateAlias(String alias) throws IllegalFormatException {
아 이건 제가 실수로 빼야 할 부분을 체크를 못했네요.

2021-05-12 12:54 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/domain/member/vo/Alias.java
> +    public static final String INVALID_ALIAS_EXCEPTION_MESSAGE = "잘못된 Alias 형식입니다.";
이거 지금 테스트 코드에서도 사용하는데, 다른 프로덕션 코드가 아닌 테스트 코드에서 사용한다고 public으로 열어두는건 개인적으로 좋지 않은 거 같음.
정보 은닉, 응집도를 높이기 위해 접근 제어자를 사용해야하는게 중요한데 테스트를 위해 public 열어둔다면 테스트를 위해 setter를 추가하는 거랑 같은 거라 생각합니다~

2021-05-12 12:55 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/domain/member/vo/Alias.java
> +    private String validateAlias(String alias) throws IllegalFormatException {
Alias는 변하지 않는 부분이라고 생각해서 `final`을 붙였는데 파라메터에는 깜빡하고 안 넣었네요.

2021-05-12 12:56 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/domain/member/vo/Alias.java
> +    public static final String ALIAS_PATTERN = "^[a-zA-Z]{1}[a-zA-Z0-9]{4,11}$";
상수의 접근제어자는 상황에 따라 다르겠지만 나는 왠만하면 priavte으로 설정해줘. 해당 클래스에서 상수를 선언한다면 그 상수는 온전히 그 클래스에서만 사용되는게 좋다고 생각하거든.

클래스 내부의 상수를 public 으로 열어서 다른 클래스에서 사용한다면 그또한 의존이기 때문에 불필요한 의존이라고 생각함~

2021-05-12 16:59 UTC, sefide commented on src/test/java/com/project/kodesalon/model/domain/member/vo/AliasTest.java
> +        Method method = alias.getClass().getDeclaredMethod("validateAlias", String.class);
저도 너무 x2 같은 의견인데요 !

우선 `테스트가 어려운 코드`라면 설계 단계부터 다시 고민해야 해요 ~ 
테스트가 쉬운 코드가 요구사항을 명확히 수행하고 이해하기 좋은 코드라고 생각해서 `테스트가 가능한 설계`를 하려고 노력하는 편이예요. 그러다보면 자연스럽게 private 메서드 또한 지양하게 되지만.. 그럼에도 불구하고 private 메서드가 불가피한 경우가 꽤 생길거예요. 그때는 최대한 public 메서드 테스트로 커버하고자 합니다. 

validateAlias 메서드 때문에 이와 같은 질문을 하신 것으로 생각이 드는데요.
validateAlias 메서드의 Reflection 테스트를 제거한 후, 커버리지를 확인해보면 모델에 대한 커버리지가 100% 달성한 걸 확인할 수 있네요 ;) public 생성자로 private 메서드에 대한 간접 테스트가 충분히 이뤄진 것 같아요. 

덧붙여서 Reflection을 사용하는 테스트 또한 지양하고 있습니다 ~
성훈님께서 말씀하신 이유 이외에, getDeclaredMethod의 파라미터로 메소드명을 문자열로 넘겨주는 방식에 있어서 오는 불편함
- 메서드명 문자열의 오타 발생 가능성
- 해당 메서드가 테스트되고 있는지 여부 확인이 어려움
 
때문에 지양하고 있어요.

2021-05-12 17:25 UTC, sefide requested changes
전반적으로 성훈님께서 남겨주신 리뷰와 같은 의견이 많아서 
몇가지 간단하게 수정해볼만한 내용들 덧붙였습니다 ~

커밋 로그보니 테스트 코드가 들어간 첫 PR인데도 
TDD에 대한 이해도도 높은 것 같아요 👍🏼

2021-05-12 17:25 UTC, sefide commented on src/test/java/com/project/kodesalon/model/domain/member/vo/AliasTest.java
> +        Method method = alias.getClass().getDeclaredMethod("validateAlias", String.class);
그나저나 alias에 대한 또 다른 유효성 체크거리가 없다면 `validateAlias`로 따로 안빼도 될 것 같아요 ~ 이것도 같은 의견 ~

2021-05-12 17:25 UTC, sefide commented on src/test/java/com/project/kodesalon/model/domain/member/vo/AliasTest.java
> +            throws NoSuchMethodException {
이 테스트에서는 NoSuchMethodException를 던질 필요가 없을 것 같은데 따로 추가한 이유가 있을까요 ?

2021-05-12 17:25 UTC, sefide commented on src/test/java/com/project/kodesalon/model/domain/member/vo/AliasTest.java
> +    void value() {
해당 테스트도 **invalidateFormatAlias_throw_exception** 테스트 메서드처럼 
(구체적인 테스트 내용은 DisplayName으로도 적어주겠지만) 

> 테스트할 메서드_테스트 상황

으로 메서드명을 지어주면 좋을 것 같아요.

2021-05-12 17:25 UTC, sefide commented on src/main/java/com/project/kodesalon/model/domain/member/vo/Alias.java
> +    public String value() {
자바 명명 규칙 중 하나인
- 메서드 명은 동사로 이루어져야 한다.

는 해당 메서드가 어떤 역할을 하는지 명확히 보여주기 위해서인 것 같아요 ~ 
value 말고 다른 좋은 네이밍은 없을까요 ?

2021-05-12 17:25 UTC, sefide commented on src/main/java/com/project/kodesalon/model/domain/member/vo/Alias.java
> +        if (Pattern.matches(ALIAS_PATTERN, alias)) {
compile 메서드가 비용 은근 많이 잡아먹어서 요거 중요합니당

2021-05-12 17:25 UTC, sefide commented on src/test/java/com/project/kodesalon/model/domain/member/vo/AliasTest.java
> +            INCLUDE_BLANK, NOT_START_WITH_ALPHABET, INCLUDE_SPECIAL_SYMBOL})
pattern 관련 테스트는 조금 꼼꼼하게 보는게 좋아요. 
숫자와 영어와 가능하다면, 한글과 같은 다른 언어나 더 나아가서 이모지 같은 문자도 같이 확인해보면 좋을 것 같아요.

위에서 커버리지가 100% 나와서 충분하다 했는데.. 100%여도 모든걸 완벽하게 커버하는 테스트가 아닐수도 있다는 점...

2021-05-13 03:50 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/domain/member/vo/Alias.java
> +        if (Pattern.matches(ALIAS_PATTERN, alias)) {
이 부분은 공부하고 다시 반영하겠습니다!

2021-05-13 03:52 UTC, sdrs6921 commented on src/test/java/com/project/kodesalon/model/domain/member/vo/AliasTest.java
> +            throws NoSuchMethodException {
초기에는 private 메서드를 테스트하는 방식으로 사용해서 해당 Exception을 사용했는데 다시 public 메서드로 테스트 하는 방법으로 변경하고 빼는 것을 깜빡했습니다! 이 부분도 반영하겠습니다.

2021-05-13 03:53 UTC, sdrs6921 commented on src/test/java/com/project/kodesalon/model/domain/member/vo/AliasTest.java
> +    void value() {
추후에는 이러한 방식으로 테스트 메서드를 작성하도록 반영하겠습니다.

2021-05-13 03:55 UTC, sdrs6921 commented on src/test/java/com/project/kodesalon/model/domain/member/vo/AliasTest.java
> +            INCLUDE_BLANK, NOT_START_WITH_ALPHABET, INCLUDE_SPECIAL_SYMBOL})
생각해보지 않는 부분이었네요. 참고하고 반영해보겠습니다!

2021-05-13 05:27 UTC, sdrs6921 commented
지난 리뷰를 반영하면서 2가지 궁금한 점이 있습니다.  

먼저, 이모지가 들어오는 것도 테스트 해 보려고 하는데 제가 찾아본 봐로는 emoji-java 의존성을 추가해서 사용하는 것이 가능하다는 것을 알 수 있었습니다. 테스트만을 위해서 emoji-java 의존성을 추가하는 것이 바람직한지 궁금합니다.

두 번째로 Alias 태스트 코드를 작성할 때 많은 상수 속성이 있는데 이 부분을 상수 클래스는 것이 좋을까요?

2021-05-13 13:47 UTC, seonghun127 approved these changes
> 지난 리뷰를 반영하면서 2가지 궁금한 점이 있습니다.
먼저, 이모지가 들어오는 것도 테스트 해 보려고 하는데 제가 찾아본 봐로는 emoji-java 의존성을 추가해서 사용하는 것이 가능하다는 것을 알 수 있었습니다. 테스트만을 위해서 emoji-java 의존성을 추가하는 것이 바람직한지 궁금합니다.
두 번째로 Alias 태스트 코드를 작성할 때 많은 상수 속성이 있는데 이 부분을 상수 클래스는 것이 좋을까요?

희상쓰 커밋단위를 되게 작게 작업한 부분이 아주 👍
리뷰 반영하느라 고생했으~

위 질문에 답을 하자면
* 이모지 테스트는 의존성을 추가하면서까지 할 필요는 없을 거 같고 나중에 DB에 잘 저장되는지 문자 collation 값만 잘 설정해줘서 확인하는 정도만 해줘도 충분하다 생각해.
* 그리고 테스트 코드의 상수는 따로 분리하는 것도 비용이라고 생각해서 나는 비추라고 생각해. 나는 테스트 코드에서 상수를 빼는걸 별로 좋아하진 않는데, 지금 상수로 뺀 부분은 테스트 하기 위한 인자 값인데 이건 상수로 안빼도 되지 않을까 싶어. 상수는 그 자체로 로직안에서 의미를 명확히 하기 위함 & 재사용 성을 위해 사용하는데 테스트 코드에선 재사용도 없고 무얼 테스트하는지 @DisplayName으로 충분히 설명하니까 상수로 빼는게 오히려 비효율적인 느낌쓰야. (굳이 인자값에 대한 설명을 할 필욘 없을 거 같애)

2021-05-13 14:00 UTC, sefide approved these changes
오늘도 빠른 반영이네요 👍🏼 

- emoji-java가 이모지 제거를 위한 라이브러리인 것 같은데, 해당 라이브러리를 추가하면 이모지가 포함된 문자열인지 테스트하는데에 이점이 있는걸까요 ? 
일단 테스트 자체를 목적으로 하는게 아니고 특정 기능을 테스트하기 위해서 라이브러리를 추가하는 건 지양하는 것 같아요. 라이브러리를 추가하기 앞서 최대한 직접 재연해보자 합니다 !
- 상수 부분은.. 답하기 앞서 Alias 테스트에 선언된 상수들이 다른 테스트에서도 사용되는걸까요? 그런게 아니라면 상수로 선언을 안해도 될 것 같아요 ~ 마찬가지로 테스트를 위한 상수 클래스 또한 불필요한 것으로 보입니다 !

2021-05-14 04:08 UTC, merged