Feature/#16
kodesalon/project pull request #32
Opened 2021-05-18 10:11 UTC by sdrs6921

### 개요
- 이슈 번호 : #16 회원 도메인 설계
- 내용 : 회원 엔티티와 VO 객체를 Mapping 하여 회원 도메인 설계

### 작업 사항
- 회원 도메인 테스트 코드 작성
- VO 객체를 Domain 객체와 매핑
- VO 객체 컬럼 설정 추가
- Member 도메인 구현

### 기타
- 질문 사항이 있습니다. 지난 번 피드백에서 메서드의 이름은 동사여야 한다는 자바 컨벤션을 지켜야 한다는 피드백을 받고, 각각의 VO 객체에서 `getValue` 메서드를 활용하였습니다.  하지만 회의를 진행하며 `엘레강트 오브젝트`라는 책에서는 메서드 이름을 정의 할 때 객체를 반환하는 메서드는 `builder`를 사용하고, 여기서는 명사를 사용하여 메서드 이름을 사용하라는 내용이 있었습니다. 저는 개인적으로 `getValue` 또한 VO 객체에게서 값을 가져온다는 의미를 담았기 때문에 잘 읽히는 코드라고 생각하고, `value`라는 메서드는 builder 패턴의 메서드라고 생각해서 좋은 naming 방식이라고 생각합니다. 추가로 `toString` 메서드는 해당 VO 객체를 String 타입으로 반환하는 의미를 담은 메서드를 `Override` 해서 사용하는 방식을 생각해 보았는데 3가지 방식에 대한 리뷰어님들의 생각이 궁금합니다!

- JPA 관련 설정이 정확하게 되어 있는지, 부족하거나 개선해야할 점이 어떤 부분이 있는지 위주로 리뷰를 받고 싶습니다!

2021-05-19 02:50 UTC, sefide reviewed
jpa 관련해서는 저도 아직 많은 공부가 필요한 입장이라 성훈님의 도움이 많이 필요할 것 같습니다. 오늘은 제가 리뷰할 수 있는게 별로 없네요  ㅠ.ㅠ 

<br>

_질문 주셨던 메소드의 명명규칙에 대해서는.._

#9  에서 value()가 메소드라는 이유로 다른 네이밍을 제안했었던 것 같아요 :0 
alias 값을 반환하는 접근자라서 get-을 붙이신 것 같네요.

저는 기본적으로 객체에서 접근자 메서드가 `정말` 불가피한 경우에는 get을 붙여서 명확하게 보여주는걸 선호해요. (특히나 현업에서는 자바 빈 표준이 기본이라) 이후에 코드 보시는 분들에게 개선의 여지를 넘겨준다고 할까요. 책임 회피일수도 있고요 ㅎ

 `엘레강트 오브젝트` 를 읽어보진 않았지만 접근 메서드가 값을 반환한다는 점에서 builder 라고 보는것 같은데 맞을까요 ? 같은 관점에서 객체가 값을 어떻게 만들어서 주던 요청자 입장에서는 받기만하면 되니 좋은 네이밍이 있다면 메서드라도 동사가 안붙어도 문제가 없을거라 봅니다. 다만 이 부분은 함께 개발하는 분들과 지향하는 프로그래밍 전략을 바탕으로 명명 규칙에 대한 이야기를 나누는게 먼저일 것 같습니다.

정리하자면 
"객체에서 접근자는 지양하고, 기본 명명 규칙을 기본으로 하되 더 좋은 네이밍이 있다면 사용해봐도 좋다."겠네요.

2021-05-19 02:50 UTC, sefide commented on src/test/java/com/project/kodesalon/model/member/domain/vo/AliasTest.java
> -        //then
다른 테스트 클래스에도 남아있는게 보이네요 ~ 
나중에 같이 지워줘도 좋을것 같아요.

2021-05-19 02:50 UTC, sefide commented on src/main/java/com/project/kodesalon/model/member/domain/vo/Alias.java
> +    private static final String INVALID_ALIAS_EXCEPTION_MESSAGE = "Alias 는 영문으로 시작해야 하며 4자리 이상 15자리 이하의 영문 혹은 숫자가 포함되어야 합니다.";
명확한 에러 메세지 👍🏼

2021-05-19 05:14 UTC, sdrs6921 commented on src/test/java/com/project/kodesalon/model/member/domain/vo/AliasTest.java
> -        //then
넵 이부분은 다시 확인 후에 반영하겠습니다.

2021-05-19 05:21 UTC, sdrs6921 commented
> `엘레강트 오브젝트` 를 읽어보진 않았지만 접근 메서드가 값을 반환한다는 점에서 builder 라고 보는것 같은데 맞을까요 ?  

넵 맞습니다!

> 객체가 값을 어떻게 만들어서 주던 요청자 입장에서는 받기만하면 되니 좋은 네이밍이 있다면 메서드라도 동사가 안붙어도 문제가 없을거라 봅니다.   

다른 분은 무조건적으로 `get` 을 붙이기 보다는 조금 더 고민해보고 메서드 명을 지어보는 게 좋을 것 같다는 의견을 말씀하셨습니다. 저도 사실 `엘레강트 오브젝트` 라는 책을 읽어보지는 않았지만 builder 메서드와 조정자 메서드에 대해서 듣고 찾아보니 값을 반환하는 메서드에 대해서는 명사로 짓는 것이 좋고, 값을 변경하는 메서드는 동사로 짓는 것이 좋다는 내용의 글이 있었습니다. 예시로 `Math` 클래스의 `max` 라는  메서드도 `getMax` 가 아니라 `최대값` 이라는 명사형 메서드 명이 있어서 개인적으로 고민해보다가 리뷰어님께 질문을 드렸습니다.

2021-05-20 09:00 UTC, sefide commented
맞아요 ! 무조건 `get` 을 붙이는 건, 오히려 메서드명을 복잡하게 만들어서 좋은 습관은 아닌것 같아요 ~ 
말씀주신 것처럼 max 메서드가 좋은 예시가 되네요 !

> 값을 반환하는 메서드에 대해서는 명사로 짓는 것이 좋고, 값을 변경하는 메서드는 동사로 짓는 것이 좋다

이 부분에서 왜 좋은지는 좀 더 고민해봐야 할 것 같아요 ! 책 한번 읽어볼게요 ㅎㅎ

2021-05-20 13:38 UTC, seonghun127 requested changes
아이고 리뷰가 늦었습니다🙏

이것저것 구현된게 많아서 일단 고생많았으~ 커밋보니까 JPA 설정 추가, final 키워드 제거, 의존성 버전 변경 등 되게 많은 걸 했던데 쉽지 않았을텐데 👍

jpa 관련 위주로 리뷰를 남겨봤으~

그리고 질문 준 내용에 대해 이야기해보자면
* `엘레강트 오브젝트` 라는 책은 유익한 내용도 있고 반발을 일으키는 내용도 있다고 생각해. (지극히 개인적인 의견입니다.) 참고 자료가 될 순 있어도 반드시 이 책에 나온대로 따를 필요는 없어. 이 책을 기반으로 자신의 생각을 정리해서 개발하는게 중요하다고 봐. 그런 차원에서 get이라는 키워드가 주는 생각을 잘 나열해줘서 고맙고 좋은 자세라고 생각해. 일단 get 이 주는 키워드에 대해서 나의 생각은 컨밴션을 정해서 프로젝트 전반적으로 통일성을 유지 시키면 지금의 방식도 괜찮다 라는 거야. 하나 궁금한건 get이라는 키워드는 단순히 객체의 필드에 접근하는 getter 에 대해서만 `builder` 라고 생각하냐는거야. 나중에 비지니스 로직을 담는 Service 레이어에서도 데이터 조회 메서드의 이름도 단순 명사로 가져갈건지 고민해볼 필요가 있을 거 같애. 그리고 기본적으로 스프링에서 제공해주는 직렬화 라이브러리 Jackson은 직렬화 객체에 반드시 getter가 있어야하는데 이 getter는 `getXXXX()` 어야 할 거야. 그럼 이런 직렬화 대상이 되는 객체에 대해서는 데이터 조회 메서드는 어떻게 할 것인지도 고민해봐야할 거고. 어찌됐든 전반적인 통일성을 계속 유지시켜나가는게 중요하니까. 나중에 어떤 객체는 이렇고 어떤 객체는 저렇고 되는 코드가 되지 않았으면 해~

* `toString()`에 대해선 헷갈리는 부분이 코멘트에 남긴 내용이 엔티티에 구현될 `toString()` 인건가? 차라리 너의 생각대로 구현해보고 이에 대해서 이야기해보면 좋을 거 같어. 참고로 `toString()` 메서드는 말그대로 객체를 문자열화 시킨다는 건데, 객체가 갖고있는 필드에 대한 정보를 나열해주는 역할이야. 즉, `toString()`으로 이 객체는 필드들에 이러한 정보를 가지고 있는 객체다 라고 나타낼 때 사용되지. 그래서 서버에선 로그를 남길 때 `toString()` 오버라이드해서 필드 데이터를 문자열로 나열하도록 하고 이를 통해서 객체에 대한 정보를 남기는 방식을 많이 사용해. 그래야 로그를 볼 때 버그를 쉽게 찾을 수 있고 문제가 되는 상황에서 그 원인 파악이 수월해. 이 부분을 고려하면서 `toString()` 을 재정의해봐~

2021-05-20 13:38 UTC, seonghun127 commented on src/main/resources/application.yml
> +---
JPA 성능 개선을 위해 캐시를 이용해서 메모리를 효율적으로 관리하는 방법도 공유합니다~

https://www.manty.co.kr/bbs/detail/develop?id=98

2021-05-20 13:38 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/domain/vo/Alias.java
> +    @Column(name = "alias", nullable = false, unique = true, length = 15)
이거는 개인적 취향인데, unique 설정은 동시에 index를 거는거기때문에 클래스 레벨에 선언해주는 `@Table` 의 속성 값중 uniqueConstraints 에서 선언해주는게 좋다고 생각해. (현재는 엔티티에 `@Table` 어노테이션이 없지만 붙여줘서 테이블 명도 같이 명시해주면 좋을 거 같아)

장점으로는
* 다른 index가 있다면 같이 테이블의 모든 인덱스를 `@Table`의 indexes 속성 값과 같이 한눈에 파악할 수 있다는 점
* 멀티칼럼으로 유니크 제약 조건을 걸 수 있다는 점



이 있을 거 같애

2021-05-25 12:39 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/member/domain/vo/Alias.java
> +    @Column(name = "alias", nullable = false, unique = true, length = 15)
제가 공부해본 바로는 여러개의 값에 unique 속성을 줄 수 가 없기 때문에 이후에 unique한 필드가 추가 될 수도 있으니 Table에 uniqueConstraint에서 선언해 주는 게 좋을 것 같다는 생각이 드는 데 제가 공부한 내용이 맞을까요??

2021-05-29 15:32 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
> +                columnNames = {"alias"}
`@UniqueConstraint` 속성 값 중 name 이 존재하는데 유니크 인덱스 이름도 설정해주면 좋아요~ 나중에 인덱스 이름만 봐도 어떤 칼럼에 설정된 인덱스인지 쉽게 인지할 수 있습니다. (코드에서뿐만 아니라 DB 스키마 확인 시에도 쉽게 판단이 가능합니다.)

2021-05-29 15:35 UTC, seonghun127 approved these changes
리뷰 반영 굳!

single comment로 리뷰 하나 달아놨으니 참고하면 될 듯!

2021-05-29 15:43 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/domain/vo/Alias.java
> +    @Column(name = "alias", nullable = false, unique = true, length = 15)
그치. 다중 칼럼에 유니크 인덱스를 건다면 (다시 말해, a와 b라는 칼럼이 존재한다면 a와 b 각각이 아닌 (a,b)에 유니크 인덱스를 걸 경우)
`@UniqueConstraint ` 로 선언해줘야 다중 칼럼에 인덱스가 걸렸구나를 쉽게 알 수 있지.

사실 `@UniqueConstraint `나 `@Index` 와 같은 설정은 jpa에서 `ddl-auto: create / update` 일 경우에 인덱스 생성을 위해 사용되는 설정들인데 이미 DB를 따로 구축해놓고 `ddl-auto: none` 설정을 주면 이 어노테이션을 가지고 jpa는 어떤 행위를 하진 않아. 다만, 코드레벨에서 이 어노테이션들을 보고 지금 해당 엔티티에 매핑된 테이블에 어떤 인덱스가 걸려있구나를 쉽게 확인할 수 있는 장점이 있어서 이야기했던거야.

2021-05-31 13:31 UTC, seonghun127 approved these changes

2021-06-01 10:51 UTC, merged