Feature/#14/게시물 제목 필드 구현
kodesalon/project pull request #35
Opened 2021-05-24 18:24 UTC by seongbeenkim

### 개요
- 이슈 번호 : #14
- 내용 : 게시물 도메인의 제목 필드 구현

### 작업 사항
- 게시물 도메인의 제목 필드를 객체로 구현 및 테스트 코드 작성

### 기타
-

2021-05-26 13:39 UTC, sefide commented on src/test/java/com/project/kodesalon/model/board/domain/vo/TitleTest.java
> +        assertThat(title).isEqualTo(new Title(boardTitle));
입력값을 통해 Title 객체가 잘 생성되었는지 확인하기 위한 `생성 테스트`네요 ~ 
추가적으로, 생성된 title 객체가 null은 아닌지 확인해줘도 좋을것 같아요

2021-05-26 13:55 UTC, sefide requested changes
null 관련 코멘트 몇개 달았습니다. 

별도로 궁금한게 #34 와 겹치는 내용이 있는데 Feature/#33/배포-및-운영-환경-구성 브랜치에서 생성한건가요 ~ ?

2021-05-26 13:55 UTC, sefide commented on src/main/java/com/project/kodesalon/model/board/domain/vo/Title.java
> +        validate(title);
title 값이 null인 경우는 없을까요 ?

2021-05-26 13:55 UTC, sefide commented on src/test/java/com/project/kodesalon/model/board/domain/vo/TitleTest.java
> +        assertThat(title).isEqualTo(new Title(boardTitle));
입력값을 통해 Title 객체가 잘 생성되었는지 확인하기 위한 생성 테스트네요 ~
추가적으로, 생성된 title 객체가 null은 아닌지 확인해줘도 좋을것 같아요

2021-05-26 13:55 UTC, sefide commented on src/test/java/com/project/kodesalon/model/board/domain/vo/TitleTest.java
> +    public void check_blank(String blank) {
title 값이 null인 경우가 있다면 
@NullAndEmptySource 사용해서 테스트하는 방법도 있습니당

2021-05-26 14:14 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/domain/vo/Title.java
> +        validate(title);
null일 경우도 추가해주면 좋을 것 같네요! 수정하겠습니다!

2021-05-26 14:15 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/board/domain/vo/TitleTest.java
> +        assertThat(title).isEqualTo(new Title(boardTitle));
해당 부분 내용 포함하여 위의 코멘트에 댓글달았습니다!

2021-05-26 14:17 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/board/domain/vo/TitleTest.java
> +    public void check_blank(String blank) {
넵넵 감사합니다 해당 어노테이션 사용하여 수정하겠습니다!


> null 관련 코멘트 몇개 달았습니다.
> 
> 별도로 궁금한게 #34 와 겹치는 내용이 있는데 Feature/#33/배포-및-운영-환경-구성 브랜치에서 생성한건가요 ~ ?

아.. 넵넵 develop에서 해야 했었는데 Feature/#33/배포-및-운영-환경-구성 작업 끝내고 바로 #34 브랜치를 생성하여 작업을 했네요ㅠㅠ
다음부터는 develop에서 하도록 하겠습니다ㅠㅠ

2021-05-26 14:37 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/board/domain/vo/TitleTest.java
> +    public void check_blank(String blank) {
`@NullAndEmptySource` 라는 것도 있군뇨. 어노테이션 하나 얻고 갑니다. 😀

2021-05-26 14:47 UTC, seonghun127 requested changes
이전 희상이가 구현했던 VO랑 매우 비슷하기 때문에 리뷰 간단하게 남겨요~

`Title` 객체에서 equals, hashcode 를 재정의해줬다면 다른 VO도 통일성있게 구현해주면 어떨까 싶습니다~ 이 부분 비지니스 로직과는 먼 이야기니 희상이랑 이야기해서 맞추면 좋을 거 같아요

2021-05-26 14:47 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/domain/vo/Title.java
> +    private final String title;
`final` 는 JPA 설정이 추가되면 제거되어야할 거 같아요~
전에 슬랙에 남겼던 이야기 같이 남깁니다

> 질문 내용
"VO 객체 내부 필드를 final로 선언했는데 JPA 때문에 추가해줘야하는 기본 생성자는 어떻게 해야하나?"
우선, VO 객체 내부에 선언한 필드에 final 키워드를 추가해줬는데 이는 제거해줘야해 (리뷰하면서 놓친 부분이야; 쏘리 :pray: )
기본적으로 jpa 에서 임베디드 타입을 선언할 때 대상 객체(ex. Email, Password 등)에 기본 생성자가 필요하므로 이미 파라미터가 선언된 생성자 때문에 final을 제거해줄 수 밖에 없어.
대신 기본 생성자를 사용할 수 없도록 접근 제어자를 private으로 선언해주면 불변 객체 상태를 유지할 수 있을거야.

2021-05-26 14:58 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/domain/vo/Title.java
> +    private final String title;
넵넵 일단 JPA 신경안쓰고 객체 중심으로 구현 먼저 하도록 한 부분이었어서 
JPA 설정 추가된다면, 희상이가 이미 피드백 받은 내용 및 적용하여 구현한 기반으로 맞춰 구현할 예정입니다! 감사합니다!

2021-05-26 15:04 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/domain/vo/Title.java
> +    private final String title;
네네 알겠습니다

그리고 보니까 내가 남긴 comment에서 equals, hashCode 이야기했는데 #20 브랜치에서 작업해준 거 같네~

2021-05-26 16:18 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/board/domain/vo/TitleTest.java
> +    public void check_blank(String blank) {
JPA 설정하지 않고 리뷰 요청 후
JPA 설정 후 다시 리뷰 재요청을 드리게 됐는데 
다음 PR부터는 번거롭지 않게 JPA까지 모두 적용하여 바로 develop에 머지할 수 있게 PR 요청드리도록 하겠습니다 죄송합니다 ㅠㅠ

> title 값이 null인 경우가 있다면
> @NullAndEmptySource 사용해서 테스트하는 방법도 있습니당

@sefide 말씀해주신 해당 어노테이션 적용하였으나 JPA 적용하는 과정 중 @Column(nullable = false) 적용하는 과정에서 null 체크를 어노테이션에서 해주기 때문에 테스트 코드를 제거해도 된다고 생각하여 테스트 코드를 지우게 됐는데 이렇게 제거해도 되는건지 궁금합니다!

2021-05-26 16:23 UTC, seongbeenkim commented
JPA 설정하지 않고 리뷰 요청 후
JPA 설정 후 다시 리뷰 재요청을 드리게 됐는데 
다음 PR부터는 번거롭지 않게 JPA까지 모두 적용하여 바로 develop에 머지할 수 있게 PR 요청드리도록 하겠습니다 죄송합니다 ㅠㅠ

@seonghun127 @sefide 
equals, hashCode를 @EqualsAndHashCode을 사용하여 구현해주도록 했는데 궁금한 사항이 있습니다
Lombok 어노테이션을 생성되는 @EqualsAndHashCode, @NoArgsConstructor와 같은 메서드들의 테스트 코드는 작성하지 않아도 된다고 생각을 하였고, 그 과정에서 코드 커버리지에서 Lombok 어노테이션을 통해 생성된 메서드를 제거하기 위한 설정 추가를 하였습니다!
Lombok 메서드에 대한 테스트 코드도 추가해야 하는 건지 아니면 제가 설정한 방식대로 해도 되는 건지 궁금합니다!

2021-05-29 03:35 UTC, sefide approved these changes
빠른 반영을 해주셨네요 ! 👍🏼 

- Lombok으로 생성된 메서드는 커버리지에 반영하고 싶지 않다면 제외 설정을 추가해도 무방할 것 같습니다 ~
    - 다만, 필요에 따라서 Lombok 어노테이션으로 생성된 메서드를 직접 테스트하기도 하는데요. 
예를 들면, `isX`이라는 이름을 가진 boolean 필드의 경우 `setIsX`라는 setter를 사용하기를 원하지만 Lombok의 @Setter를 사용하는 경우 기본적으로 필드명과 동일한 `setX`라는 setter를 생성하는데요. 이와 관련해서 테스트를 한 경험이 있었네요.
    - 그 외에는 대부분 자연스럽게 테스트되기 때문에 따로 테스트를 안하는 편인것 같아요..
이번에 추가된 @EqualsAndHashCode로 생성된 equlas 메서드 또한 AbstractAssert의 isEqualsTo를 수행하면서 테스트가 되기 때문에 커버리지에 영향이 없는것 같네요 ~ :0

2021-05-31 13:33 UTC, seonghun127 approved these changes
일요일날 이야기했던 내용도 포함돼있어 approve 합니다~

2021-05-31 16:14 UTC, merged