Feature/#20/회원 로그인 기능 구현
kodesalon/project pull request #36
Opened 2021-05-25 12:24 UTC by sdrs6921

### 개요
- 이슈 번호 : #20 
- 내용 : 회원 로그인 기능 구현

### 작업 사항
- `MemberRepository` 테스트 코드 작성 (`findByAlias()`)
- `MemberRepository` 구현
- `MemberService` 테스트 코드 작성 (`login`)
- `MemberService` 구현(`login`)
- `Member` 엔티티 내에 `비밀번호 체크 메서드` 테스트 코드 작성
- `Member` 엔티티 `비밀번호 확인 메서드` 구현
- `MemberContoller` Login `RestDocs` 작성
- `MemberController` `Login` 구현

### 기타
- `Controller`와 `Service` 그리고 `Repository` 의 테스트 코드를 이번에 처음 작성해 보았는 데 더 `개선` 할 점이 없는 지 궁금합니다.
- 각각의 `컴포넌트` 들이 올바르게 활용 되었는 지 좀 더 깔끔하게 짜는 방법은 없었는 지 위주로 피드백 해주시면 감사하겠습니다.
- `Rest Docs 설정`이 제대로 되었는 지 궁금합니다. 특히 `Controllerd 테스트 코드`에 추가로 `확인` 해야 할 점이 없는 지 궁금합니다.
- 지난 번 `Member 객체` 에 관한 피드백은 해당 branch로 분기 후 `반영` 하여 다시 `PR 요청` 을 올리겠습니다.

2021-05-29 05:46 UTC, sefide requested changes
몇 가지 코멘트 남겼는데 다른 분들의 의견이 궁금한 내용도 있네요 ~
제 의견이 정답은 아니니 확인해보시고 편하게 반영해주시면 좋을것 같아요 !

2021-05-29 05:46 UTC, sefide commented on src/test/java/com/project/kodesalon/model/member/dto/LoginResponseDtoTest.java
> +    void login_failed_create_failed_response_dto() {
[FEATURE] - 회원 로그인 기능 구현 #20 
```markdown
## 원하는 결과
회원 별명, 비밀번호 일치 시 로그인, 아닐 경우 예외
```
로그인 실패 시 예외를 발생하는게 원하는 결과인 것 같은데 다른 실패하는 시나리오가 있을까요 ?

2021-05-29 05:46 UTC, sefide commented on src/test/java/com/project/kodesalon/model/member/service/MemberServiceTest.java
> +        when(member.getId()).thenReturn(MEMBER_ID);
member에서 getId(), getAlias(), isIncorrectPassword() 메서드 결과값을 스터빙하기보다는 
67 라인에서 반환하는 member 객체를 구체적으로 설정해서 테스트해주는건 어떨까요 ? 

member의 값에 따라 테스트가 동작할 수 있도록이요 ! 
- 존재하는 Alias의 회원정보에 Password가 일치하는 member 
- 존재하는 Alias의 회원정보에 Password가 일치하지 않는 member

2021-05-29 05:46 UTC, sefide commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +        Member member = memberRepository.findMemberByAlias(new Alias(loginRequestDto.getAlias()))
이후 남아있는 요구사항을 봤을때 alias를 이용해 회원정보를 조회하는 로직은 따로 메소드로 분리해도 좋을것 같아요 ~

2021-05-29 06:49 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +        return new ResponseEntity<>(new LoginResponseDto(member.getId(), member.getAlias()), HttpStatus.OK);
넵!! 이 부분은 추후에 다시 반영하겠습니다!

2021-05-29 06:51 UTC, sdrs6921 commented on src/test/java/com/project/kodesalon/model/member/service/MemberServiceTest.java
> +        when(member.getId()).thenReturn(MEMBER_ID);
저도 객체를 구체적으로 설정해주려고 했는데 Jpa를 사용했기 때문에 Member객체의 ID 필드를 직접 설정해주지 못하는 부분이 있었습니다. 그래서 member의 ID가 null값으로 리턴되는 문제가 발생하는 데 혹시 이런 부분을 테스트 할 좋은 방법이 있을까요? 공유해주시면 감사하겠습니다!

2021-05-29 06:53 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +        Member member = memberRepository.findMemberByAlias(new Alias(loginRequestDto.getAlias()))
넵!! 회원 정보를 조회하는 로직을 따로 분리해보겠습니다!!

2021-05-29 07:10 UTC, sdrs6921 commented on src/test/java/com/project/kodesalon/model/member/dto/LoginResponseDtoTest.java
> +    void login_failed_create_failed_response_dto() {
> 로그인 실패 시 예외를 발생하는게 원하는 결과인 것 같은데 다른 실패하는 시나리오가 있을까요 ?

다른 실패하는 시나리오는 없습니다.

2021-05-29 08:23 UTC, seonghun127 requested changes
희상쓰 작업하느라 고생했으~
하면서 이것저것 삽질 많이 한게 느껴져서 좋은 경험을 했을 거라 생각합니다 ㅎㅎㅎ
처음해보는 것들이 많았을 텐데 100% 다 이해한다보단 이런 것들이 있구나 정도만 느껴도 충분한 작업이라 생각해. 앞으로 계속 작업하면서 익숙해질 내용들이기에 화이팅하시지요 :)

> 커밋이 너무 많아 놀랬으... 작업 범위를 조정해서 PR 단위를 줄이는 것도 좋을 거 같애~
작업하다보면 고구마줄기처럼 해야할 게 계속 나오는 경우가 있는데 그럴 때 어느 부분에서 끊고 Issue를 새로 따서 작업하는 것도 좋은 방법 중 하나라 생각합니다

2021-05-29 08:23 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
> +        this.mockMvc = MockMvcBuilders.webAppContextSetup(webApplicationContext)
현재 이 테스트 코드에 정체성을 정리할 필요가 있을 거 같은데요.
이게 인수테스트 (AcceptanceTest)인지 컨트롤러에 대한 단위 테스트(Unit Test)인지 단순히 API 문서를 만들기 위한 테스트 인지를 정해야할 거 같아요.

왜그러냐면 `@SpringBootTest` 라는 어노테이션을 이용해서 이 어플리케이션에 대한 Application Context를 통째로 띄우고있는데요 (물론 테스트용이긴 하지만), 그러면 모든 빈을 등록하고 실제 App이 실행될때 처럼 인프라 환경을 구축하게 되는데요 (DB 포함) 자연스레 테스트 수행 시간이 길어질 수 밖에 없습니다.

물론 인수테스트를 하는거라면 실제 App이 실행될 때처럼 같은 인프라 환경을 구축하는게 당연하지만 지금 테스트 코드는 인수테스트라고 할 수 없는게 `MemberService` 객체를 Mocking 하고 있습니다. 목 객체를 사용하는 이유는 보통 단위 테스트 작성할 때 많이 사용하는데 비지니스 로직에 집중하기 위해 그외 부가적인 부분(또는 직접 통제하지 못하는 부분)을 배제시키기 위함인데요 인수테스트에서는 실제 앱이 시작부터 끝까지 동작하는 일련의 프로세스를 전부 테스트하는 것이기 때문에 Mocking을 하면 안됩니다.

그러다고 이 테스트가 단위테스트라고 할 수 없는게 쓸데없는 빈들까지 모두 Context에 등록하는 인프라 환경을 구축하고 (DB 포함) 있습니다. 물론 API에 대한 단위 테스트를 작성하려면 MockMvc 객체를 가지고 직접 요청을 쏴야하기 때문에 다른 단위 테스트 코드(`MemberService`와 같은)처럼 작성하면 안됩니다.
그래서 `MockMvcBuilders`에서 아래 메서드를 제공합니다.
`org.springframework.test.web.servlet.setup.StandaloneMockMvcBuilder`
위 메서드를 사용하면 `@SpringBootTest`와 달리 필요한 빈을 가지고 API 테스트를 하기위한 최소한의 인프라 환경을 구축한다고 나와있네요.
위 메서드로 이동해서 javadoc 한번 읽어보시면 좋을 거 같습니다.

참고하면 좋을 자료도 공유드립니다. (사실 인수테스트에 대해 잘 몰라서 이 부분은 저도 좀 더 찾아볼게요.)
https://dadadamarine.github.io/java/spring/2019/03/16/spring-boot-validation.html

2021-05-29 08:23 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/common/GlobalExceptionHandler.java
> +    private final Logger logger = LoggerFactory.getLogger(this.getClass());
롬복에서 위 선언을 대신해주는 어노테이션을 제공해줍니다. 참고하세요~ `@Slf4j`

2021-05-29 08:47 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +    private static final String NO_MEMBER_ELEMENT_EXCEPTION_MESSAGE = "존재하는 Alias를 입력해주세요.";
만약 이 예외 메세지가 화면에 노출되는 문구라면 Alias라고 말하기보단 사용자가 접한 단어를 사용하는게 좋을 거 같아요~
이부분은 정책 이슈이기 때문에 프론트랑 이야기를 나눠봐야할 거 같네요. 
만약 화면에 "Alias"라고 노출된다면 그대로 유지해도 되구요.

2021-05-29 12:08 UTC, sefide commented on src/main/java/com/project/kodesalon/model/member/controller/MemberController.java
> +    public MemberController(MemberService memberService) {
오호 그렇네요 ! @AllArgsConstructor도 마찬가지고.. 배워갑니다 👍🏼

2021-05-29 12:26 UTC, sefide commented on src/test/java/com/project/kodesalon/model/member/service/MemberServiceTest.java
> +        when(member.getId()).thenReturn(MEMBER_ID);
아하 제가 어떤 것을 테스트하느냐에 대한 이해가 부족했네요
- `MemberService.login()`의 비즈니스 플로우 자체에 대한 테스트가 중점 !!!
- `isIncorrectPassword()`은 MemberTest에서 보장
- `Member` 객체에 대한 직접적인 설정은 불필요한 포인트 

친절한 설명에 한번에 이해가 갔습니다. 감사합니다 ! 
@sdrs6921 님 혼란을 드렸네요 이 부분은 @seonghun127 님 의견을 참고해주세요 !~!

2021-05-31 07:47 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/common/GlobalExceptionHandler.java
> +    private final Logger logger = LoggerFactory.getLogger(this.getClass());
몰랐던 내용인데 참고하겠습니다!!!

2021-05-31 07:50 UTC, sdrs6921 commented on src/test/java/com/project/kodesalon/model/member/repository/MemberRepositoryTest.java
> +@ExtendWith(SpringExtension.class)
넵!! 이 부분은 공부하고 제거해서 반영하겠습니다!!

2021-05-31 13:34 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
> +        this.mockMvc = MockMvcBuilders.webAppContextSetup(webApplicationContext)
이 부분은 바로 반영하지 않아도 되고 advanced 로 빼서 나중에 적용해도 될 거 같아요~

2021-06-01 09:58 UTC, sdrs6921 commented on src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
> +        this.mockMvc = MockMvcBuilders.webAppContextSetup(webApplicationContext)
> 이게 인수테스트 (AcceptanceTest)인지 컨트롤러에 대한 단위 테스트(Unit Test)인지 단순히 API 문서를 만들기 위한 테스트 인지를 정해야할 거 같아요.

단위 테스트랑 API 문서를 만들기 위한 테스트로 방향을 잡았습니다. 이런 방향으로 다시 반영하겠습니다!

2021-06-03 13:51 UTC, seonghun127 requested changes
리뷰 반영 굳!
컨벤션이나 통일성 관련 리뷰 남겼으니 확인해주세요~

추가로 다희님이 슬랙에서 이야기해준 부분인데 conflict 나는 부분도 어떻게 해결할지 고민해보면 좋을 거 같아요~
https://w1619570373-4tl209278.slack.com/archives/C0213U5MUTF/p1622707048001800

2021-06-03 13:51 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/member/dto/LoginResponseDtoTest.java
>      @DisplayName("Loin이 성공하면 HttpStatus 200과 ID, ALIAS 객체를 생성합니다.")
테스트 명세 내용을 바꿔줘야할 거 같아요~
HttpStatus 내용은 빼야할 거 같네요.

2021-06-03 13:51 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/dto/LoginResponseDto.java
필드 사이에 어노테이션이 없다면 공백은 없애도 될 거 같아요~

2021-06-03 13:51 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
> +                .getResponse();
이 메서드를 사용한 이유는 무엇인가요?
이 메서드의 반환 값을 이용하지 않는거 같아서 지워도 될 거 같은데요.
혹시 제가 잘못 알고 있다면 알려주세요~

2021-06-03 13:51 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/dto/LoginRequestDto.java
> +    private Alias alias;
`LoginResponseDto` 클래스에선 `@Getter` 어노테이션을 클래스에 선언해주었는데요,
이곳에선 필드에 선언해주고 있어서 이 부분도 정해서 통일성을 유지해주면 좋을 거 같아요~

2021-06-04 06:54 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/member/controller/MemberController.java
> +        return new ResponseEntity<>(memberService.login(loginRequestDto), HttpStatus.OK);
몰랐던 내용 이었는데 정적 메서드로 변경하고 ResponseEntity를 정적 메서드를 사용하는 것으로 모든 컨트롤러를 수정하겠습니다!! 훨씬 더 가독성이 있는 것 같아요!!

2021-06-04 06:56 UTC, sdrs6921 commented on src/test/java/com/project/kodesalon/model/member/dto/LoginResponseDtoTest.java
>      @DisplayName("Loin이 성공하면 HttpStatus 200과 ID, ALIAS 객체를 생성합니다.")
명확한 DisplayName으로 변경하겠습니다!!

2021-06-04 06:57 UTC, sdrs6921 commented on src/test/java/com/project/kodesalon/model/member/domain/vo/AliasTest.java
>          assertThatThrownBy(() -> new Alias(invalidFormat)).isInstanceOf(IllegalArgumentException.class)
BddAssertion에 thenThrow를 사용해서 Test 코드를 통일하겠습니다!!

2021-06-04 06:58 UTC, sdrs6921 commented on src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
> +                .getResponse();
반환하는 값이 없는 게 맞아요! PR 날리기 전까지 꼼꼼하게 신경쓴다고 봤는데 이런 부분을 놓친 것 같습니다. 바로 반영하도록 하겠습니다!

2021-06-04 06:59 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/member/dto/LoginResponseDto.java
Getter 어노테이션을 사용했던 자리를 그냥 남겨둔 것 같습니다. 이 분은 신경을 못 쓴 부분이네요. 바로 공백 제거 하겠습니다.

2021-06-05 09:43 UTC, sefide commented on src/main/java/com/project/kodesalon/model/member/controller/MemberController.java
> +        return new ResponseEntity<>(memberService.login(loginRequestDto), HttpStatus.OK);
오 하나 배우고 갑니다 ~

2021-06-05 11:30 UTC, sefide approved these changes
피드백 반영한거 확인했습니다.
특별히 코멘트 할 내용이 없네요 👍🏼

2021-06-05 11:42 UTC, sefide commented
! 한가지 빠트린게 있었네요. 
커밋 로그 보니까 불필요한 코드 제거 시, prefix로 `refactor`랑 `style`을 번갈아가면서 사용하고 있어서요.
이전에는 PR에서는 `chore`를 사용했었던 것 같은데 하나로 통일해주면 좋을것 같습니다 !
당장은 불필요해보이는 코드여서 지웠는데 여러분들과 동시에 작업하다보면 해당 코드가 없어져서 이슈가 생길수도 있어요 ~ 그래서 보다 이력을 확인하게 쉽게 통일해주는게 좋답니다

2021-06-05 11:47 UTC, sdrs6921 commented
> `actor`랑 `style`을 번갈아가면서 사용하고 있어서요.
> 이전에는 PR에서는 `chore`를 사용했었던 것 같은데 하나로 통일해주

제가 `refactor` 랑 `style` 을 혼동해서 사용했네요. `chore` 의 경우에는 `yml` 파일이나 `gradle` 을 수정할 때 사용하기로 규칙을 정했고, 불필요한 코드를 제거하거나 포매팅의 경우에는 `style`로 통일하기로 약속을 했습니다. 앞으로 불필요한 코드를 제거하거나 코드 포매팅을 할 경우에는  `style` 로 통일하겠습니다!!

2021-06-09 14:41 UTC, seonghun127 approved these changes
ControllerTest에서 ObjectMapper로 직렬화를 시도하기 위해 postfix가 Serializer인 클래스를 만들었다가 지웠던 거 같은데, 제가 괜한 말을 해서 고생했겠다는 생각이 드네요; 죄송합니다 🙏

몇몇개 리뷰 남겼으니 확인해주시고 이 PR은 approve 하겠습니다. 반영 후 바로 머지 해주세요~

2021-06-09 14:41 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/member/controller/dto/LoginRequestTest.java
> +        BDDSoftAssertions softly = new BDDSoftAssertions();
이런게 있군뇨. 👍
처음보는 클래스네요. assertAll() 과 비교했을 때 특정 assertion이 실패해도 전부 수행되는 건 같지만 메세지를 좀 더 보기 좋게 해주는 장점이 있는걸로 보이는데, 맞을까요? 추가로 다른 장점도 있으면 알려주세요~

2021-06-09 14:41 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/controller/dto/LoginRequest.java
> +public class LoginRequest {
controller에서만 사용하는 DTO를 만든거죠?
예전에 service 레이어와 controller 레이어에서 사용하는 dto를 분리하는게 좋다 라고 말씀드렸었는데,
곰곰이 생각해보니 그냥 controller에서 service에 있는 dto를 사용하는거랑 별반 다를게 없겠구나 라는 생각이 들었습니다;

그럼 controller와 service 레이어의 dto 의존관계는 어떻게 처리하는게 좋냐라고 생각해보면
dto의 위치는 실제 사용처 레이어(service)에 두고 dto 의존은 고수준(service)의 dto에 의존하도록 구조를 가져가는게 맞는거 같습니다.

다만 이부분은 제가 잘못된 피드백을 드려서 당장 반영하기보단, 다같이 이야기해보면 좋을 거 같네요.

2021-06-09 14:41 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +                .orElseThrow(() -> HttpClientErrorException.create("존재하는 아이디를 입력해주세요.", HttpStatus.BAD_REQUEST,
`HttpClientErrorException` 예외로 변경한 이유가 무엇인가요?
`create()` 메서드의 인자(실제 사용하지 않는)를 너무 많이 전달해줘서 오히려 코드를 더 복잡해지진 않나요?

2021-06-10 04:50 UTC, sdrs6921 commented on src/test/java/com/project/kodesalon/model/member/controller/dto/LoginRequestTest.java
> +        BDDSoftAssertions softly = new BDDSoftAssertions();
> 메세지를 좀 더 보기 좋게 해주는 장점이 있는걸로 보이는데, 맞을까요? 추가로 다른 장점도 있으면 알려주세요~

방금 assertAll과 테스트를 해 봤을 때에는 좀 더 메세지가 간략하게 보여주는 부분이 있는 것 같습니다. 다만 BddSoftAssertions를 사용하게 된 이유는 모든 테스트를 BddAssertions를 사용해서 통일하기 위해서 Assertions의 assertAll 메서드를 쓰는 것 보다 Mockito와 Assertions를 모두 Bdd로 사용하기 위해서 사용하였습니다. 그 외에 다른 장점은 아직 찾지 못했습니다!

2021-06-10 04:52 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/member/controller/dto/LoginRequest.java
> +public class LoginRequest {
넵넵! 알겠습니다~

2021-06-10 04:55 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +                .orElseThrow(() -> HttpClientErrorException.create("존재하는 아이디를 입력해주세요.", HttpStatus.BAD_REQUEST,
> HttpClientErrorException 예외로 변경한 이유가 무엇인가요?

처음에 로그인 Error 처리할 때 인가되지 않은 사용자에 대한 예외를 Custom한 예외를 만들어서 처리하기 보다는 기존의 예외 클래스로 처리하고 싶어서 사용하였습니다! 좀 더 간단한 인자로 생성할 수 있는 생성자를 어제 찾았고 이는 새로운 이슈 브랜치를 만들어서 리팩토링 하겠습니다!

2021-06-10 04:56 UTC, merged

2021-06-10 12:35 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/member/controller/dto/LoginRequestTest.java
> +        BDDSoftAssertions softly = new BDDSoftAssertions();
네네 보니까 `assertAll()` 과 다른 점이 메세지 노출 형식인 거 같네요.
더 좋은 방식인 거 같습니다~ 👍

다만 우려되는 점은 테스트에서 확인해야할 것을 2개의 메서드로 체킹해야하는데 위와 같은 메서드로 한번에 테스트하려는 실수를 범할 수 있을 수 있다는 점입니다. 지금 코드가 그렇다는 것은 아니고 `assertAll()`과 같은 걸로 무조건 한번에 테스트 돌려야지 라는 습관(?)이 생기지 않도록 주의해주세요~