Feature/#21/게시물 작성 기능 구현
kodesalon/project pull request #39
Opened 2021-06-01 13:00 UTC by seongbeenkim

### 개요
- 이슈 번호 : #21 
- 내용 : 게시물 작성 기능 구현

### 작업 사항
- 게시물 생성하여 DB에 저장하는 로직 구현

### 기타
- Controller 테스트 코드는 API 문서 작성에 초점을 맞춰 작성했습니다. 그리고 Controller, Service, Repository 모두 최소한의 환경 및 독립적으로 테스트를 하려고 노력하긴 했는데 이 부분 계속 혼자 고민하긴 보다는 피드백을 받는 것이 더 좋을 것 같아 PR 올립니다!

2021-06-01 13:48 UTC, seonghun127 requested changes
단위 테스트 / 통합 테스트 모두 잘 작성한 거 같습니다~
모든 테스트 코드가 비지니스 로직을 검증하는데만 집중한다고 생각되어집니다.

몇개의 피드백 남겼으니 확인해주세요 :)

2021-06-01 13:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +@Transactional
`@Transactional` 어노테이션은 클래스 레벨에 선언해줄 수 있는 어노테이션이지만 개인적으로 메서드 레벨에 선언해주는 게 더 명확하다고 생각합니다.

왜냐하면 메서드 별로 readOnly, propagation, transactionManager를 다르게 가져갈 수 있기 때문입니다. 클래스, 메서드 레벨 동시에 선언해주면 메서드 레벨의 값으로 트랜잭션이 설정될테지만 메서드에 모두 이 어노테이션을 선언해주게되면 결국 클래스 레벨에 선언해주는건 의미가 없게 됩니다.

2021-06-01 13:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +        } catch (Exception e) {
`Title`, `Content` VO의 유효성 검증에서 예외가 발생할 경우를 ExceptionHandler에서 처리하기 위해 try-catch 로 묶은거 같은데요.
try-catch 로직이 추가됨으로써 인덴트가 늘어나고 로직이 복잡해질 수 있다고 생각합니다. VO에서 발생하는 유효성 검증을 아우르는 예외 클래스를 만들고 이를 상속하는 구조로 가져가면 try-catch 구문을 제거할 수 있을 것으로 판단됩니다.

2021-06-01 13:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/domain/dto/BoardCreateRequest.java
> +public class BoardCreateRequest {
컨트롤러에서만 사용하는 DTO라면 model.board.controller 패키지로 옮기는건 어떨까요? (Service 에서 사용하는 DTO 클래스도 동일합니다.)

현재 패키지 의존관계를 보면
controller -> service, domain / service -> domain, repository 인데요.

controller가 domain 패키지를 의존할 필요가 없어보여요. controller는 service만 알아도 service에서 domain을 알기 때문에 의존관계를 아래처럼 보다 간단하게 가져갈 수 있어보입니다.
controller -> service -> domain / repository

2021-06-01 13:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/controller/BoardController.java
> +    public ResponseEntity save(@RequestBody final BoardCreateRequest boardCreateRequest) {
프론트에서 게시글을 생성하고 보여지는 페이지가 어떤 것인가요?
만약 프론트에서 게시글 작성 후 게시글 상세 페이지로 바로 이동하는 플로우라면 이 API의 반환 값이 필요해보입니다.

그리고 개인적으로 제네릭 타입을 요구하는 클래스 선언 시 제네릭을 명시해주는게 좋다고 생각해요. 그래야 코드를 명확하게 읽을 수 있습니다.

2021-06-01 13:48 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/board/controller/BoardControllerTest.java
> +                .andDo(document("board/create/fail/invalid-title",
403 응답 시 response body 로 내려가는 메세지도 문서화하면 좋을 거 같아요.

2021-06-01 13:48 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/board/controller/BoardControllerTest.java
> +        String requestBody = "{ \"memberId\": 1, \"title\": \"게시물 제목\", \"content\": \"게시물 내용\", \"createdDateTime\": \"2021-06-01T23:59:59.999999\"}";
매번 이렇게 문자열로 나타내는게 귀찮을 거 같은데요.
`ObjectMapper.writeValueAsString()` 메서드 사용해도 될 거 같아요.

com.fasterxml.jackson.databind.ObjectMapper#writeValueAsString

2021-06-01 13:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/domain/dto/BoardCreateRequest.java
> +    private String createdDateTime;
createDateTime을 String으로 선언하신 이유가 무엇인가요?
지금 로직을 보니 Service 레이어에서 `LocalDateTime`으로 파싱하고 있는데 애초에 프리젠테이션 레이어에서 `LocalDateTime`으로 설정되도록 하면 이 값을 사용하는 곳에서는 파싱에 대한 고려를 하지 않을 수 있을 것입니다.
이런 값 파싱은 스프링에게 맡기는 것이 오히려 더 정확하고 안전하다고 생각해요~ (Enum도 동일합니다.)

2021-06-01 13:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/domain/Board.java
> +    @Builder
DTO에선 Builder를 사용하지 않고 있던데 Builder 패턴을 사용하는 기준이 무엇인가요.
#38 PR에서 언급했던 내용인데요.
오히려 값이 덜 유의미하게 사용되는 DTO에서 Builder를 사용하고 엔티티에선 사용하지 않는 방향이 더 나아보여요.
반드시 그렇게 하라는 건 아니니 현재 Builder 패턴을 적용하는 클래스 기준이 무엇인지 궁금합니다~

2021-06-01 13:48 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/board/repository/BoardRepositoryTest.java
> +        assertThat(TEST_BOARD.getId()).isEqualTo(savedBoard.getId());
JPA는 엔티티가 영속화 될 경우 `@id` 어노테이션이 달려있는 식별자 필드에 값을 어사인해줍니다.
스프링 data jpa에서 제공해주는 `save`메서드를 보면 인자로 들어온 객체(`TEST_BOARD`)를 영속화 진행하고 그 객체를 다시 리턴합니다.
즉, 현재 테스트 코드에서 `savedBoard`에 할당된 객체와 `TEST_BOARD`는 같은 주소를 갖는 객체에요.
같은 주소의 같은 값을 `isEqualTo` 로 비교하는게 의미가 있나 싶은 생각이 드네요.
영속화가 정상적으로 이뤄졌다면 식별자가 값이 잘 채워졌는지만 확인하는게 테스트의 의미가 더 명확해보입니다.

org.springframework.data.jpa.repository.support.SimpleJpaRepository#save

2021-06-01 13:48 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/board/service/BoardServiceTest.java
> +    @ParameterizedTest
프로덕션 코드에서 try-catch 구문을 걷어내면 지워도 될 테스트로 보이네요.

2021-06-01 13:48 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/utils/ApiDocumentUtils.java
> +    static OperationRequestPreprocessor getDocumentRequest() {
중복 제거 👍

2021-06-02 15:30 UTC, sefide requested changes
고생하셨어요 👍🏼 중복되는 내용은 제외하고 코멘트 몇 개 남겼습니다 !

2021-06-02 15:30 UTC, sefide commented on src/main/java/com/project/kodesalon/model/board/exception/ForbiddenException.java
> +@ResponseStatus(HttpStatus.FORBIDDEN)
`403 FORBIDDEN`보다 `400 BAD_REQUEST`이 더 적합하지 않을까요 ? 
(`BoardService.java`에서) `ForbiddenException`은 게시물 제목, 내용에 적합하지 않은 데이터로 인해 발생하는 예외를 처리하기 위한 용도로 보이는데 `403 FORBIDDEN`은 권한과 관련된 상태 코드라서요. 
Exception명이 `ForbiddenException`이라서 헷갈리네요 ~

2021-06-03 20:41 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +@Transactional
넵넵 각 메소드마다 다른 설정을할 수 있으니 메소드에 하는 것이 더 좋은 것 같네요
해당 어노테이션 메소드로 옮겨주었습니다!

> 왜냐하면 메서드 별로 readOnly, propagation, transactionManager를 다르게 가져갈 수 있기 때문입니다

해당 부분에 대해서는 공부해서 정리해보도록 하겠습니다!

2021-06-03 20:44 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +        } catch (Exception e) {
넵넵 서비스에서 유효성 검증을 하는것보다는 올바른 값을 받아 엔티티로 변환하고 DB에 넘겨주는 행위를 하고, 컨트롤러에서는 올바른 값을 받아왔는 지에 대한 체크를 해주는 것이 더 좋다고 생각하여 해당 예외 일으키는 부분 서비스 로직에서 제거하였습니다!

2021-06-03 20:48 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/domain/dto/BoardCreateRequest.java
> +public class BoardCreateRequest {
패키지 구조를 1차 배포하기전 저번에 이야기해주신 방향으로 희상이와 같이 정리를 하기로 이야기해서, 나중에 한다는 생각으로 패키지 구조 관리에 소홀히 하게 된 것 같습니다. 해당 부분도 말씀해주신 사항대로 각 dto 패키지 만들어 수정하였습니다. 앞으로는 신경써서 구현하도록 하겠습니다!

2021-06-03 20:56 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/controller/BoardController.java
> +    public ResponseEntity save(@RequestBody final BoardCreateRequest boardCreateRequest) {
> 프론트에서 게시글을 생성하고 보여지는 페이지가 어떤 것인가요?
> 만약 프론트에서 게시글 작성 후 게시글 상세 페이지로 바로 이동하는 플로우라면 이 API의 반환 값이 필요해보입니다.

게시물이 생성된 후 전체 게시물이 보여지게 됩니다.
게시물 생성 후, 게시물 전체 조회 api를 호출하여 모든 게시물을 출력하는 구조로 약속하여 반환값이 없게 구현하였습니다.



> 그리고 개인적으로 제네릭 타입을 요구하는 클래스(`ResponseEntity`) 선언 시 제네릭을 명시해주는게 좋다고 생각해요. 그래야 코드를 명확하게 읽을 수 있습니다.

넵 제가 이 부분은 생각치 못하고 넘어간 부분이었던 것 같습니다. 다음부터는 이러한 부분에 대해서 한번 더 확인하고 올리도록 하겠습니다

2021-06-03 20:59 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/board/controller/BoardControllerTest.java
> +                .andDo(document("board/create/fail/invalid-title",
docs 이름과 메세지 출력되는 응답 값만 봐도 예외 메세지라는 것을 알 수 있지 않을까하여 넘어간 부분이었는데
더 명확하게 표현하기 위해서 메세지 필드도 문서화하는 것이 좋은 것 같네요! 해당 부분 문서화하였습니다!

2021-06-03 21:01 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/board/controller/BoardControllerTest.java
> +        String requestBody = "{ \"memberId\": 1, \"title\": \"게시물 제목\", \"content\": \"게시물 내용\", \"createdDateTime\": \"2021-06-01T23:59:59.999999\"}";
넵 해당 부분 싱글톤으로 만들어 전역적으로 사용하게 수정하였습니다!

2021-06-03 21:03 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/domain/dto/BoardCreateRequest.java
> +    private String createdDateTime;
해당 부분은 프론트에서 날짜가 어떤 형식으로 넘어올지 모르고 Json 파싱을 LocalDateTime 타입으로 해줄 수 있는지를 모른 상태였어서 String으로만 선언해놓은 부분이었습니다.
하지만, 나중에 관련 내용 찾아본결과 Json 매핑 시에 LocalDateTime, 객체 형식도 바로 매핑이 된다는 것을 알게 되었고 또한 `ISO8601` 규약에 맞춰 시간,날짜를 전달한다고 알게 되어 바로 LocalDateTime으로 수정하였습니다😂

2021-06-03 21:11 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/domain/Board.java
> +    @Builder
이 부분에 대해서 희상이와 이야기를 나눈 결과, 일단 현재는 DTO, Entity 모두 생성자를 사용하면서 구현을 하고, 서로 Builder에 대해서 더 고민해보고 이야기를 해본 후 적용해나가기로 하였습니다.
현재 Builder 이 부분은 코멘트 달아주시기 전에 이전에 구현을 이미 하고 커밋을 날린 부분이어서 다시 수정하였습니다!

2021-06-03 21:24 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/board/repository/BoardRepositoryTest.java
> +        assertThat(TEST_BOARD.getId()).isEqualTo(savedBoard.getId());
영속성에 대해서 생각하면서 처음에는 `TestEntityManager`를 사용해서 `persist, flush, clear` 후 `find`를 통해 객체를 찾아 식별자를 확인하는 방식으로도 구현해보고 많은 예시를 찾아보고 구현한 부분이었는데 피드백 받고 확인해보니 기본적인 함수 확인도 안하고 넘어 갔었네요. 제가 함수를 한번 확인했었어도 알 수 있었을 것 같은데 이러한 부분은 조금 더 신경쓰고 JPA 공부도 열심히하도록 하겠습니다!

테스트 코드를 수정하였는데, 이 부분도 제대로 수정을 한건지 잘 모르겠어서 피드백 주시면 감사하겠습니다!

2021-06-03 21:24 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/board/service/BoardServiceTest.java
> +    @ParameterizedTest
넵 이 부분 제거되었습니다!

2021-06-03 21:32 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/controller/BoardController.java
> +    public ResponseEntity save(@RequestBody final BoardCreateRequest boardCreateRequest) {
넵 말씀해주신 이유에 있어서 명시해주는 게 좋다고 생각이 드네요! 해당 부분 수정하였습니다! 
프로젝트를 하면서 하나씩 간과하게 되고, 신경쓰지 못한 부분들이 많이 생기는데 
이러한 부분에 대해서 피드백 주셔서 감사합니다!

2021-06-03 21:34 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/controller/BoardController.java
> +@RequestMapping(value = "/api/v1")
넵 다같이 이야기 해 본 결과, 가능하다면 API 버전 관리를 하면서 프로젝트를 진행해보고 싶다고 하여 `v1`을 붙여주었습니다!

2021-06-03 21:42 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/exception/ForbiddenException.java
> +@ResponseStatus(HttpStatus.FORBIDDEN)
회사, 개인마다 사용하는 상태코드가 조금씩 다른 부분이 있어 일단 저희가 찾아본 HTTP 상태 코드 글들을 기준으로 임의로 일단 정하고
나중에 리뷰어분들께 피드백을 받아 수정하자!하여 구현을 했던 부분이었는데, 저도 구현하면서 Forbidden이 적합하지 않다고 생각했고 정리를 한번 해야한다고 느꼈습니다. 이 부분은 저희가 정리해서 리뷰어분들께 여쭤보도록 하겠습니다!
현재 피드백 주신 부분은 `400` 으로 수정을 하였습니다!

2021-06-04 15:26 UTC, seonghun127 approved these changes
빠른 피드백 반영 👍
추가로 몇개 더 피드백 달아놨으니 확인해주세요~

이 PR에 대한 리뷰는 여기서 마무리하는 의미로 Approve 미리 해둘게요. 반영 후 바로 merge 하시고 다음 작업 이어가주세요.

2021-06-04 15:26 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/config/JacksonConfiguration.java
> +        objectMapper.registerModule(new JavaTimeModule());
```java
SerializationFeature.WRITE_DATES_AS_TIMESTAMPS
```
`ObjectMapper` 설정 시 위 설정을 false로 해주면 좋은데요.
지금 `@JsonFormat` 사용하는 곳에서 pattern 속성으로 해당 값의 직렬화 상태를 명시해주고 있는데 따로 명시하지 않아도 "yyyy-MM-dd'T'HH:mm:ss" 이 포맷으로 직렬화해줄거에요.
이는 java.time 하위에 있는 날짜 관련 클래스에 대해 모두 적용된다고 하네요.
이 부분은 정확히 알고 말씀드리긴 보단 구글링하면서 이해한 내용을 바탕으로 공유드립니다.
@sefide 님, 혹시 이부분에 대해 추가 피드백이 있으시면 코멘트 달아주시면 좋을 거 같아요~

참고자료
* https://kwonnam.pe.kr/wiki/springframework/springboot/json
* https://www.baeldung.com/jackson-serialize-dates#java-8

2021-06-04 15:26 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +        Board createdBoard = boardCreateRequestDto.toBoard("writer");
코드가 많이 간결해졌군뇨. 👍

2021-06-05 11:32 UTC, sefide commented on src/main/java/com/project/kodesalon/model/board/controller/BoardController.java
> +@RequestMapping(value = "/api/v1")
URI를 이용한 버전 관리를 선택했군요 ㅎㅎ 참고해서 보겠습니다 !

2021-06-05 13:27 UTC, sefide commented on src/test/java/com/project/kodesalon/config/JacksonConfiguration.java
> +        objectMapper.registerModule(new JavaTimeModule());
아 네네 저도 정확하게 이해한건지 모르겠지만

```
SerializationFeature.WRITE_DATES_AS_TIMESTAMPS
```
Spring Boot 2.x은 위 설정이 디폴트라 @seonghun127 님 말씀처럼 pattern을 따로 명시해주지 않아도 되는걸로 알고 있어요.
테스트에서 사용하는 ObjectMapper에 대한 config 또한 위 설정으로 통일시켜주는게 좋을 것 같아요 ! 

참고 : https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.spring-mvc.customize-jackson-objectmapper

2021-06-05 13:49 UTC, sefide approved these changes
몇 가지 코멘트 남겼는데 빠른 진행을 위해 저도 어프드려요 ! 
점점 희상님과 통일성도 높아지고 코드가 명확해지고 있는것 같아요  👍🏼

2021-06-05 13:49 UTC, sefide commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +        Board createdBoard = boardCreateRequestDto.toBoard("writer");
저도 따봉 드립니다. 👍🏼 👍🏼

2021-06-05 13:49 UTC, sefide commented on src/test/java/com/project/kodesalon/config/JacksonConfiguration.java
> +    public ObjectMapper objectMapper() {
테스트 내에서 공통으로 사용할 수 있도록 설정하는 방식 좋습니다 👍🏼

2021-06-05 13:49 UTC, sefide commented on src/test/java/com/project/kodesalon/model/board/controller/BoardControllerTest.java
> +        mockMvc.perform(post("/api/v1/boards/")
URL 마지막에 `/` 제거해야겠네요 !

2021-06-05 13:49 UTC, sefide commented on src/test/java/com/project/kodesalon/model/board/controller/BoardControllerTest.java
> +        mockMvc.perform(post("/api/v1/boards/")
아래 테스트들도 같이 제거해주면 좋을것 같아요

2021-06-05 13:49 UTC, sefide commented on src/test/java/com/project/kodesalon/model/board/service/dto/BoardCreateRequestDtoTest.java
> +    public void toBoard() {
매개변수로 받고 있는 writer 이외의 다른 필드 또한 `BoardCreateRequestDto`가 `Board` 객체로 생성되면서 값의 변화가 있는지 없는지 확인해주는게 좋을것 같아요.

2021-06-07 12:46 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/controller/BoardController.java
> +    public ResponseEntity<HttpStatus> save(@RequestBody final BoardCreateRequest boardCreateRequest) {
null이 어사인 된다고 생각하지 못했었네요..
해당 부분 수정하였으며
제네릭에 대해서 더 공부해보도록 하겠습니다!

2021-06-07 12:46 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/board/repository/BoardRepositoryTest.java
> +        Optional<Board> foundBoard = boardRepository.findById(TEST_BOARD.getId());
해당 부분도 말씀하신 내용과 같이 수정하였습니다!

2021-06-07 12:47 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/config/JacksonConfiguration.java
> +        objectMapper.registerModule(new JavaTimeModule());
해당 부분은 스터디시간에 이야기한 부분대로 적용하였습니다!

2021-06-07 12:47 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/config/JacksonConfiguration.java
> +    public ObjectMapper objectMapper() {
넵 말씀하신 이유처럼 여러 곳에서 사용될 것 같아 싱글톤처럼 쓰기 위해서 분리를 했습니다!

2021-06-07 12:47 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/board/controller/BoardControllerTest.java
> +        mockMvc.perform(post("/api/v1/boards/")
넵넵 전부 제거하였습니다!

2021-06-07 12:48 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/board/service/dto/BoardCreateRequestDtoTest.java
> +    public void toBoard() {
넵넵 맞는 말씀인 것 같습니다!
해당 부분도 수정하였습니다!

2021-06-07 12:49 UTC, merged

2021-06-07 12:54 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/config/JacksonConfiguration.java
> +        objectMapper.registerModule(new JavaTimeModule());
혹시 스터디 시간에 어떤 이야기를 나눴는지도 같이 코멘트에 명시해주면 좋겠네요. @sefide 님은 그 이야기를 못들으셨으니...
(제가 기억나면 이야기할텐데 기억이 안나네요...😂)

2021-06-07 13:15 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/config/JacksonConfiguration.java
> +        objectMapper.registerModule(new JavaTimeModule());
아 넵넵
결론부터 간단하게 말씀드리자면, 수정하지 않고 처음 구현 그대로 가져갔습니다!

> Spring Boot 2.x은 위 설정이 디폴트라 @seonghun127 님 말씀처럼 pattern을 따로 명시해주지 않아도 되는걸로 알고 있어요.

@sefide님의 피드백과 @seonghun127님이 올려주신 https://kwonnam.pe.kr/wiki/springframework/springboot/json 에서의 글 내용처럼 Spring Boot 2.x는
`SerializationFeature.WRITE_DATES_AS_TIMESTAMPS` 설정이 `false`로 Default 되어있기 때문에 추가 설정을 하지 않는 방식으로 하기로 하였습니다.

그리고 Jackson에서 `SimpleModule`을 상속받은 `JavaTimeModule` 내에 `DateTime`에 대한 default 직렬화, 역직렬화가 `yyyy-MM-dd'T'HH:mm:ss` 형식인 `DateTimeFormatter.ISO_LOCAL_DATE_TIME`이기 때문에 `@ JsonFormat`에서 따로 pattern을 따로 명시해주지 않아도 되지만, 
다른 사람들이 저희 코드를 봤을 경우 어떠한 형식으로 시간이 저장되는 지 알 수 있게 표현해주는 것이 좋다고 생각하여 명시하였던 부분을 스터디에서 이야기하였고, 이 부분에 대해서 그러한 이유라면 그대로 가져가도 좋을 것 같다는 의견을 받아, pattern 부분도 수정하지 않았습니다!

2021-06-07 14:03 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/config/JacksonConfiguration.java
> +        objectMapper.registerModule(new JavaTimeModule());
넵넵 정리하도록 하겠습니다~!

2021-06-08 05:10 UTC, sefide commented on src/test/java/com/project/kodesalon/config/JacksonConfiguration.java
> +        objectMapper.registerModule(new JavaTimeModule());
명시적 표시를 위해 남기는 점 인지했습니당 ㅎㅎ 공유 감사합니다