Feature/#18/회원가입 기능 구현
kodesalon/project pull request #40
Opened 2021-06-01 13:44 UTC by sdrs6921

### 개요
- 이슈 번호 : #18 회원가입 기능 구현
- 내용 : 회원가입 테스트 및 회원 가입 기능 구현

### 작업 사항
- 회원 가입 Service Test 작성
- 회원 가입 Service 구현
- 회원 가입 Controller 테스트 코드 작성
- 회원 가입 Controller 구현

### 기타
-

2021-06-02 16:16 UTC, seonghun127 requested changes
빠른 구현 좋습니다~ 나날이 코드가 좋아지는게 보이네요.
몇가지 리뷰 남겼으니 확인해주세요 :)

2021-06-02 16:16 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
>          given(memberService.login(any(LoginRequestDto.class)))
Controller 테스트에선 BDDMockito의 `given()`를 사용해서 테스트하고 계신데,
Service 테스트에선 Mockito `when()`을 사용하고 있어서 이를 통일시켜주면 좋을 거 같네요.

물론 BDDMockito가 Mockito를 감싼 거라 테스트 수행엔 전혀 상관이 없는데 클래스별로 사용하는 메서드가 달라지면 통일성이 떨이져서 코드 복잡도가 올라갈 수 있습니다.

2021-06-02 16:16 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
>                  .andExpect(content().string("{\"memberId\":1,\"alias\":\"alias\"}"))
API 가 내려주는 값을 json 형태의 문자열 형태로 확인하고 계신대요, 문자열 관리가 힘들어서 테스트 작성하는데 많은 어려움이 있을 것으로 보여집니다.

`jsonPath()` 를 한번 찾아보시면 좋을 거 같아요. json 형태의 데이터를 key로 접근해서 해당 값을 비교할 수 있도록 해주는 메서드입니다.

org.springframework.test.web.servlet.result.MockMvcResultMatchers#jsonPath(java.lang.String, org.hamcrest.Matcher<? super T>)

2021-06-02 16:16 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
>                                  fieldWithPath("alias").description("로그인 할 alias"),
문서화 시 필드의 타입도 같이 체크해주면 좋을 거 같아요~ `type()`

org.springframework.restdocs.payload.FieldDescriptor#type

2021-06-02 16:16 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +                    throw new IllegalStateException("이미 존재하는 아이디입니다");
현재 이 예외가 던져지면 ExceptionHandler에서 받아서 `e.message()` 메세지만 로그로 남기고 예외 처리를 하고 있는데요.
나중에 로그를 검색해서 볼 때 어떤 요청 값에 의해서 실패했는지 따로 확인할 수 없을 거 같네요.
여기서도 log를 남겨보는건 어떨까요?
log 남기는거까지 필요할까 싶으면 에러 메세지에 요청 값도 추가해줘도 될 거 같네요.

2021-06-02 16:16 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/member/service/MemberServiceTest.java
>      @DisplayName("존재하는 Alias가 Alias와 Password가 일치하면 200 status 코드, Id, Alias를 리턴합니다.")
DisplayName이 변경되어야할 거 같네요.
리뷰 반영하면서 status 코드는 해당 DTO에서 관리하지 않고 있네요.

2021-06-03 07:48 UTC, sefide requested changes
세상에.. 앞서 꼼꼼한 리뷰를 받으셔서 제가 남길게 별로 없네요. 
고생하셨어요 👍🏼

2021-06-04 14:19 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/common/GlobalExceptionHandler.java
> +    @ExceptionHandler(IllegalStateException.class)
서버의 error가 아니라 사용자의 실수라고 생각하여 info로 설정했는데 로그 레벨을 다시 한 번 고려해보고 조정하겠습니다.

2021-06-04 14:21 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +        Member savedMember = memberRepository.save(new Member(createMemberRequestDto.getAlias().value(), createMemberRequestDto.getPassword().value(),
Member를 따른 변수로 추출해보겠습니다!

2021-06-04 14:22 UTC, sdrs6921 commented on src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
>          given(memberService.login(any(LoginRequestDto.class)))
일단은 BDDMockito와 BDD를 사용해서 먼저 구현한 후에 어떠한 방식으로 테스트 코드를 짤 지 회의를 다시 한 번 해보고 통일하겠습니다.

2021-06-04 14:23 UTC, sdrs6921 commented on src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
>                  .andExpect(content().string("{\"memberId\":1,\"alias\":\"alias\"}"))
jsonPath 메서드를 공부하고 추가로 반영하겠습니다.

2021-06-04 14:25 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +                    throw new IllegalStateException("이미 존재하는 아이디입니다");
어떠한 상황에서 발생한 오류인지 로그로 남기겠습니다!

2021-06-04 14:25 UTC, sdrs6921 commented on src/test/java/com/project/kodesalon/model/member/service/MemberServiceTest.java
>      @DisplayName("존재하는 Alias가 Alias와 Password가 일치하면 200 status 코드, Id, Alias를 리턴합니다.")
이 부분도 빠르게 수정하겠습니다

2021-06-04 14:27 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/common/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(new ErrorResponse(e.getMessage()), HttpStatus.FORBIDDEN);
지난 번에 회의를 통해서 가장 적합하다고 생각한 상태 코드가 데이터의 유효성에 관한 상태코드라고 판단해서 `422 Unprocessable Entity` 상태 코드를 사용하기로 했고 이 부분도 반영하겠습니다.

2021-06-04 14:32 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +        Member savedMember = memberRepository.save(new Member(createMemberRequestDto.getAlias().value(), createMemberRequestDto.getPassword().value(),
제가 생각하기엔 `DTO`에서 `Entity`를 변환하는 부분을 담당하는 것이 `Service` 에서 할 일이라고 생각했었는데 생각을 했었는데 `DTO` 내부에서 Entity 객체를 생성해서 내려주는 방식을 적용해 보는 것도 다른 서버 개발자분과 회의한 후에 통일하겠습니다!

2021-06-09 14:56 UTC, seonghun127 requested changes
여기서 작업에서도 #36  에 남긴 리뷰와 같이 controller와 service간 dto 의존 이슈가 있군뇨.
이부분은 제가 잘못이야기해서 여기저기 잘못 이야기한 내용을 바탕으로 작업이 되어 있네요. (리뷰 똑바로 할게요 😭)

리뷰는 merge 커밋 이후의 "#18" prefix 붙어있는 커밋만 보면서 남겼습니다.
혹시 더 봐야하는 내용이 있다면 알려주세요~

2021-06-09 14:56 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +                    log.error("회원 가입 단계에서 {}는 이미 존재하는 Alias입니다.", createMemberRequestDto.getAlias());
로그에 남기고 있는 `createMemberRequestDto.getAlias()` 값이 제대로 출력되지 않고 있네요. 해당 메서드는 `Alias` 객체를 리턴하고 있어서 주소값이 찍히고 있습니다.

그리고 사용자가 이미 존재하는 Alias를 입력했다는 사실이 서버 error인지 다시 생각해보면 좋을 거 같아요.
error 로그는 시스템적 문제나, 비지니스 적으로 장애로 인식될만한 요소에 남기는데요.
Alias가 유효하지 않은 사실은 위 두 경우 모두 해당하지 않는다고 생각해요~

2021-06-11 14:55 UTC, sefide approved these changes
앞선 리뷰에 빠르게 반영해주셔서 전반적으로 명확하고 통일성 높은 코드가 되었네요.
#41 에서처럼 공통으로 사용하는 BDDSoftAssertions 상수화도 추후 반영해주면 좋을 것 같아요.

더불어서 다른 얘기지만 보다 보니까 Docs 꼼꼼하게 잘 작성해주시네요. 
저는 회사에서 자체 개발한 모듈을 사용하고 있기 때문에 Spring Rest Docs가 낯설었는데 덕분에 새로 익히고 배우고 가네요. 나중에 기회가 된다면 API 문서를 자동화하는 모듈을 직접 개발해보시는 것도 재밌을것 같아요 !

2021-06-13 08:19 UTC, sdrs6921 commented
> #41 에서처럼 공통으로 사용하는 BDDSoftAssertions 상수화도 추후 반영해주면 좋을 것 같아요.

넵 이 부분에 대한 피드백도 한꺼번에 변경해서 반영하였습니다! 이를 상수화하는 부분까지는 미처 생각하지 못했던 부분이었네요!

>  나중에 기회가 된다면 API 문서를 자동화하는 모듈을 직접 개발해보시는 것도 재밌을것 같아요 !

최대한 노력해서 이 부분도 한 번 진행해보겠습니다!

2021-06-16 13:44 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
>                                  fieldWithPath("alias").description("로그인 할 alias"),
해당 부분도 모두 적용하였습니다!

2021-06-18 00:20 UTC, seonghun127 approved these changes
몇가지 피드백 남겼습니다. 미리 approve할테니 반영 후 머지해주시면 돼요~

추가로 Advanced 내용을 남겨요.

**`BaseEntity` 관리**
- 엔티티마다 공통으로 존재하는 값이 존재할텐데요. 이를 부모객체로 빼서 공통으로 관리하는 방식입니다. JPA에서 엔티티간 상속관계를 지원해주기 때문에 이를 사용해보는 것도 좋을 거 같아요. 공통으로 존재하는 값으로는 생성날짜, 생성자(해당 데이터를 생성한 주체), 수정날짜, 수정자 등이 있을 거 같네요.

**패키지 구조**
- 현재 도메인별로 (member, board) 패키지를 구분하고 그 안에서 presentation/service/domain 식으로 패키지를 나누고 있는데요, 이러면 결국  상위 패키지(member, board)간 순환 참조가 발생할 가능성이 높아집니다. 더불어 현재 방식이 구분짓기 편하다는 장점이 있는데 구조가 복잡해질 수록 그 장점이 점점 떨어질 수 있습니다. 예를들어 Member와 Board를 동시에 조회해서 데이터를 가공해야하는 기능이 추가되어야한다고 했을 때 해당 로직(Service가 되겠죠)은 어디에 위치해야하는지 결정하기 애매해집니다. (이런 상황이 반복된다면 나중에 이 클래스가 왜 member 패키지 하위에 있어야하는지, board 패키지 하위에 있어야하는지 이해가 가지 않는 상황이 올 수 있어요.) 현 상위 패키지를 처음부터 layer architecture로나눠서 만드는게 어떨지 의견드려요~

2021-06-18 00:20 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +    public LoginResponse join(CreateMemberRequestDto createMemberRequestDto) {
해당 메서드에서 2번의 DB connection을 맺어서 통신을 하는데요 (중간에 `IllegalStateException`이 발생하지 않는 한).
하나의 connection으로 통신하는게 더 낫다고 생각이 드네요.
connection을 얻는 것도 어떻게보면 비용이니 (물론, connection pool을 사용하므로 그 비용은 비싸진 않습니다.) 굳이 connection을 매번 끊고 다시 연결하면서 데이터 조회 -> 데이터 저장을 할 필욘 없어 보여요.
이 부분에서 제가 잘못 알고 있는 부분이 있다면 정정해주세요. cc. @sefide

2021-06-18 00:20 UTC, seonghun127 commented on src/main/resources/application.yml
> +          in_clause_parameter_padding: true
JPA 설정 👍

2021-06-18 00:20 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/common/GlobalExceptionHandler.java
> +        String errorMessage = Objects.requireNonNull(e.getFieldError()).getDefaultMessage();
`e.getFieldError()`을 `Objects.requireNonNull()`로 감싸주셨는데요, 여기서 NPE가 발생할 경우 이를 핸들링해주는 곳은 어디인가요?
`Objects.requireNonNull()`안에서 발생할 수 있는 NPE를 관리하는 핸들러를 추가하거나 이 메서드 자체를 지우는 방향으로 개선해보면 좋을 것 같습니다~

2021-06-18 00:34 UTC, seonghun127 commented on build.gradle
> +    implementation group: 'org.hibernate.validator', name: 'hibernate-validator', version: '6.1.5.Final'
아래 블로그도 참고해보세요~
https://medium.com/@gaemi/java-%EC%99%80-spring-%EC%9D%98-validation-b5191a113f5c

2021-06-18 02:21 UTC, seongbeenkim commented on build.gradle
> +    implementation group: 'org.hibernate.validator', name: 'hibernate-validator', version: '6.1.5.Final'
해당 부분 모르는 부분이었습니다!
spring validation으로 의존성 교체해주었습니다 감사합니다!

2021-06-18 02:26 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/member/service/MemberServiceTest.java
> +                .hasMessageContaining("이미 존재하는 아이디입니다");
`HttpClientErrorException`이 발생할 경우, 
기본 메시지가 `"400 이미 존재하는 아이디입니다"` 와 같이 
HTTP 상태 + 예외메세지 가 함께 출력되어 `hasMessageContaining()`으로 수정했었습니다!

현재 리팩토링 도중 `HttpClientErrorException`을 제거하고 `IllegalArgumentException`와 같은 에러들로 교체해주어 다시 `hasMessage()`로 수정해주었습니다!

2021-06-18 03:33 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +    public LoginResponse login(LoginRequest loginRequest) throws HttpClientErrorException {
이 부분 다른 브랜치에서 지우긴 했는데, 해당 브랜치에서도 다시 제거해주었습니다!

2021-06-18 04:45 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +    public LoginResponse join(CreateMemberRequestDto createMemberRequestDto) {
해당 부분 아래의 글 참고하여 `hibernate.connection.provider_disables_autocommit=true` 로 설정해주었는데 이와 같은 방식으로 해결하는 것이 맞을까요? 
https://kwonnam.pe.kr/wiki/java/hibernate/performance
https://pkgonan.github.io/2019/01/hibrnate-autocommit-tuning

2021-06-18 05:57 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/common/GlobalExceptionHandler.java
> +        String errorMessage = Objects.requireNonNull(e.getFieldError()).getDefaultMessage();
`Objects.requireNonNull()` 를 제거해주었습니다!

2021-06-18 06:16 UTC, seongbeenkim commented
> **패키지 구조**
> 
> * 현재 도메인별로 (member, board) 패키지를 구분하고 그 안에서 presentation/service/domain 식으로 패키지를 나누고 있는데요, 이러면 결국  상위 패키지(member, board)간 순환 참조가 발생할 가능성이 높아집니다. 더불어 현재 방식이 구분짓기 편하다는 장점이 있는데 구조가 복잡해질 수록 그 장점이 점점 떨어질 수 있습니다. 예를들어 Member와 Board를 동시에 조회해서 데이터를 가공해야하는 기능이 추가되어야한다고 했을 때 해당 로직(Service가 되겠죠)은 어디에 위치해야하는지 결정하기 애매해집니다. (이런 상황이 반복된다면 나중에 이 클래스가 왜 member 패키지 하위에 있어야하는지, board 패키지 하위에 있어야하는지 이해가 가지 않는 상황이 올 수 있어요.) 현 상위 패키지를 처음부터 layer architecture로나눠서 만드는게 어떨지 의견드려요~

넵넵 패키지 구조 수정 부분은 저희가 회원 PR 모두 머지 후 
`게시물 - 회원` 연동하는 하는 작업에서 패키지 수정할 예정이었습니다! 
이번주 스터디 시간까지 완료하도록 하겠습니다!

2021-06-18 06:16 UTC, merged

2021-06-19 07:31 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +    public LoginResponse join(CreateMemberRequestDto createMemberRequestDto) {
음 제가 리뷰를 너무 돌려 이야기했군뇨. 위 메서드를 하나의 트랜잭션으로 묶으면 어떨까라는 의견을 드린 것이었습니다.

참고로 hibernate의 auto commit 기능을 끄는건 성능향상에 좋아서 좋은 방향으로 설정해주신거 같네요.
auto commit 이 활성화돼있으면 트랜잭션 관리가 어려워져서 set auto commit = false 라는 쿼리를 먼저 보내서 트랜잭션을 시작하고 트랜잭션이 끝나고나면 set auto commit = true 를 다시 날릴거에요.
즉, DB에 쓸데없는 쿼리가 날라가는 것인데요. 반드시 설정해줘야하는 부분입니다. 저도 이 [블로그](https://pkgonan.github.io/2019/01/hibrnate-autocommit-tuning)보고 많이 도움됐어서요. 공부해보면 좋을 내용으로 추천드려요~