Feature/#41/회원 조회 기능 구현
kodesalon/project pull request #42
Opened 2021-06-02 06:55 UTC by sdrs6921

### 개요
- 이슈 번호 : #41 
- 내용 : 회원 조회 테스트 및 회원 조회 구현

### 작업 사항
- 회원 조회 Service 테스트 코드 작성
- 회원 조회 Service 구현
- 회원 조회 Controller 테스트 코드 작성
- 회원 조회 Controller 구현
- 회원 조회 Rest Docs에 추가

### 기타
-

2021-06-03 14:14 UTC, seonghun127 requested changes
비지니스 로직이 복잡한 작업이 아니라 간단한 리뷰들만 남겼어요~

2021-06-03 14:14 UTC, seonghun127 commented on src/docs/asciidoc/api-docs.adoc
> +include::{snippets}/select/success/httpie-request.adoc[]
httpie-request.adoc[] 보다는 http-request.adoc[] 를 사용하면 더 좋을 거 같아요.
다른 API 문서에서도 http-request.adoc[]를 사용하고 있네요.

2021-06-03 14:14 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +    @Transactional(readOnly = true)
readOnly 속성의 `@Transactional` 추가 👍

2021-06-05 13:24 UTC, sefide approved these changes
이제 익숙도가 많이 높아지신것 같아요 ! 👍🏼 
저도 간단한 로직이라서 특별한 코멘트 없이 어프합니다. 

+) 앞선 PR들이 병합되지 않아 중복되는 코드가 많네요. 
리뷰 속도가 느려서 그런것이겠지만은(ㅠ) PR 생성 시, 리뷰받고자 하는 코드의 단위를 줄이는 것도 좋은 리뷰 문화에 큰 도움이 됩니다.

2021-06-10 12:47 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/member/service/MemberServiceTest.java
>          BDDSoftAssertions softly = new BDDSoftAssertions();
이 객체는 상수로 빼도 되지 않을까요?

2021-06-10 12:49 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +                    log.error("회원 조회 단계에서 존재하지 않는 회원 식별자 memberId : {}", memberId);
error 로는 서버 애러가 발생 시 남기는 로그 레벨인데, 회원 조회 실패가 서버 애러인지는 한번 고민해볼 필요가 있을 거 같아요~
이전 PR에서도 남긴 리뷰인데 한번 더 남깁니다.

2021-06-11 14:24 UTC, sefide reviewed
Commits와 Files changed를 번갈아보며 리뷰를 남기다보니 prefix가 #18인 커밋에 코멘트를 남긴 것 같네요.. 참고해주시고 해당 내용은 #18 에 다시 남길테니 확인해주시면 좋을 것 같습니다. 
당장의 변경이 필요하다기보다는 한번쯤 생각해보면 좋겠다 싶은 코멘트 하나 남겼습니다.

2021-06-13 08:15 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +                            log.error("{}인 Alias를 가진 사용자가 존재하지 않음", loginRequestDto.getAlias());
아 넵! 참조 값으로 로그를 찍는 부분을 제대로 확인하지 못했습니다. 이 부분은 다른 branch에서 피드백을 받아서 일괄적으로 변경한 후에 반영하였습니다.

2021-06-13 08:16 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/common/GlobalExceptionHandler.java
> +    @ExceptionHandler(IllegalStateException.class)
음.. 여러개의 exception을 하나로 처리하는 방식은 모르는 부분이었습니다. Exception 처리 방식이 동일하기 때문에 이 부분도 고려해서 다음 리뷰에 반영하겠습니다!!

2021-06-16 13:45 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
>                  .andExpect(content().string("{\"alias\":\"alias\",\"name\":\"이름\",\"email\":\"email@email.com\",\"phone\":\"010-1111-2222\"}"))
`jsonPath()` 모두 반영하였고 개발 시에도 모두 적용하고 있습니다!

2021-06-16 13:46 UTC, seongbeenkim commented on src/docs/asciidoc/api-docs.adoc
> +include::{snippets}/select/success/httpie-request.adoc[]
`http-request.adoc[]`로 수정하였습니다 감사합니다 :)

2021-06-16 13:47 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/member/service/MemberServiceTest.java
>          BDDSoftAssertions softly = new BDDSoftAssertions();
넵! 중복적인 부분이라 `BDDSoftAssertions` 상수로 빼놓았습니다!

2021-06-16 13:49 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/common/GlobalExceptionHandler.java
> +    @ExceptionHandler(IllegalStateException.class)
동일하게 처리하는 부분에 있어 중복적인 코드가 발생된다고 생각하여 아래와 같이
`@ExceptionHandler({IllegalArgumentException.class, NoSuchElementException.class, IllegalStateException.class})`
수정하였습니다 :)

2021-06-17 08:12 UTC, sefide approved these changes
다소 가벼울 수 있는 부분이지만 displayName이랑 테스트 코드 통일하니 보기 좋네요. dto 네이밍 변경도요 👍🏼 
[ExcpetionHandler에 대한 수정처리](https://github.com/kodesalon/project/pull/42#discussion_r652709139)는 #47 에서 반영한거 확인했습니다 !
고생하셨어요 ~

2021-06-19 08:06 UTC, seonghun127 approved these changes
코드의 통일성들이 올라가네요. 좋습니다 💯

2021-06-19 10:24 UTC, merged