Feature/#19/회원 비밀번호 변경 기능 구현
kodesalon/project pull request #46
Opened 2021-06-09 08:42 UTC by seongbeenkim

### 개요
- 이슈 번호 : #19 
- 내용 : 회원 비밀번호 변경 기능 구현

### 작업 사항
- 회원 비밀번호 변경 기능 관련 도메인, 컨트롤러, 서비스, 레파지토리 구현

### 기타

2021-06-10 13:34 UTC, seonghun127 requested changes
전반적으로 코드가 깔끔한 느낌이네요. 구현하느라 고생하셨습니다 👏
몇가지 리뷰남겼는데 확인해주세요~

2021-06-10 13:34 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/member/domain/MemberTest.java
> +        //given
주석 표기 방식은 아래와 같습니다.
```
// given

// when

// then
```

2021-06-10 13:34 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +        member.changePassword(changePasswordRequestDto.getPassword());
지금 DTO에서 값을 꺼내는 플로우를 보면 String(Presentation Layer) -> VO(Service Layer) -> String(getter) -> VO(changePassword()) 인데요.

두가지를 다시 봐야할 거 같습니다.
우선 다른 PR에서 이야기했었는데 controller 전용 DTO를 따로 빼는게 과연 의미가 있을까 입니다.
제가 controller, service 레이어에서 사용하는 DTO를 각각 따로 만들면 좋다고 이야기했었는데요, 이는 적절한 내용이 아닌 거 같습니다.
필드가 같다면 굳이 나누기보단 service 레이어에 두고 controller 레이어에서 사용하도록 하는게 더 나아보여요. 그럼 위 플로우가 한 뎁스 줄어들 거 같네요.
두번째는 DTO에서 VO 객체를 들고 있는 것입니다. 결국 엔티티에서 VO 값을 초기화할 때 VO 내부의 필드의 타입으로 값을 받고 VO를 초기화하는데, 엔티티에 도달하기전 DTO에서 VO를 들고 있으니 불필요한 값 변환 작업이 발생하는 거 같습니다.
유효성 검증 측면에서 DTO에 VO를 들고 있는게 좋다라고 생각이 들었었는데, 프리젠테이션 레이어에서 기본 값 타입으로 사용된다면 유효성 검증은 spring-validation을 이용하고 VO로 값에 대한 유효성 검증을 엔티티에 적용될 때 한번 더 해주는 방식이 나아보여요.

두서없이 이야기를 늘어놨는데요 이부분에 추가적인 이야기를 나누고 싶으면 슬랙이든 github이든 많이 많이 코멘트 주세요~

2021-06-10 13:34 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/controller/MemberController.java
> +    @PutMapping
현재, `ChangePasswordRequest` 객체를 통해서 (request body) 식별자 값(memberId)을 받고 있는데요,
restful 에서 식별자는 path variable 받아야하는 걸로 알고 있어요.
restful 에서 path variable는 리소스의 위치를 나타내는데 지금 API는 특정 리소스의 정보를 변경하는 역할을 수행하니 특정 리소스의 위치(식별자)는 path variable로 나타내면 좋을 거 같습니다.

2021-06-10 13:34 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +        return new ChangePasswordResponseDto("비밀번호 변경 성공하였습니다.");
응답 값(`ChangePasswordResponseDto`)에 사용하는 message 값을 직접 초기화 해주고 있는데요.
해당 메세지가 프론트에서 노출되는 정보라면 서버가 뷰단에서 사용하는 메세지를 관리하게 되는 것인데요.
서버 어플리케이션은 기본적으로 뷰단에서 노출되어야하는 정보를 최대한 신경쓰지 말아야합니다.

만약, 해당 메세지 ("비밀번호 변경 성공하였습니다.")가 화면에 노출되어야한다면 결국 화면에 노출되는 메세지를 서버에서 관리하게 되는 것인데 만약 요구사항이 변경되어 문구가 수정되어야했을 때 변경되어야하는 곳은 프론트가 아닌 백단이 되게 됩니다.
분명 문구와 관련된 이슈는 프론트에서 관리하는 것이 맞는데 그와 관련된 요구사항에 의해 서버의 코드가 변경된다는 것은 옳지 않은 상황입니다. (다시 배포를 해야하게 되죠.)
물론 해당 문구를 프론트에서 바로 사용하는 것이 아닌 프론트에서 따로 관리하는 문구로 노출한다면 해당 요구사항이 왔을 때 서버엔 영향이 없겠지만 그렇다면 서버에서 이 메세지를 내려줄 필요도 없게 되겠죠.

2021-06-10 13:34 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/member/repository/MemberRepositoryTest.java
>          testEntityManager.flush();
`testEntitiyManager.flush()` 로 dirty checking이 실행되도록 짠 코드가 좋은 거 같네요. 테스트하기 애매한 부분일 수 있을 텐데 괜찮은 방법으로 해결하신 거 같네요. 👍

2021-06-11 19:48 UTC, sefide requested changes
커밋로그 보니 비밀번호 변경 로직 관련해서 고민하신 흔적들이 보여서 저도 같이 배우고 갑니다 !
아, Docs 확인해보니까 비밀번호 변경 API에 대해 controllerTest는 추가했는데 API 문서에 추가는 안하신 것 같아서 확인 부탁드려요 ~

2021-06-11 19:48 UTC, sefide commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
> +        if (hasSamePassword(new Password(newPassword))) {
`new Password(newPassword)`를 따로 빼서 `Password`객체 생성과 `hasSamePassword` 메서드와 라인분리를 하는건 어떨까요? 
- `hasSamePassword`를 통과한 Password와 이후 `this.password`에서 선언되는 Password가 동일하다 것을 메소드 내에서 보장해주는 것과 
- `Password` 초기화 시, 수행하는 유효성 검증으로 인해 발생하는 `IllegalArgumentException`과 `hasSamePassword `메소드에서 발생하는 `IllegalArgumentException`을 디버깅 단계에서 좀 더 명확하게 구분시킬 수 있을것 같아요.

2021-06-11 19:48 UTC, sefide commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
> +    public boolean hasSamePassword(Password password) {
final 키워드로 객체의 변경을 최소화해줘도 좋을것 같아요 !

2021-06-16 13:53 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
> +        if (isIncorrectPassword(new Password(newPassword))) {
`hasSamePassword`라는 이름으로 수정하였습니다!
1. 로그인 시, 입력한 비밀번호와 현재 자신의 비밀번호와 똑같은지 비교
2. 비밀번호 변경 시, 바꾸려는 비밀번호와 현재 자신의 비밀번호와 똑같은지 비교
두 경우 모두 어색하지 않고 명확하게 표현할 수 이름이라고 생각이 되어 위와 같이 수정하였습니다.

2021-06-16 13:54 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/member/domain/MemberTest.java
> +        //given
`BDDMockito, BDDAssertio` 로만 작성하는 방식으로 합의보았으며, 모두 통일시키도록 수정했습니다!

2021-06-16 13:57 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +        member.changePassword(changePasswordRequestDto.getPassword());
해당 부분 스터디 시간에 이야기 나눴던것처럼
서비스 DTO 하나만 사용하며, 
해당 DTO에서는 VO객체를 들고 있지 않고 spring-validation을 통해 유효성 1차 검증, 엔티티로 변환 시 VO로 2차 검증하는 식으로 수정하였습니다.

2021-06-16 13:58 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/controller/MemberController.java
> +    @PutMapping
restful에 대한 이해도가 부족했던 것 같습니다..
`path variable`로 수정하였습니다!

2021-06-16 13:59 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +        return new ChangePasswordResponseDto("비밀번호 변경 성공하였습니다.");
해당 부분도 스터디 시간에 이야기한 것처럼 에러 코드를 보내는 방식으로 수정하였습니다!

2021-06-16 14:02 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
> +        if (hasSamePassword(new Password(newPassword))) {
넵넵!! 말씀하신 것처럼 더 명확하게 구분하기 위해서 라인 분리를 해주는 게 좋은 것 같습니다!
해당 부분도 수정하였습니다 :)

2021-06-16 14:03 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
> +    public boolean hasSamePassword(Password password) {
넵 말씀하신대로 `final`로 수정해주었습니다 :)

2021-06-17 08:21 UTC, sefide commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +        return new ChangePasswordResponseDto("비밀번호 변경 성공하였습니다.");
**feature/#19/회원-비밀번호-변경-기능-구현** 브랜치에서는 에러 코드로 보내는 방식으로 수정한 내용이 안보이네요 😢
혹시 어디서 수정했는지 확인할 수 있을까요 ?

2021-06-17 08:28 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +        return new ChangePasswordResponseDto("비밀번호 변경 성공하였습니다.");
앗.. 죄송합니다ㅠㅠ 이 부분은 `feature/#19/회원-비밀번호-변경-기능-구현` 브랜치에서 작업하지 않고 
저희가 새로 만든 `feature/#51/게시물-회원-연동` 브랜치에서 작업을 하였었네요... 혼동드려서 죄송합니다..
오늘 해당 부분 작업한 브랜치 PR이 올라갈텐데 그곳에서 확인하셔야 할 것 같습니다ㅠㅠ 번거롭게 해드려서 죄송합니다ㅠㅠ

2021-06-17 15:26 UTC, sefide commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +        return new ChangePasswordResponseDto("비밀번호 변경 성공하였습니다.");
옷 아니 괜찮습니다 ! 해당 브랜치에서 확인해볼게요 (_ _) !

2021-06-17 16:28 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +        return new ChangePasswordResponseDto("비밀번호 변경 성공하였습니다.");
#52 해당 PR 확인해보시면 될 것 같습니다!

2021-06-18 08:41 UTC, sefide approved these changes
#19 커밋 위주로 확인했는데 잘 반영해주신 것 같아 어프드리옵니다 !

2021-06-19 07:21 UTC, seonghun127 approved these changes
Request, Response DTO 클래스에 대한 유효성 검사 테스트를 완전 빡쎄게(?)해서 놀랬습니다.
(사실 저는 DTO에 대한 테스트 코드는 안짜거든요...🙄)
물론, 좋다는 이야기입니다. 테스트 코드를 작성하는건 무조건적으로 좋다고 생각하기 때문입니다.
Approve 할게요~

2021-06-19 07:21 UTC, seonghun127 commented on src/docs/asciidoc/api-docs.adoc
> +- 회원 비밀번호 변경 실패 example(존재하지 않는 회원 식별자) include::{snippets}/changePassword/fail/noMember/http-response.adoc[]
include 에서 줄바꿈이 있어야겠네요

2021-06-19 10:26 UTC, seongbeenkim commented on src/docs/asciidoc/api-docs.adoc
> +- 회원 비밀번호 변경 실패 example(존재하지 않는 회원 식별자) include::{snippets}/changePassword/fail/noMember/http-response.adoc[]
수정하였습니다!

2021-06-19 10:33 UTC, merged