Feature/#45/회원 탈퇴 기능 구현
kodesalon/project pull request #47
Opened 2021-06-09 10:32 UTC by sdrs6921

### 개요
- 이슈 번호 : #45 
- 내용 : 회원 탈퇴 기능 구현

### 작업 사항
- 회원 탈퇴 Controller 테스트 작성
- 회원 탈퇴 Controller 구현
- 회원 탈퇴 Service 테스트 작성
- 회원 탈퇴 Service 구현
- 회원 탈퇴 Repository 테스트 작성

### 기타
- deleteById를 해서 삭제하는 것이 좋은 지, 아니면 Member을 조회해서 delete(Entity)로 삭제하는 것이 더 좋을지 고민이 되어서 두 가지 방식 모두 작성해서 올렸습니다. 혹시 어떠한 방식으로 삭제에 관한 처리를 하시는 지 궁금합니다!

2021-06-11 20:51 UTC, sefide requested changes
코드가 깔끔해서 특별한 코멘트는 없네요 고생하셨어유 👍🏼 

1) Member 정보를 삭제하는 방식에 대해 질문 주셨네요. 
`deleteMember2` 메소드는 존재하지 않는 회원을 삭제하는 경우에 아래와 같은 Exception이 발생하네요 !
> org.springframework.dao.EmptyResultDataAccessException: No class com.project.kodesalon.model.member.domain.Member entity with id 1 exists!

존재하지 않는 회원에 대해 어떻게 처리하는지 차이가 있을 것 같아요. 
- `deleteMember2`의 경우, Exception이 발생해 이에 대한 처리를 해줘야하는 반면, 
- `deleteMember`는 앞서 유효성 검증을 통해 Exception을 직접 발생시키거나, 삭제 진행을 하니까요.
    
현업에서는 어떻게 활용하는지 @seonghun127 님 이야기가 궁금하네요.
저라면 기존에 선언되어 있는 findById 메소드를 활용하여 체크 후 -> `delete`로 삭제 진행하는게 어떨까 의견 내봅니다. ㅎㅎ.
 근데 보통 회원 탈퇴 시, 실제 바로 회원정보를 삭제하고 있지는 않는걸로 알고 있어서 이 부분도 함께 고민해보면 좋을 것 같아요. 


2) 그리고 제가 확인을 제대로 못한걸까요 ? 회원 탈퇴 Api-Docs도 추가해야 할 것 같아요.

2021-06-11 20:51 UTC, sefide commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +        return new DeleteMemberResponseDto("회원이 성공적으로 삭제되었습니다");
#46 에서 @seonghun127 님께서 [남겨주신 리뷰](https://github.com/kodesalon/project/pull/46#discussion_r649181816)와 동일한 의견인데요. 
유저뷰에 노출할 메세지라면 서버에서 관리하는 것보다는 상태 코드로 응답해주고 메세지는 프론트단에서 관리하는게 좋습니다. 메세지 변경 요구사항이 꽤 자주 있기 때문에 기능이 변경되어서 필요한 경우 외의 작업은 최소화하는게 좋아요 ~

2021-06-11 20:51 UTC, sefide commented on src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
> +    void deleteMember() throws Exception {
delete 방식에 대한 고민이 끝나면 실패하는 경우도 추가해주면 좋을것 같아요

2021-06-12 16:27 UTC, seonghun127 requested changes
리뷰가 늦었습니다; 몇몇개의 코멘트 남겼으니 확인부탁드려요 🙏

PR 코멘트 질문에 답변을 드리자면 아래와 같습니다.

어떤 방식으로 할 지는 크게 상관없을 거 같습니다. 결국 트레이드 오프라 생각해요.
정리하면 아래와 같을 거 같습니다.

1) 삭제 전 데이터 조회
   * 삭제전 존재하는지 확인하기 위해 해당 엔티티 조회
   * 엔티티가 존재한다면 삭제 시도

> 장점 : 장점으로는 삭제 시도 시 대상 데이터가 무조건 존재한다는 것을 보장받을 수 있음
단점 : 쿼리가 2번 발생함

2) 바로 데이터 삭제 시도

> 장점 : 쿼리가 1번 발생함
단점 : 대상 데이터가 존재하지 않는 경우가 발생할 수 있기 때문에 해당 메서드를 사용하는 쪽에서 예외처리가 필요

그런데 이는 데이터를 삭제한다고 했을 때 이야기이고요.
데이터를 굳이 삭제해야할까라는 의문이 듭니다.

데이터를 삭제하지 않고 `deleted`와 같은 삭제 flag를 관리하는 필드(칼럼)을 추가해서 이 값이 true면 삭제된 것으로 관리해도 되지 않을까 싶어요.
즉, 삭제 처리 시 삭제 쿼리로 실제 데이터를 삭제하는 것이 아닌 삭제된 값이라고 인지할 수 있도록 삭제 flag 값을 바꿔주는 방식이 되겠죠.
이렇게 처리하면 장점으로 DB에서 데이터 재정렬 처리가 필요없다는 것이 있습니다.
만약 A 라는 테이블에 인덱스가 여러개가 있고 그 인덱스의 크기(용량)이 크다면 데이터 삭제 시 다시 인덱싱하는 작업에 적지않은 부하가 있을 수 있습니다. 물론 innoDB는 이 부분을 실시간 처리가 아닌 데이터 변경 관리 버퍼를 두고 처리함으로써 원활한 OLTP 환경을 제공해주긴 하지만 결국 버퍼의 데이터 변경 내역을 스토리지에 반영이 필요하고 그 시점엔 DB 서버 자체가 원활하지 않을 수 있습니다.
삭제 flag에는 인덱스를 걸 필요가 없을터이니 이 값이 변경될 때마다 인덱싱이 다시 수행될 필요도 없고 데이터도 삭제되지 않으니 위와 같은 상황을 애초에 방지할 수 있을 것입니다.

물론 데이터 삭제가 빈번하게 발생하는 비지니스가 아니라면 굳이 이부분까지 고려할 필요가 있을까 싶은 생각이 들 수 있지만 토이 프로젝트 시 오버엔지니어링은 상당 부분 필요하다고 생각해요. 아직 DB의 개념적 지식이 학습되지 않아서 이러한 이야기가 무슨 말인지 이해안돼도 괜찮습니다. 용어들만 먼저 접해보면서 나중에 어떤 것들을 공부하면 좋을 지 키워드만 가져가도 매우 좋은 상황이라 생각해요.

삭제 flag가 추가되면 이러한 의문이 들거에요.
조회 시 매번 where절에 해당 flag가 false인 조건이 추가되어야해서 코드 작성이 번거러워지지 않을까 라는 생각이 들 수 있습니다.
이 부분은 [이 블로그](https://cheese10yun.github.io/jpa-where/)를 한번 봐보시면 좋을 거 같아요.

2021-06-12 16:27 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +        memberRepository.delete(member);
delete() 메서드의 구현체를 보면 내부적으로 해당 엔티티가 존재하는지 조회를 하고 있습니다.
그래서 지금 코드는 memberId에 해당하는 값을 2번 조회해서 삭제를 시도하고 있어요.
`findById(memberId)` 는 지워도 될 거 같습니다.

2021-06-12 16:27 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +    public DeleteMemberResponseDto deleteMember(Long memberId) {
`@Transactional` 어노테이션이 필요합니다.
위 어노테이션이 없기 때문에
1. `findById(memberId)` 에서 DB 접근 1번 발생 (조회 쿼리) -> 트랜잭션 종료 (1차 캐시 휘발)
2. `delete(member)` 에서 DB 접근 2번 발생 (조회 쿼리, 삭제 쿼리) -> 트랜잭션 종료
로 총 DB 접근이 3번 발생으로 비효율적으로 동작하게 됩니다.

만약 하나의 트랜잭션으로 묶이면 1번에서 1차 캐시가 휘발되지 않기 때문에 `delete(member)`에서 조회 쿼리가 발생하지 않을 것입니다. 엔티티 조회 시도 시 1차 캐시에 해당 엔티티가 존재할 것이기 때문에 쿼리 발생x

**쿼리가 여러번 발생한다는 것은 DB I/O, 쿼리 수행/처리 가 많아진다는 것이고 그것이 곧 부하로 이어집니다.
불필요한 쿼리를 줄일 수 있도록 어플리케이션에서 관리하는 것이 매우 중요합니다.**

2021-06-13 09:23 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +        return new DeleteMemberResponseDto("회원이 성공적으로 삭제되었습니다");
넵!! 이 부분도 추가적으로 반영하겠습니다!!

2021-06-16 14:05 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
> +    void deleteMember() throws Exception {
넵넵 이미 삭제한 회원에 대한 삭제 요청을 보내거나, 존재하지 않는 회원에 대해 삭제 요청을 하는 부분을 추가해주었습니다!

2021-06-16 14:09 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/repository/MemberRepository.java
> +    void deleteById(Long memberId);
`deleteById()` 를 기존에 제공해준다는 것을 모르고 구현해준 부분인 것 같습니다..
해당 부분 제거하였습니다!
데이터 삭제가 아닌 `flag`로 처리하는 방식으로 수정을 하여,
`CrudRepository`가 제공하는 `deleteById()`도 사용하지 않게 하였습니다!

2021-06-16 14:09 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/member/service/MemberServiceTest.java
> +        verify(memberRepository, times(1)).delete(any(Member.class));
해당 부분은 명시해주는 것으로 통일하기로 하였습니다! :)

2021-06-16 14:14 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +    }
넵넵! 이 부분에 대해서 프론트와 같이 이야기를 나누었고
앞으로 프론트에서 에러 코드를 받아서 해당 에러에 대한 메세지를 프론트에서 관리하며 출력해주도록 하는 방식으로 진행하기로 하였습니다!

2021-06-16 14:16 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +        memberRepository.delete(member);
https://github.com/kodesalon/project/pull/47#discussion_r652727692 에 남긴 대댓글을 내용처럼 데이터를 삭제하지 않고 `flag`로 관리하는 방식으로 수정하여, 해당 로직 제거되었습니다!

2021-06-16 14:20 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +    public DeleteMemberResponseDto deleteMember(Long memberId) {
넵넵 말씀하신 것처럼 트랜잭션, 함수가 JPA에서 어떻게 동작하는 지에 대한 이해도가 부족하여 이렇게 구현을 하게된 것 같습니다.
이러한 부분에 더 신경쓰고 공부하면서 구현하도록 하겠습니다!

2021-06-17 15:25 UTC, sefide requested changes
delete 방식에 대한 고민의 끝으로 _깔꼼한_ 코드가 나온 것 같네요. 
두 가지 코멘트만 남겼는데 한가지가 마음에 걸려 Request changes 했습니다 ! 


+) 데이터를 삭제하는 것이 아닌 삭제 flag로 관리하는 것으로 변경하셨군요 👍🏼 

flag로 관리하는 것에 대해서는 성훈님께서 자세히 코멘트 주셔서.. 크게 할 얘기는 없지만... 
조금 더 덧붙이자면 서비스 측면에서도 바로 데이터 삭제를 하는걸 요구하진 않아요. 탈퇴한 회원이 계정을 복구해달라고 하거나 회원 이외의 데이터를 복구하도록 요구하는 경우가 은근 많기 때문인데요. 그래서 보통 회원가입 시 회원정보 유지 기간을 고지하고 탈퇴 후 그 유지기간 동안은 데이터를 보관하는 것 같아요. 추가적으로 탈퇴 flag 외에 탈퇴일자도 함께 저장해두고요. 더불어 회원 정보는 서비스 내 다른 데이터와 연관이 많이 되기 때문에 바로 삭제를 진행하는 건 서비스가 커질수록 어려운 일이 되는것 같아요. 
(실무에서 "_회원 탈퇴 시 데이터 바로 삭제.._" 와 같은 요구사항을 주는 경우가 있어서 서비스 측면으로 생각하는 연습도 많이 해두면 좋을 것 같아요. 안그럼 한번에 해결할 수 있는 문제를 금방 해결하지 못할때가 있어요ㅠ )

2021-06-17 15:25 UTC, sefide commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
> +@Where(clause = "deleted = 'false'")
회원 관련 조회 시, 기본적으로 탈퇴한 회원은 필터링되도록 @Where를 이용해 간단히 해결하신것 같네요 !

여기서 탈퇴한 회원과 동일한 `alias`로 회원가입을 가능하게 할지 궁금한데요 ! 현재 코드로는 탈퇴 회원의 필터링 처리로 동일한 `alias`라도 회원가입이 가능하게끔 의도하신 것 같아요. 그런데 해당 상황 재연 시 동일한 alias로 무결성 제약조건이 깨져 JdbcSQLIntegrityConstraintViolationException이 발생하는 것 같아요. 이 부분에 대한 처리도 필요할 것으로 보입니다 !

2021-06-17 16:07 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/member/service/MemberServiceTest.java
> +    @DisplayName("회원 탈퇴에 성공한다.")
> 조금 더 덧붙이자면 서비스 측면에서도 바로 데이터 삭제를 하는걸 요구하진 않아요. 탈퇴한 회원이 계정을 복구해달라고 하거나 회원 이외의 데이터를 복구하도록 요구하는 경우가 은근 많기 때문인데요. 그래서 보통 회원가입 시 회원정보 유지 기간을 고지하고 탈퇴 후 그 유지기간 동안은 데이터를 보관하는 것 같아요. 추가적으로 탈퇴 flag 외에 탈퇴일자도 함께 저장해두고요. 더불어 회원 정보는 서비스 내 다른 데이터와 연관이 많이 되기 때문에 바로 삭제를 진행하는 건 서비스가 커질수록 어려운 일이 되는것 같아요.

넵넵 데이터가 바로 삭제되지 않아야 된다는 점에 동의합니다!
말씀하신것처럼 탈퇴 날짜 저장 및 회원 정보를 보관하고, 일정 기간이 지나면 DB에서 삭제하는 방식 등을 다른 팀원들과 상의해보도록 하겠습니다!

2021-06-18 00:36 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/member/service/MemberServiceTest.java
> +    @DisplayName("회원 탈퇴에 성공한다.")
여기 [리뷰](https://github.com/kodesalon/project/pull/40#pullrequestreview-686928646)에 있는 내용 중 `BaseEntity` 부분도 참고해보세요~

2021-06-18 09:09 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
> +@Where(clause = "deleted = 'false'")
해당 부분은 고려하지 못한 상황이었네요!
삭제한 회원 아이디로 가입 시도를 할 경우, 가입을 하지 못하게 수정하였습니다.

1차 배포 후, 삭제 날짜와 현재 날짜를 비교하여 일정 시간이 지나기 전까지는 같은 아이디로 가입을 금지하게 하고 
일정 시간이 지나 회원 데이터가 삭제되면 그 이후에는 같은 아이디로 가입을 허용하게 하는 방안으로 구현하려고 하는데 어떻게 생각하시나요?

2021-06-19 15:07 UTC, seonghun127 requested changes
빠른 리뷰 반영이네요~ 몇가지 피드백 남겼으니 확인해주세요!

2021-06-19 15:07 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
> +    public Member(final Alias alias, final Password password, final Name name, final Email email, final Phone phone) {
생성자 파라미터 타입을 모두 VO로 바꾸신 이유가 무엇인가요?
개인적으로 이전처럼 String 으로 받고 있는데 추후 `Member` 객체를 생성하는 부분에서 더 유연하게(편하게) 생성할 수 있다고 생각해요.
VO 객체를 인자로 받으면 해당 객체를 외부에서 직접 생성한 뒤 주입시켜줘야하는데 클라이언트 입장에서 원시값(String은 원시값이 아니지만 특수한 클래스이므로 원시값으로 칭하겠습니다.)을 주입시키고 `Member` 생성자 내부에서 알아서 값 객체 생성하도록 두는게 더 편리하지 않을까요?

2021-06-19 15:07 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
> +    public Member(final Alias alias, final Password password, final Name name, final Email email, final Phone phone) {
`CreateMemberRequest`클래스의 `toMember()` 메서드에서 일일이 VO 객체를 생성해서 주입시켜주고 있는데요. 지금은 이 메서드만 호출하면 그만이지만 그외에 `Member` 엔티티를 만들어야하는 상황이 오면 전부 VO 객체를 일일이 만들어줘야하니 복잡도가 올라간다고 생각해요~

2021-06-19 15:07 UTC, seonghun127 commented on src/docs/asciidoc/api-docs.adoc
> +- 회원가입 실패 Exaple (탈퇴한 회원의 Alias로 회원 가입)
`Example` 오타가 있네요~

2021-06-19 15:27 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
> +    @Getter
> 이 필드만 lombok @Getter을 사용하신 이유가 있을까요?

다른 VO와는 달리 Id와 deleted의 경우에는 값 그대로 리턴해도 상관 없다고 생각해서 코드의 수를 줄이기 위해 사용하였습니다.
다른 필드와의 통일성을 위해 이 부분을 변경하였습니다!

2021-06-19 15:29 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
> +    private boolean deleted;
넵! 이부분은 바로 반영하였습니다!

2021-06-19 15:31 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
> +    public Member(final Alias alias, final Password password, final Name name, final Email email, final Phone phone) {
> 생성자 파라미터 타입을 모두 VO로 바꾸신 이유가 무엇인가요?

각각의 값 객체를 생성하는 부분과 Member Entity 객체를 생성하는 부분을 분리하기 위해 생성자 파라미터 타입을 모두 VO로 바꾸었습니다.

2021-06-19 15:33 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
>  @Table(name = "member", uniqueConstraints = {@UniqueConstraint(columnNames = {"alias"})})
코드 레벨에서 명시해 주는 것이 DB를 찾아서 접근하는 것 보다 더 유용한 것 같습니다. 이 부분도 반영하였습니다!

2021-06-19 15:35 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
>  @NoArgsConstructor
Jpa에 영향을 주지 않는 Protected Level로 기본 생성자의 접근 제어 수준을 조정하였습니다!

2021-06-19 15:37 UTC, sdrs6921 commented on src/docs/asciidoc/api-docs.adoc
> +- 회원가입 실패 Exaple (탈퇴한 회원의 Alias로 회원 가입)
이 부분도 바로 바꾸었습니다!

2021-06-21 12:17 UTC, sefide commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
> +@Where(clause = "deleted = 'false'")
탈퇴 처리 후, 일정 시간 지난 회원 정보는 완전 삭제하는걸까요 ? 
이 부분에 대한 정책만 확실하게 정하면 어떤 방향이든 괜찮을 것 같은데
영구 삭제가 안되는건 개인정보 보호법상 불가능한 이야기라 첫번째 방법이 보통이겠네요
- 회원 탈퇴 (탈퇴 flag 처리)
1) 탈퇴한 회원 정보, 일정 시간 지나면 회원 정보 영구 삭제 => 회원 Table 전체에서 중복되는 `alias`가 있는지 확인, `alias`은 카디널리티가 높아서 전체 조회 시에 특별히 이슈가 없지 않을까 싶습니당
2) 탈퇴한 회원 정보 유지 => 탈퇴 시점이 지난 회원을 제외하고 동일한 `alias`가 있는지 확인

2021-07-06 06:09 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/member/service/MemberServiceTest.java
> +    @DisplayName("회원 탈퇴에 성공한다.")
> 날짜관련 내용은 여기 [리뷰](https://github.com/kodesalon/project/pull/40#pullrequestreview-686928646)에 있는 내용 중 `BaseEntity` 부분도 참고해보세요~

BaseEntity 클래스 생성만 해놓았으며 오늘 프론트와 이야기하여 어떻게 날짜 받아올지 이야기 후 수정하도록 하겠습니다!

2021-07-12 02:01 UTC, sefide approved these changes
jwt까지 적용하니 엄청 깔끔하게 정리가 된 것 같습니다 👍🏼 
아래 질문 내용은 내용 정리 후 반영해도 될 것 같아 우선 어프드립니당 !

혹시 탈퇴한 회원과 동일한 `Alias`를 가진 정보로 회원가입을 시도한 경우는 어떻게 하기로 했을까요 ? 
지금은 MemberService의 `validateDuplicationOf` 메소드에서는 삭제되지 않은 회원을 기준으로 `Alias` 중복을 확인하기 때문에 `ConstraintViolationException`이 발생하고 있네요.

2021-07-12 03:33 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
> +        given(loginInterceptor.preHandle(any(HttpServletRequest.class), any(HttpServletResponse.class), any()))
현재는 탈퇴한 회원과 동일한 `Alias`로 회원가입을 할 수 없도록 하였습니다.

이 부분은  #23 PR의 해당 커밋에서 https://github.com/kodesalon/project/pull/54/commits/3f82d632230151c169a7dfcb6c0afde0e87848e2 
`DataIntegrityViolationException`에 대한 처리를 해주고 있어 `ConstraintViolationException`까지 커버가 되는 것으로 확인하였습니다!!

2021-07-12 08:46 UTC, sefide commented on src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
> +        given(loginInterceptor.preHandle(any(HttpServletRequest.class), any(HttpServletResponse.class), any()))
넵 #23 커밋에서 확인해보겠습니다 🙇‍♂️

2021-07-15 12:03 UTC, seonghun127 approved these changes
jwt 적용된 후로 API가 restful 해졌네요 ㅎㅎㅎ 코드 또한 보다 간결해졌다고 생각합니다. 수고하셨어요.
몇가지 피드백 남겼으니 확인부탁드려요. (남긴 피드백들은 간단한 내용들이 미리 Approve 할게요!)

추가로 하나 더 이야기하자면,
지금 BaseEntity가 추가됐고 해당 엔티티에 생성/수정 날짜 필드가 존재하니 이 값을 초기화하고 갱신시켜주는 로직도 전반적으로 반영되어야할 것으로 보입니다.
지금 PR에선 회원이 탈퇴하는 `Member.delete()` 메서드에서도 해당 로직이 필요하겠죠.
PR 별로 반영할 것인지 한번에 반영하는 issue 티켓을 딸 것인지 정해서 반영하면 좋을 것 같아요~

2021-07-15 12:07 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
> +        given(loginInterceptor.preHandle(any(HttpServletRequest.class), any(HttpServletResponse.class), any()))
혹시 `willThrow()` 메서드가 먼저 호출되고 안그러고의 차이를 이야기하는 것일까요?
* 반환값이 void인 메서드를 스터빙하기 위해서는 아래 메서드를 사용해서 먼저 결과값을 설정해줘야합니다.
   * org/mockito/BDDMockito.java:488
---
제가 질문의 의도를 잘못이해한 것이라면 정정해주세요~ 🙏

2021-07-15 12:13 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
> +    public void delete() {
넵넵 맞습니다! `BaseEntity`는 브랜치 별이 아닌 추후에 한 번에 적용할 예정이었어서 이슈 티켓 새로 만들어 추후 해당 부분 수정하도록 하겠습니다!

2021-07-15 12:14 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/common/BaseEntity.java
> +    protected LocalDateTime createdDate;
이 부분도 위에 댓글 남긴 내용https://github.com/kodesalon/project/pull/47#discussion_r670404118과 같이 BaseEntity 적용 이슈 발급하여 적용할 때 하도록 하겠습니다!

2021-07-15 12:18 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/common/BaseEntity.java
> +    protected LocalDateTime createdDate;
제가 기억하기로는 `Time`을 적어주었던 것 같은데 아니었네요ㅠㅠ 이 부분 수정하겠습니다!

> `BaseEntity` 추가 후 배포가 있었는지 모르겠지만 DB 변경도 같이 일어나야겠네요. (DB 스키마 변경을 아직 안했기를 바랍니다 😂)

 헛... 프론트에서 jwt 토큰 받아오는 기능이 필요하다해서 급하게 배포를 했었는데 이 부분 확인해보겠습니다😂

2021-07-15 12:19 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +    public void deleteMember(Long memberId) {
이 브랜치 말고 다른 브랜치에서 수정을 했나보네요!
해당 부분은 다른 브랜치에서 `final` 적용된 상태입니다!

2021-07-15 12:22 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
> +        given(loginInterceptor.preHandle(any(HttpServletRequest.class), any(HttpServletResponse.class), any()))
앗 이 부분 저희가 @sefide님의 질문에 대한 답변을 달지 않고 공통 코멘트에 대한 답변을 달았었네요!

성훈님이 말씀하신 의도대로 저희가 구현을 해주었습니다!!

2021-07-15 12:56 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/common/BaseEntity.java
> +    protected LocalDateTime createdDate;
배포가 정상적으로 이뤄졌는지 확인이 필요하겠네요~

2021-07-16 04:12 UTC, merged

2021-07-18 05:48 UTC, sefide commented on src/test/java/com/project/kodesalon/model/member/controller/MemberControllerTest.java
> +        given(loginInterceptor.preHandle(any(HttpServletRequest.class), any(HttpServletResponse.class), any()))
오 맞습니다. 그 차이가 맞네요. 혼자서 테스트하다 실수해서 차이가 없다고 생각했어요. 
답변 감사합니다 👍🏼