Feature/#51/게시물 회원 연동
kodesalon/project pull request #52
Opened 2021-06-17 08:44 UTC by seongbeenkim

### 개요
- 이슈 번호 : #51 
- 내용 : 게시물 - 회원 연동

### 작업 사항
- 게시물 - 회원 연동 
- Error 코드 추가

### 기타
- #51 커밋 내역만 보시면 됩니다! :)

2021-06-19 16:10 UTC, seonghun127 requested changes
드디어 엔티티간 연관관계가 생겼군뇨...ㅎㅎㅎ JPA에 대해 더 탐구해봐요~
몇가지 피드백 남겼으니 확인해주세요!

2021-06-19 17:58 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +        member.addBoard(createdBoard);
넵넵 연관관계 편의 메서드처럼 생성자 내부에 위치하도록 수정하였습니다!

2021-06-19 18:04 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/board/service/BoardServiceTest.java
> -        verify(boardRepository, times(1)).save(any(Board.class));
이 부분은 제가 놓친 부분이었어서 이후 PR 올린 #24 게시물 삭제 브랜치에서 수정했었습니다.
해당 브랜치에서도 다시 한번 수정하였습니다~

2021-06-19 18:13 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +        Member member = memberRepository.findById(memberId)
Repository에 직접 물어보는 것이 Service를 거치면서 조회하는 것보다 단계를 줄일 수 있지 않을까라고 생각하며 `MemberRepository`를 의존하게 하면서 구현을 했었습니다.
구현하면서, 중복적인 `findById` 메소드가 `MemberService`, `BoardRepository` 두 곳 모두에 존재하게 되면서 이 부분 스터디 시간에 질문하려고 했던 부분인데 피드백 주셔서 감사합니다~

2021-06-21 13:01 UTC, sefide approved these changes
지난 스터디 시간에 함께 보면서 얘기 나눴어서 간단한 코멘트만 남기고 어프드립니다 !

2021-07-06 08:30 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +@Slf4j
해당 부분 로그 남기도록 수정하였습니다!

2021-07-06 08:34 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/service/dto/BoardCreateRequest.java
> +    private LocalDateTime createdDateTime;
클라이언트에서 요청을 받고 서버에서 자동으로 생성 날짜를 생성하게 될 시
요청을 받고 날짜를 생성하는 아주 짧은 시간차이(ex) 0.001)가 생기게 되어 정확한 생성 시간을 가지지 못하다는 피드백을 받았고,
현재 저희 프로젝트 같은 경우 서버에서 날짜 자동 생성을 해도 괜찮지만, 실무에서 쿠폰, 이벤트 생성 및 만료 날짜와 같은 개념을 다룰 경우 이러한 아주 짧은 시간이 아주 중요하다고 생각되기 때문에 클라이언트에서 받는 방식으로 구현을 하게 되었습니다!

2021-07-12 02:46 UTC, sefide commented on src/main/java/com/project/kodesalon/model/board/service/dto/BoardCreateRequest.java
> +    private LocalDateTime createdDateTime;
오 그렇군요 ! 

참고로 말씀드리자면, 
다른 곳에서는 어떻게 하는지 모르겠지만 제가 발을 담갔던 곳에서는 시간 관련 이벤트는 서버 시간 기준으로 운영하고, 클라이언트로부터 요청 시간을 받아 서버 시간과 비교해서 이벤트 결과(?) 여부를 결정해요. 
이벤트 운영 시간 자체를 클라이언트 시간을 기준으로 잡게 되면 클라이언트 환경에 따라 시간이 달라질 수 있는데, 클라 정보가 해외인 경우, 타임존 이슈도 발생할 수 있고요 ! 그래서 이벤트 시간은 서버에 저장해두고 이 정보를 클라에게 제공하는 방식을 선택한 것 같아요. 
@seongbeenkim 님 말씀처럼 지금 프로젝트에서는 서버에서 생성해도 되지만 이런 경우에 사용될 수 있겠네요 ~! 참고참고쓰

2021-07-12 03:12 UTC, sefide approved these changes
리뷰 반영 잘해주셨네요 ! 👏🏼

2021-07-12 13:29 UTC, sefide commented on src/main/java/com/project/kodesalon/model/board/service/dto/BoardCreateRequest.java
> +    private LocalDateTime createdDateTime;
> 시간 관련 이벤트는 서버 시간 기준으로 운영하고, 클라이언트로부터 요청 시간을 받아 서버 시간과 비교해서 이벤트 결과(?) 여부를 결정해요.

요 대목에서  클라이언트로부터 요청 시간 정보를 직접 받는게 아니라 서버가 클라이언트에게 요청받은 시간 정보를 이용할 것 같아요. 직접 시간 정보를 받는건 중간에 변경될 위험 요소가 있어서요. 관련해서 여쭤봤던 동료분께 다시 여쭤보고 공유드릴게요 :*-(

2021-07-12 17:15 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/service/dto/BoardCreateRequest.java
> +    private LocalDateTime createdDateTime;
넵넵 알겠습니다!! 감사합니다 :)

2021-07-15 12:44 UTC, seonghun127 approved these changes
수고하셨습니다~ 간단한 리뷰 하나 남겼으니 확인부탁드려요. (Approve 할게요~)

추가로 `Board`에 JPA관련 어노테이션을 `Member` 같은 형식으로 맞추면 좋을 것 같습니다.
예를 들어 `@Table` 어노테이션을 명시하여 테이블 이름을 직접 관리하는 것이 관리 측면이나 통일성 측면이나 좋아보입니다.

2021-07-15 12:44 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +        log.info("Member alias : {}, Board Id : {}", member.getAlias(), createdBoard.getId());
위 로그를 남기는 시점의 `createdBoard`는 영속화가 진행되지 않았기 때문에 `getId()`를 호출해도 null이 나올 것입니다.

2021-07-15 12:45 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/service/dto/BoardCreateRequest.java
> +    private LocalDateTime createdDateTime;
서버에서 시간을 생성한다고 하면 프리젠테이션 레이어에서 현재 날짜/시간을 생성해서 비지니스, 도메인 레이어로 전달하는 것도 하나의 방법입니다. 실제 클라이언트가 요청을 보낸 시간과 정확히 일치할 순 없겠지만 실제 서비스하는데 큰 차이가 없기 때문에 이렇게도 많이 개발해요~

2021-07-15 12:46 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +        log.info("Member alias : {}, Board Id : {}", member.getAlias(), createdBoard.getId());
앗.. 그러네요
`save()` 다음 줄에서 로그 출력하도록 수정하겠습니다!

2021-07-15 12:48 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/service/dto/BoardCreateRequest.java
> +    private LocalDateTime createdDateTime;
두 분이 말씀해주신 부분 고려해서
어떠한 방식으로 할 지 @sdrs6921과 이야기해보도록 하겠습니다~!

2021-07-15 12:53 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/service/dto/BoardCreateRequest.java
> +    private LocalDateTime createdDateTime;
@sefide 님, 
> 서버가 클라이언트에게 요청받은 시간 정보
라는게 어떤 정보를 사용하는 것인가요? 요청 헤더 중 하나의 값을 사용하는 것일까요?

2021-07-16 04:09 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/board/service/dto/BoardCreateRequest.java
> +    private LocalDateTime createdDateTime;
지금은 클라이언트에서 받아 오는 것으로 하고 추후에 프레젠테이션 레이어에서 현재 날짜나 시간을 생성하는 방식으로 변경하는 것이 좋을 것 같습니다.

2021-07-16 04:22 UTC, merged

2021-07-18 05:49 UTC, sefide commented on src/main/java/com/project/kodesalon/model/board/service/dto/BoardCreateRequest.java
> +    private LocalDateTime createdDateTime;
@seonghun127 님 
> 서버가 클라이언트에게 요청받은 시간 정보

는 클라이언트에게서 헤더나 파라미터로 따로 받는 정보는 아니고요. 프레젠테이션 레이어에서의 서버 시간이라고 보시면 될 것 같아요.