Feature/#24/게시물 삭제 기능 구현
kodesalon/project pull request #53
Opened 2021-06-19 05:58 UTC by seongbeenkim

### 개요
- 이슈 번호 : #24 
- 내용 : 게시물 삭제 기능 구현

### 작업 사항
- 게시물 삭제 기능 구현

### 기타
-

2021-06-20 15:41 UTC, seonghun127 requested changes
API 설계에 대해 고민이 좀 필요해보여요. 현재 로그인된 정보를 전혀 저장하는 곳이 없으니 회원에 대한 모든 요청에 대해서 request body나 path variable로 회원 식별자가 값을 직접 받아야하는 방식으로 API들이 구현되고 있는데요, session, jwt를 이용해서 로그인된 정보를 관리하는 방식을 도입시키면 좋을 거 같습니다~
이 부분이 먼저 적용되어야 다른 API에 변경 사항이 많이 줄일 수 있을 거 같습니다.

그외 몇가지 피드백 남겼으니 확인부탁드려요~

2021-06-20 15:41 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/board/controller/BoardControllerTest.java
> +    @DisplayName("내용이 존재하지 않을 경우 HTTP 400과 예외 코드를 반환한다.")
`@DisplayName`의 내용이 바뀌어야할 거 같아요~

2021-06-20 15:41 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/controller/BoardController.java
> +    public ResponseEntity<Void> delete(@RequestBody final BoardDeleteRequest boardDeleteRequest) {
삭제하려는 게시물의 식별자 값을 request body로 받고 있는데요, 삭제 대상의 식별자 값은 path variable로 받는게 restful 한 설계입니다.
삭제 대상인 게시물에 대해서 삭제 권한이 있는지 체크하기 위해 memberId를 따로 받고 있는걸로 추정되는데, 그래서 이를 boardId와 같이 request body로 받은 것일까요?
로그인된 정보를 담는 session 정보를 만들어서 현재 로그인된 정보를 request/response header 값으로 전달한다면 따로 memberId는 안받아도 될 거 같아요. 그러면 boardId는 path variable로 받을 수 있을 거구요.

2021-06-20 15:41 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/domain/Board.java
> +    private void validateAuthorizationOf(Member member) {
`Board` 객체 내에선 writer라는 표현을 쓰고 있으니 파라미터의 이름도 writer로 변경하면 어떨까요?

2021-06-20 15:41 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/domain/Board.java
> +        return writer.equals(member);
현재 게시글의 작성자가 맞는지 확인하기 위해 `isWrttenBy()`메서드에서 `Member`객체를 인자로 받고 있고 `Member` 객체에 재정의한 `equals()` 메서드를 호출하고 있는데요.
이를 id만 비교하는 방식으로 수정하면 좋을 거 같아요. (`equals` 메서드를 수정하라는 이야기는 아닙니다.)
Service 레이어에서 이 메서드에 `Member` 객체를 전달하기위해서 한번 DB 조회를 하고 있는데, 꼭 조회할 필요가 있을까라는 생각이 들어서요. memberId의 값을 이미 알고 있으니 이 값으로만 비교해도 충분히 삭제할 권한이 있는지 확인할 수 있을 것으로 판단됩니다.
`Board` 객체의 `Member` 필드는 프록시지만 `getId()`를 호출한다고해서 조회 쿼리는 발생하지 않습니다. 프록시는 이미 식별자 값을 알기 때문인데요, 이와 같이 수정한다면 `Member` 테이블을 조회하는 쿼리 1개를 줄일 수 있을 것입니다.

2021-06-20 15:41 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
> +        return alias.equals(member.alias);
id 값으로 비교하는게 더 좋아보입니다~ (오프라인이에서 이야기했지만 한번 더 언급해요)

2021-06-21 14:02 UTC, sefide requested changes
@seonghun127 님과 같은 의견으로 회원 정보를 저장하고 클라이언트와 주고 받는 방법에 대해 고민이 필요할 것 같아요 ! 현업에서는 회원정보를 파라미터로 주고 받는 경우는 없어서 고민해보고 변경해보면 좋은 경험이 될 것 같아요. 그 외 추가적으로 남긴 코멘트도 확인해주세요 :)

2021-06-21 14:36 UTC, sefide commented on src/main/java/com/project/kodesalon/model/board/domain/Board.java
> +        return writer.equals(member);
이 내용 관련해서 
탈퇴한 회원 정보로 게시물을 삭제하는 경우도 고려해봐야 할 것 같아요 !

2021-07-06 10:11 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/board/controller/BoardControllerTest.java
> +    @DisplayName("내용이 존재하지 않을 경우 HTTP 400과 예외 코드를 반환한다.")
해당 부분 수정하였습니다!

2021-07-06 10:12 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/controller/BoardController.java
> +    public ResponseEntity<Void> delete(@RequestBody final BoardDeleteRequest boardDeleteRequest) {
JWT 적용으로 `boardId` pathVariable로 받게 수정하였습니다!

2021-07-06 10:13 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/domain/Board.java
> +    private void validateAuthorizationOf(Member member) {
넵넵 해당 부분도 `Writer`로 수정하였습니다!

2021-07-07 07:45 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/domain/Board.java
> +        return writer.equals(member);
> 현재 게시글의 작성자가 맞는지 확인하기 위해 `isWrttenBy()`메서드에서 `Member`객체를 인자로 받고 있고 `Member` 객체에 재정의한 `equals()` 메서드를 호출하고 있는데요.
> 이를 id만 비교하는 방식으로 수정하면 좋을 거 같아요. (`equals` 메서드를 수정하라는 이야기는 아닙니다.)
> Service 레이어에서 이 메서드에 `Member` 객체를 전달하기위해서 한번 DB 조회를 하고 있는데, 꼭 조회할 필요가 있을까라는 생각이 들어서요. memberId의 값을 이미 알고 있으니 이 값으로만 비교해도 충분히 삭제할 권한이 있는지 확인할 수 있을 것으로 판단됩니다.
> `Board` 객체의 `Member` 필드는 프록시지만 `getId()`를 호출한다고해서 조회 쿼리는 발생하지 않습니다. 프록시는 이미 식별자 값을 알기 때문인데요, 이와 같이 수정한다면 `Member` 테이블을 조회하는 쿼리 1개를 줄일 수 있을 것입니다.

해당 부분 `memberId`로 비교하도록 수정하여 Member Table 조회하는 쿼리 1개 줄이도록 수정하였습니다!!

> 이 내용 관련해서
> 탈퇴한 회원 정보로 게시물을 삭제하는 경우도 고려해봐야 할 것 같아요 !

회원이 탈퇴할 경우 해당 회원이 생성한 게시물이 삭제되도록 구현하였습니다.

2021-07-07 07:46 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
> +        return alias.equals(member.alias);
id 값으로 비교하도록 수정했습니다~

2021-07-07 07:46 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/domain/Board.java
> +    private boolean deleted;
이 부분 `false`로 수정하였습니다~

2021-07-07 07:48 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/controller/BoardController.java
> +    public ResponseEntity<Void> delete(@RequestBody final BoardDeleteRequest boardDeleteRequest) {
```
@DeleteMapping("/{boardId}")
    public ResponseEntity<Void> delete(@Login Long memberId, @PathVariable final Long boardId) {
        boardService.delete(memberId, boardId);
        return new ResponseEntity<>(HttpStatus.OK);
    }
```
와 같이 말씀하신대로 자원표시하여 `PathVariable`로 받아오게 수정하였습니다~

2021-07-07 07:49 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/board/controller/BoardControllerTest.java
>      void delete() throws Exception {
게시물 작성자와 인자로 전달받은 사용자의 비교 결과가 틀릴 경우, 삭제 요청 실패하게 하는 테스트 코드 추가 해주었습니다!

2021-07-07 07:54 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/domain/Board.java
> +    private void validateState() {
넵 맞습니다. 항상 조회해 오는 게시물은 `"deleted = 'false'"`이기 때문에 삭제가 되었는지 한번 더 유효성 체크를 하는 부분은 없어도 될 것 같습니다! 해당 부분 제거하였습니다!

2021-07-07 08:15 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/domain/Board.java
> +        validateAuthorizationOf(member);
해당 부분 `@Transactional` 어노테이션 추가 및 게시물 삭제 로직을 변경하면서 수정하였습니다!

2021-07-12 08:44 UTC, sefide approved these changes
게시물 삭제 기능 관련해서는 특별히 코멘트할 내용이 없네요 ! 고생하셨습니다 👏🏼

2021-07-17 13:28 UTC, seonghun127 requested changes
몇가지 피드백 남겼으니 확인부탁드려요~
피드백 중 몇몇이 생각이 좀 필요한 부분이라 생각되어 approve는 안하고요~ 내일(7/18) 만남 때 이야기해봐도 좋습니다!

2021-07-17 13:28 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +        memberBoardService.deleteBoardByMemberId(memberId);
지금 `MemberBoardService.deleteBoardByMemberId()` 메서드의 설정된 `@Modifyng` 설정 값을 보면 `clearAutomatically` 설정 값이 true인데요, 이 때문에 그 다음 줄에서 실행하는 `member.delete()`메서드에 대한 dirty checking이 수행되지 않고 있습니다.
즉, clearAutomatically 설정으로 `MemberBoardService.deleteBoardByMemberId()` 수행 직후 persistence context가 자동 clear 되기 때문에 발생하는 문제인데요. 이 부분에 대한 수정이 필요해보입니다.

2021-07-17 13:28 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +        memberBoardService.deleteBoardByMemberId(memberId);
참고차 이 부분을 테스트해봤던 테스트 로직도 공유해봐요~

```java
@SpringBootTest
@AutoConfigureTestEntityManager
public class MemberServiceIntegrationTest {

    @Autowired
    private MemberService memberService;

    @Autowired
    private TestEntityManager entityManager;

    @BeforeEach
    void setUp() {
        entityManager.persist(MemberTest.TEST_MEMBER);
        entityManager.persist(BoardTest.TEST_BOARD);
        entityManager.flush();
        entityManager.clear();
    }

    @Test
    @Transactional
    @Rollback(value = false)
    void test() {
        // given

        // when
        memberService.deleteMember(1L);

        // then
    }
}
```

2021-07-17 13:28 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/repository/MemberRepository.java
> +@Repository
해당 어노테이션은 붙이지 않아도 자동으로 빈 등록됩니다~

2021-07-18 05:49 UTC, sefide commented on src/main/java/com/project/kodesalon/model/memberboard/MemberBoardService.java
> +public class MemberBoardService {
솔직히 저도 리뷰하면서 `MemberBoardService`를 보고 좀 고민이 많이 되었는데요.
> 공통 메소드 도출, MemberService와 BoardService의 순환참조 제거

이 목적으로 추가한 것 같아 특별히 다른 코멘트는 안했네요. 그리고 앞으로 추가될 `Image`나 `Comment`와 같이 새로운 연관관계를 가진 기능이 추가되었을 때 `MemberBoardService`와 같은 클래스들의 존재 여부도 다시 고민할 수 있을거라 생각했어요. (이 시점에 복잡도가 올라가는걸 몸소 느끼지 않을까 싶네요)

@seonghun127 님께서 얘기를 잘해주셔서 특별히 다른 코멘트할 내용은 없는데요. 말씀주신 내용 중
> 추가로 findById() 메서드는 온전히 Member 엔티티만 조회하고 있어요. Board 도 같이 조회해서 Member, Board 엔티티의 필드를 조합해서 Dto를 반환하는 역할을 한다면 facade 의 역할을 하고 있다라고 볼 수도 있겠지만 현재는 그렇지도 않고요.

이 부분이 중요하다고 생각해요. 클래스명 그대로 `Member`, `Board`가 조합된 데이터를 다룬다면 해당 클래스의 존재가 더 뒷받침될거예요.

2021-07-21 04:05 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/authentication/domain/RefreshTokenTest.java
넵넵 제거해주었습니다!!

2021-07-21 04:21 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/domain/Board.java
> +    @Column(name = "deleted")
넵넵 nullable = false, columnDefinition = false로 명시해주었습니다!

2021-07-21 04:30 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +        memberBoardService.deleteBoardByMemberId(memberId);
해당 부분 쿼리만 생각하고 다음 호출되는 부분은 고려를 안했었네요
clearAutomatically 제거해주었습니다!!

2021-07-21 05:11 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/repository/MemberRepository.java
> +@Repository
JpaRepository를 상속하면 해당 어노테이션을 붙이지 않아도 되는것은 몰랐네요!
제거해주었습니다!

2021-07-21 05:15 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/memberboard/MemberBoardService.java
> +public class MemberBoardService {
#23 `게시물 수정 기능 구현`  branch에서 `MemberBoardService` 를 제거하고 `boardRepository` 를 `memberService` 에서 의존하도록 수정하였습니다!

2021-07-28 15:19 UTC, seonghun127 approved these changes
확인이 늦었습니다~ 더는 반영할게 없어보입니다. approve 할게요!

2021-07-30 02:30 UTC, merged