Feature/#23/게시물 수정 기능 구현
kodesalon/project pull request #54
Opened 2021-06-19 15:14 UTC by sdrs6921

### 개요
- 이슈 번호 : #23 
- 내용 : 게시물 수정 기능 구현

### 작업 사항
- 게시물 수정 Controller 테스트 작성
- 게시물 수정 Controller 구현
- 게시물 수정 Service 테스트 작성
- 게시물 수정 Service 구현
- 게시물 수정 Rest Docs 작성

### 기타
-

2021-06-21 14:48 UTC, sefide requested changes
prefix 수정전이신것 같아 #24 prefix 기준으로 확인헀습니다.
추가로 남겨둔 코멘트 이외에 아래 내용 확인 부탁드려요 ~

1. #53 에서와 마찬가지로 회원정보를 전달하는 방법에 대해 함께 고민해주면 좋을 것 같아요. 이 부분에 대한 고민이 끝나면 변경되는 부분이 꽤 있겠어요 !
2. 게시물을 작성한 회원이 아니어도 게시물 수정이 가능한걸까요 ? (지금 코드로는 수정이 가능하네요) 
불가능하다면 게시물 삭제와 같은 정책이므로 공통으로 사용할 수 있는 로직이 있을 것 같아요. 
3. 게시물 수정 관련해서 스터디 시간에 작성했던 repository 테스트도 추가해주면 좋을 것 같아요.

2021-06-21 14:48 UTC, sefide commented on src/test/java/com/project/kodesalon/model/board/service/dto/BoardUpdateRequestTest.java
> +    @NullAndEmptySource
이 어노테이션 활용 잘하는것 같아 보기 좋네요 ㅎㅎ

2021-06-21 14:48 UTC, sefide commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +        return new BoardUpdateResponse("게시물 정보가 변경되었습니다");
오프라인 스터디 시간에 얘기 나눴던것처럼 
HTTP 상태 코드로 내려주거나 해서 통일시켜주면 좋을 것 같아요 !

2021-06-22 11:47 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +        return new BoardUpdateResponse("게시물 정보가 변경되었습니다");
넵 이 부분은 바로 반영하겠습니다!

2021-06-22 14:48 UTC, seonghun127 requested changes
오프라인 때 이야기했던 것 외에 추가 피드백 남겼습니다~ 확인해주세요 :)

2021-06-22 14:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/service/dto/BoardUpdateRequest.java
> +    private Long memberId;
이 필드도 jwt로 바뀌어야겠네요~

2021-06-22 14:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/controller/BoardController.java
> +    @PutMapping(value = "/boards/{boardId}")
"/boards" 도 공통으로 빼도될 것 같아요~

2021-06-22 14:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +    private Member saveMember(CreateMemberRequest createMemberRequest) {
혹시 동시성 이슈 때문에 따로 메서드로 추출하신걸까요?

개인적으로 코드내에서 try-catch 사용하는 것을 별로 안좋아하는데요.
`ALREADY_EXIST_MEMBER_ALIAS` 메세지를 전달하는 것이 목적이라면 `DataIntegrityViolationException` 전용 ExceptionHandler를 만드는게 어떨까요?
(이 부분은 취향 문제이기 때문에 꼭 반영하실 필요는 없습니다~)

2021-06-22 14:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +    private Member saveMember(CreateMemberRequest createMemberRequest) {
아 삭제된 회원에 대한 alias 문제로 추가하신걸로 보이네요.
어쨋든 유니크 제약 조건에 대한 처리문제이니 위 피드백 내용에 대해 한번 고민해보면 좋겠네요.

2021-06-22 14:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +        if (!memberRepository.existsById(memberId)) {
회원정보를 조회할 필요가 있나 싶어요.
삭제랑 비슷한 맥락인데, `Board` 도메인에서 수정 권한이 있는지 회원 식별자 값으로만 비교해도 충분하다고 생각합니다.

이 [리뷰](https://github.com/kodesalon/project/pull/53#discussion_r654952443) 내용 참고하세요~

2021-06-22 14:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/domain/Board.java
> +    public void updateTitleAndContent(Title updateTitle, Content updateContent) {
도메인에서 수정할 수 있는 권한 체크가 필요해보이네요~

2021-06-22 14:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/service/dto/BoardUpdateRequest.java
> +    @Length(max = CONTENT_LENGTH_BOUND_MAX, message = INVALID_BOARD_CONTENT)
`updatedTitle` 필드에 있는 `@Length`에 max 인자 이름의 형식을 통일시켜주면 좋겠네요.
* TITLE_LENGTH_MAX_BOUND
* CONTENT_LENGTH_BOUND_MAX

2021-06-22 14:48 UTC, seonghun127 commented on src/main/resources/static/docs/kodesalonApi.html
>  <!DOCTYPE html>
이 문서는 뭔가요?

2021-07-07 08:26 UTC, seongbeenkim commented on src/main/resources/static/docs/kodesalonApi.html
>  <!DOCTYPE html>
해당 부분은 게시판 전용 api 문서이었는데 하나의 api문서로 통합해주면서 삭제하였습니다!

2021-07-07 09:08 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/service/dto/BoardUpdateRequest.java
> +    private Long memberId;
해당 부분 jwt 적용으로 제거 되었습니다~

2021-07-07 09:09 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/controller/BoardController.java
> +    @PutMapping(value = "/boards/{boardId}")
넵넵 공통으로 빼주었습니다~

2021-07-09 05:49 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +    private Member saveMember(CreateMemberRequest createMemberRequest) {
try-catch 문을 사용하지 않게 되면 다른 Entity에서 `DataIntegrityViolationException`가 발생할 경우 처리하지 못하는 문제가 있을 수 있기 때문에 try-catch문을 사용해서 처리하였습니다.

2021-07-09 06:30 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +        if (!memberRepository.existsById(memberId)) {
넵넵 @Login 어노테이션 적용함으로써 인증된 회원 식별 번호를 받아오게하고
해당 식별 번호로 수정 권한이 있는 지 확인하게 함으로써 DB 조회하지 않게 수정하였습니다!

2021-07-09 06:30 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/domain/Board.java
> +    public void updateTitleAndContent(Title updateTitle, Content updateContent) {
해당 부분 회원 식별 번호를 인자로 받아 권한 확인 후 수정 가능하도록 변경하였습니다!

2021-07-09 06:43 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/service/dto/BoardUpdateRequest.java
> +    @Length(max = CONTENT_LENGTH_BOUND_MAX, message = INVALID_BOARD_CONTENT)
`MAX_BOUND`로 통일했습니다!!

2021-07-12 12:33 UTC, sefide approved these changes
코드가 빠르게 통일성을 가지게 되는 것 같아요 ! 👍🏼  
남긴 코멘트가 간단한 내용이라 바로 어프드립니당.

2021-07-12 17:12 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/service/dto/BoardUpdateRequest.java
> +    private String updatedTitle;
넵넵 이미 클래스명에서 `update`라는 내용이 들어가 있으니
한번 더 명시를 안해줘도 될 것 같네요! 해당 부분 수정하겠습니다 :)

2021-07-28 15:33 UTC, seonghun127 approved these changes
`MemberBoardService`가 제거됐군뇨. 고생하셨습니다. 순환참조때문에 꽤나 고생하신 것 같은데 많은 배움이 있었길 바랍니다.
몇가지 피드백 남겼고 PR이 오래돼서 미리 approve 할게요~

2021-07-28 15:33 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/domain/Board.java
> +    private void validateDateTime(final LocalDateTime deletedDateTime) {
날짜 정보만 null 체크하는 이유는 무엇인가요?
이 메서드를 사용하는 곳을 보니 엔티티 정보 수정하는 부분인데요. 다른 파라미터에 대한 null 검증은 없는데 날짜 정보만 null 체크하는 이유가 궁금합니다~

2021-07-28 15:33 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +    public Member findById(final Long memberId) {
readonly `@Transactional` 을 붙여주면 좋겠네요~

2021-07-28 15:33 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +    public Member findById(final Long memberId) {
그 밑에 `findMemberByAlias()` 메서드에도 붙여주면 좋겠군뇨.

2021-07-30 02:59 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/domain/Board.java
> +    private void validateDateTime(final LocalDateTime deletedDateTime) {
앗.. 특별한 이유는 없습니다.. 
dto에서 null체크, 타입체크 해주기 때문에
도메인에서 null체크하는 부분 제거해주었습니다!!

2021-07-30 02:59 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +    public Member findById(final Long memberId) {
넵넵 붙여주었습니다~!

2021-08-01 11:54 UTC, seonghun127 approved these changes
다시 Approve!

2021-08-01 12:19 UTC, merged