Feature/#22/게시물 조회 기능 구현
kodesalon/project pull request #55
Opened 2021-06-20 06:39 UTC by seongbeenkim

### 개요
- 이슈 번호 : #22
- 내용 : 게시물 조회 기능 구현

### 작업 사항
- 게시물 단일, 복수 조회 기능 구현

### 기타
-

2021-06-23 15:48 UTC, seonghun127 requested changes
몇몇 커밋의 prefix가 24로 되어있는거 같아요. 해당 커밋의 작업 내용 확인하면서 리뷰 남겼는데 혹시 놓친 부분이 있거나 이번 PR의 작업 내용이 아닌데 피드백을 남긴 부분은 말씀해주세요. 그리고 이 부분에 대해 추가 피드백을 받고 싶다 하는 부분이 있다면 코멘트 달아주세요~

2021-06-23 15:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/service/dto/BoardSelectSingleResponse.java
> +    private String createdDateTime;
날짜타입을 문자열로 내려주는 이유가 있을까요?
이 부분 때문에 `Board` 엔티티에서 `createdDateTime` 필드의 getter에서 `toString()`을 사용하게되는거 같은데요.
`LocalDateTime`으로 내려줘도 되지 않을까요?

2021-06-23 15:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/controller/BoardController.java
> +    public ResponseEntity<BoardSelectMultiResponse> selectBoards(@PageableDefault(sort = "board_id", direction = Sort.Direction.DESC) final Pageable pageable) {
페이지 조회 방식으로 구현하기로 결정된 것인가요?
`Pageable` 사용하는 것도 좋은데, 더보기 방식도 고려해봤으면 좋겠습니다~

2021-06-23 15:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/controller/BoardController.java
> +    public ResponseEntity<BoardSelectMultiResponse> selectBoards(@PageableDefault(sort = "board_id", direction = Sort.Direction.DESC) final Pageable pageable) {
참고로 innoDB에선 데이터가 PK기반으로 클러스터링 되어 있어 자동으로 board_id 기반으로 정렬돼서 조회될거에요~ (물론 오름차순 - ASC으로 정렬될거라 DESC는 명시해줘야겠네요.)

2021-06-23 15:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +        return new BoardSelectSingleResponse(board.getTitle(), board.getContent(), board.getCreatedDateTime(), board.getWriter());
조회한 엔티티를 DTO로 변환하는 과정 중 `board.getWriter()`에서 지연로딩이 발생되어야하는데 session(entity manager)가 없어서 에러가 발생하고 있습니다~
`writer`의 `name`을 바로 가져와야한다면 조인 쿼리를 날리는게 더 나아보이네요. QueryDsl을 적용해야하는 시기가 슬슬 다가온거 같네요 :)

2021-06-23 15:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +        Page<Board> boards = boardRepository.findAll(pageable);
여기서 지금 에러가 발생하고 있습니다.
어플리케이션을 띄우고 직접 API 콜해보시면 확인해볼 수 있습니다.

2021-06-23 15:48 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/board/controller/BoardControllerTest.java
> +                                beneathPath("content"),
이런게 있군뇨 👍

2021-06-23 15:48 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/board/controller/BoardControllerTest.java
> +                                fieldWithPath("writer").type(JsonFieldType.STRING).description("게시물 작성자 별명")
제가 정확히 기억이 안나는데 `Page` 로 내려주는 응답에 필드로 페이지 관련 필드들이(`현재 페이지 번호`, `다음 페이지에 데이터가 존재하는지`, `전체 페이지 수` 등) 여럿 존재하는 것으로 아는데요.
페이지 방식으로 전체 조회를 하기로 했다면 해당 데이터들도 같이 API문서로 정리해야하지 않을까요?

2021-06-23 15:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/domain/Board.java
> +    private boolean deleted;
여기 `@Column` 어노테이션이 필요해보이네요.

2021-06-24 13:17 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/controller/BoardController.java
> +    public ResponseEntity<BoardSelectMultiResponse> selectBoards(@PageableDefault(sort = "board_id", direction = Sort.Direction.DESC) final Pageable pageable) {
두번째 코멘트를 다시 읽어보니 좀 이상하게 말을 했네요. 어찌됐던 PK기반 내림차순 정렬로 페이지 조회한다는 것이니 둘다 명시하는 것이 맞습니다. 클러스터링 인덱스에 설명하려다보니 뭔가 말의 앞뒤가 안맞는 느낌으로 코멘트를 달았네요.
무시하시고 첫번째 코멘트에 집중하시면 될 듯 합니다. 😂

2021-06-24 13:20 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/board/controller/BoardControllerTest.java
> +                                fieldWithPath("writer").type(JsonFieldType.STRING).description("게시물 작성자 별명")
응답값이 아래와 같네요.
이중 클라아언트에게 필요한 정보가 있을터이니 해당 필드를 API 문서로 정리하는게 맞아보이네요.
![image](https://user-images.githubusercontent.com/30451129/123269748-3b05fe00-d53a-11eb-9ca1-89e6c61de489.png)

2021-06-24 13:21 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/domain/Board.java
> +    private boolean deleted;
추가로 `@Column` 어노테이션의 사용될 속성 값들도 같이 명시해주면 좋겠습니다~

2021-07-12 05:58 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +        return new BoardSelectSingleResponse(board.getTitle(), board.getContent(), board.getCreatedDateTime(), board.getWriter());
Select 방식으로 조회시 Fetch Join을 사용하여 Writer와 함께 조회하도록 변경하였습니다. 또한, `@Transactional` 을 사용해서 entity manager가 없는 에러가 나지 않도록 수정하였습니다!

2021-07-12 06:50 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +        Page<Board> boards = boardRepository.findAll(pageable);
Pageable을 사용할 때 sort의 속성을 테이블 컬럼 명으로 사용해서 문제가 발생했습니다. 객체의 속성 이름을 사용하도록 변경하도록 변경하여 해결하였습니다. 이후에는 더보기 방식으로 다시 변경할 예정입니다!

2021-07-12 06:53 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/board/domain/Board.java
> +    private boolean deleted;
`@Column` 어노테이션을 사용하여 속성값을 명시하도록 변경하였습니다.

2021-07-15 14:05 UTC, sefide requested changes
리뷰하면서 게시물 다중 조회 시 반환 데이터에 대해 궁금한게 있습니다 !

현재 반환 데이터는 게시물 리스트만 내려주고 있는데요. 
FE에서 해당 api 호출 시 `다음 페이지에 데이터가 존재하는지`는 어떻게 확인하나요? 현재는 해당 데이터를 따로 내려주고 있지 않기 때문에 FE쪽에서 내려오는 `리스트 사이즈`로 판단하거나 혹은 `전체 데이터 개수`와 같은 데이터가 필요할 것 같네요 !
`다음 페이지에 데이터가 존재하는지` 확인하는 방식에 따라 반환 데이터가 변경될 필요가 있어보여요.

2021-07-15 14:23 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +        List<Board> boards = boardRepository.findTop10By(lastBoardId);
넵넵 이 부분 `limit` 인자받도록 수정하겠습니다!!

> 현재 반환 데이터는 게시물 리스트만 내려주고 있는데요.
> FE에서 해당 api 호출 시 `다음 페이지에 데이터가 존재하는지`는 어떻게 확인하나요? 현재는 해당 데이터를 따로 내려주고 있지 않기 때문에 FE쪽에서 내려오는 `리스트 사이즈`로 판단하거나 혹은 `전체 데이터 개수`와 같은 데이터가 필요할 것 같네요 !
> `다음 페이지에 데이터가 존재하는지` 확인하는 방식에 따라 반환 데이터가 변경될 필요가 있어보여요.

`반환되는 결과 리스트 사이즈`로 다음 페이지에 데이터가 존재하는지 확인하도록 구현하였습니다! 

1. `page size`를 10으로 항상 클라이언트에서 요청
2. 게시물이 10개 이상일 경우 10개의 리스트 반환 -> 더보기 가능 
2-1. 게시물이 10개 미만일 경우 10개 미만의 리스트 반환 -> 더보기 불가능

2021-07-28 16:29 UTC, seonghun127 requested changes
몇몇 추가 피드백 남겼습니다. 조금 고민이 필요해보이는 부분이 있어서 Approve는 하지 않을게요.
확인부탁드려요~

2021-07-28 16:29 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/repository/BoardRepositoryImpl.java
> +@Repository
제거해도 되는 어노테이션입니다~

2021-07-28 16:29 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/repository/BoardRepositoryImpl.java
> +    private EntityManager em;
어노테이션 주입말고 생성자 주입으로 변경하는건 어떨까요?
항상 클래스를 선언할 땐 생성자를 명시해주는게 좋다고 생각해요. 지금 이 클래스는 spring 프레잉워크에 종속적인 클래스이지만 POJO일 때를 항상 고려하셨으면 합니다.

2021-07-28 16:29 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/board/repository/BoardRepositoryTest.java
> +        boards.forEach(b -> {
람다 로직이 한줄이면 중괄호는 제거하는게 좋아보여요~

2021-07-28 16:29 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/repository/BoardRepository.java
> +    Optional<Board> selectBoardById(@Param("boardId") Long boardId);
사용처가 테스트코드밖에 없습니다.
아무래도 아래 코드에 적용해야겠죠?
`com.project.kodesalon.model.board.service.BoardService#selectBoard`

2021-07-28 16:29 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/repository/BoardRepositoryImpl.java
>      public List<Board> selectBoards(final Long lastBoardId, final int size) {
코드 중복을 좀 더 줄여볼 수 있을 것 같아보이는데요. 이 부분은 여유가 되면 시도해보시면 좋을 것 같아요.
그렇다고 코드가 엄청 깔끔해질진 모르겠네요.
이를 언급하는 이유는 나중에 query dsl를 적용하면 되게 깔끔해질 것으로 보이는데요, 그전에 지금 `EntityManager`로 jpql를 짜는 방식이 Query Dsl에선 어떤식으로 개선됐는지 몸소 체험해볼 수 있을 것 같아서 입니다.

2021-07-28 16:29 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/controller/BoardController.java
> +    public ResponseEntity<List<BoardSelectResponse>> selectBoards(@RequestParam @Nullable final Long lastBoardId, @RequestParam final int size) {
더보기 방식을 적용한 API인거죠?
더보기 방식에 대해 좀더 고민을 해볼 필요가 있어보입니다.
@sefide 님께서 comment에 남겨주신 FE에서 다음 더 조회할 데이터가 있는지 알 수 있는 여부를 같이 내려주면 좋을 것 같아요.
그래야 불필요하게 서버에 요청을 보내는 일을 줄일 수 있을 것입니다. 참고로 추가 쿼리가 발생하지 않고 해당 정보(데이터가 더 있는지)를 조회하는 방법으로 고민해보면 좋을 것 같아요~

2021-07-30 03:20 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/repository/BoardRepositoryImpl.java
> +@Repository
접미사로 Impl를 붙여줄경우 `Repository`가 자동적으로 할당되는지는 몰랐네요!
수정해주었습니다

2021-07-30 03:24 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/repository/BoardRepositoryImpl.java
> +    private EntityManager em;
넵넵!
저번에 @Value 관련으로 같은 피드백 주셨었는데, 적용하지 못헀네요.ㅠㅠ 수정하였습니다!

2021-07-30 03:25 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/board/repository/BoardRepositoryTest.java
> +        boards.forEach(b -> {
넵넵 제거해주었습니다~!

2021-07-30 03:27 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/repository/BoardRepository.java
> +    Optional<Board> selectBoardById(@Param("boardId") Long boardId);
앗.. 만들어놓고 적용을 해주지 않았네요
적용하였습니다!

2021-07-30 04:56 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/repository/BoardRepositoryImpl.java
>      public List<Board> selectBoards(final Long lastBoardId, final int size) {
최초 다중 게시물 조회 시,
가장 마지막 게시물 번호가 무엇인지 모르기 때문에 `lastBoardId  = MAX_VALUE`로 설정해줌으로써 
하나의 쿼리로 모두 동작하게 하였습니다!

2021-07-30 06:47 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/controller/BoardController.java
> +    public ResponseEntity<List<BoardSelectResponse>> selectBoards(@RequestParam @Nullable final Long lastBoardId, @RequestParam final int size) {
``` JAVA
@Getter
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class MultiBoardSelectResponse {
    private List<BoardSelectResponse> boards;
    private boolean hasNext;

    public MultiBoardSelectResponse(final List<BoardSelectResponse> boards) {
        this.boards = boards;
        this.hasNext = hasNextBoard(lastBoard());
    }

    private BoardSelectResponse lastBoard() {
        return boards.get(boards.size() - 1);
    }

    private boolean hasNextBoard(final BoardSelectResponse boardSelectResponse) {
        return !boardSelectResponse.checkLast();
    }
}
```

`MultiBoardSelectResponse` 클래스 생성하여
더 조회할 데이터가 있는지 알려주는 필드 추가해주었습니다

2021-08-02 14:30 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/service/dto/MultiBoardSelectResponse.java
> +        return boards.subList(0, size);
이 부분은 `last`가 아닌 경우 마지막 데이터를 제거하는 로직으로 보이는데요.
결국 마지막 데이터 여부를 파악하고 그에 따라 마지막 데이터를 제거하던지 그대로 반환하던지 차이일텐데
그렇다면 빠른 시간 복잡도로 마지막 데이터만 제거할 수 있는 자료구조를 사용해보는건 어떨까요?

2021-08-03 12:57 UTC, sefide requested changes
몇 가지 질문같은 코멘트 남겼습니다 ~! 
확인이 필요할 것 같아 request change 했습니다

2021-08-03 12:57 UTC, sefide commented on src/main/java/com/project/kodesalon/model/board/service/dto/BoardSelectResponse.java
> +    public boolean checkLast() {
이 메소드의 용도는 무엇인가요? 사용되지 않는 메소드라면 지워주세요 : )

2021-08-04 08:28 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +        return boardRepository.selectBoardById(boardId)
`selectBoard()`는 `member`를 사용하기 때문에 fetch join(`selectBoardById`)하게 그대로 두었으며, 
나머지 `updateBoard`, `delete`, `save` 등 `member`를 사용하지 않는 곳에서는 기본 `findById`를 사용하였습니다

2021-08-04 08:28 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/board/repository/BoardRepositoryTest.java
> +        boards.forEach(board -> softly.then(persistenceUnitUtil.isLoaded(board.getWriter())).isTrue());
앗.. 수정하였습니다~!

2021-08-05 03:44 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/board/service/dto/MultiBoardSelectResponse.java
> +    public boolean isLast() {
넵!! `BoardService` 에서 마지막 게시물 여부를 계산하고 초기화하는 방식으로 수정하였습니다.

2021-08-05 03:47 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/board/service/dto/MultiBoardSelectResponse.java
> +        this.last = isLastBoard();
저도 `hasNext` 가 더 명확한 네이밍이라고 생각했습니다. 하지만  getter 메서드의 이름이 `isHasNext` 로 네이밍을 해야 해서 필드를 `last`로 하고 메서드 네임을 `isLast`로 가져가는 것이 더 좋은 네이밍이라고 판단했습니다.

> 추가로 위 피드백을 반영하지 않더라도 boolean 타입의 네이밍 컨벤션으로 바꿔주는건 어떨까싶어요~

이 부분은 혹시 `last` 변수를 isLast 변경하는 것이 좋다는 피드백으로 이해해도 괜찮을까요??

2021-08-05 03:51 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/board/service/dto/MultiBoardSelectResponse.java
> +        return boards.subList(0, size);
이 부분도 `EntityManager` 에서 데이터를 조회 후에 `Deque` 자료 구조를 활용하여 반환하도록 수정하였습니다. 이 부분을 수정하면서 궁금한 점이 `EntityManager`에서 `List`로 반환된 자료구를 `Deque` 로 초기화 하게 되면 `subList`를 사용하는 것과 동일한 시간 복잡도를 가지게 되는데 혹시 더 좋은 방법이 있는지 궁금합니다!

2021-08-05 04:13 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/board/repository/BoardRepositoryImpl.java
> +        String query = "select b from Board b join fetch b.writer where b.id < :lastBoardId and b.deleted = false order by b.id desc";
> `lastBoardId` 가 docs에서는 마지막으로 조회_한_ 게시물 식별 번호라고 되어 있는데
> 지금 쿼리 봐서는 마지막으로 조회_할_ 식별 번호인 것 같아요!

지금 쿼리를 확인해보고 테스트 해 봤을 때 마지막으로 조회한 게시물의 식별번호를 받아서 다음 게시물을 잘 조회하는 것 같습니다. 가장 최근 게시물에 올라온 게시물 순으로 조회하기 위해서 board_id를 기준으로 역순으로 정렬해서 데이터를 조회하도록 구현하였습니다.

> 시작점이 아니라 마지막 게시물 번호를 기준으로 조회하도록 한 이유가 있을까 궁금합니다 ~

`lastBoardId`의 다음 값 부터 size만큼 조회하도록 쿼리를 작성하였습니다!!

2021-08-05 04:18 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/model/board/service/dto/BoardSelectResponse.java
> +    public boolean checkLast() {
> 이후 커밋으로 인해 중괄호가 다시 생겼네요

이 부분은 다시 반영하였습니다 :) 

> 이 메소드의 용도는 무엇인가요? 사용되지 않는 메소드라면 지워주세요 : )

원래는 마지막 게시물인지 여부를 체크하기 위해 메서드를 만들었지만 다른 방식을 사용해서 해당 메소드를 지우는 것을 깜빡했습니다. 바로 반영하겠습니다!

2021-08-08 05:38 UTC, seonghun127 requested changes
리뷰가 늦었네요; 몇개 코멘트 남겼습니다~
오늘 스터디시간 (8/8)에 이야기해봐도 좋아요~

2021-08-08 05:38 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/repository/BoardRepositoryCustom.java
> +    Deque<Board> selectBoards(final Long lastBoardId, final int size);
`Deque` 자료구조를 사용하셨군뇨. `Deque` 자료구조는 생각해보지 못했네요 👍
제가 의도한 것은 기존에 `List` 자료구조였으니 마지막 요소(Element)를 제거하는 API를 제공해주는 `LinkedList`를 것이었습니다.
즉, Repository에서의 반환타입에는 변경이 없고 마지막 요소를 제거해야하는 "부분"에서 `LinkedList`를 사용하면 어떨까라는 생각을 했습니다. 그게 변경이 적을거라 생각했거든요.
이 메서드는 `entityManager`의 `getResultList()`가 반환하는 `List`로 변경하는게 더 좋아보여요. 마지막 요소를 제거하는 로직에서 사용하지 않을 수 있는데 매번 `Deque`로 복사할 필요는 없으니까요.

2021-08-08 05:38 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +
65번째 줄부터 69번째 줄까지의 로직이 여기 있을 필요가 있을까요?
이를 계산하는 역할을 DTO 생성자에게 위임하는게 어떨까요?

2021-08-08 05:38 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/service/dto/MultiBoardSelectResponse.java
> -        return last;
위 로직들을 제거한 이유가 무엇인가요?
이 로직은 Service의 책임이라 생각하신건가요?

2021-08-08 05:41 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/service/dto/MultiBoardSelectResponse.java
> +        return boards.subList(0, size);
그러네요. 복사해야하는 생각까진 고려하지 못했습니다;
결국 어떤 자료구조를 사용하던 새로운 자료구조를 사용한다면 복사비용이 드네요. 시간복잡도 장점은 못가져갈 듯 싶네요.
그래도 마지막 요소를 제거한다는 API를 제공하는 자료구조를 사용하는게 코드를 읽을 때 더 잘 읽힐 것 같습니다~

2021-08-08 05:45 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/service/dto/MultiBoardSelectResponse.java
> +        this.last = isLastBoard();
이 부분도 생각못했네요.
사실 DTO에 대한 테스트를 코드를 안짜는데요. (로직을 갖고 있지 않다면 개인적으로 필요치 않다라고 생각해요. 그렇다고 짜는게 안좋다는건 아닙니다.)
그래서 `hasNext` 라는 네이밍을 가져갔을 때 getter 메서드의 이름을 고려해보지 않았네요. 사용처는 오로지 직렬화 시점이었어서...
`last`로 가도 괜찮아보이네요.

---

추가로 boolean 타입의 네이밍은 앞에 동사를 붙이는걸로 알고 있어서요. 그래서 `isLast` / `hasNext`를 말씀드린 거 였습니다.

2021-08-09 13:27 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/service/dto/MultiBoardSelectResponse.java
> +        this.last = isLastBoard();
해당 부분 `MultiBoardSelectResponse`에서 `last` -> `isLast`로 이름 수정하였으며,
`isLast`가 `last`로 직렬화로 되기 때문에 `BoardControllerTest` api 문서 작성 코드에는 `last` 그대로 유지하도록 하였습니다!
```java
fieldWithPath("last").type(JsonFieldType.BOOLEAN).description("마지막 게시물 여부")
```

2021-08-09 14:16 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/repository/BoardRepositoryCustom.java
> +    Deque<Board> selectBoards(final Long lastBoardId, final int size);
넵넵 `Repository`에서의 반환은 `List` 그대로 가져가주는게 좋은 것 같습니다!

MultiBoardSelectResponse에서
`Deque`, `LinkedList` 모두 `List`를 복사하는데 있어서 똑같은 비용이 든다고 생각하지만, 
말씀해주신 것처럼 deque.`pop()` 보다 마지막 요소를 제거해준다는 의미에 있어서 linkedList.`removeLast()` 가 더 가독성이 좋아보여 `LinkedList`로 수정해주었습니다!

2021-08-09 14:36 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/board/service/BoardService.java
> +
넵넵 이 부분 생성자에 옮겨주었습니다!

2021-08-10 14:43 UTC, sefide approved these changes
성훈님께서 좋은 리뷰 남겨주셔서 자료구조에 대해 좀 더 공부가 되셨을 것 같아요. 저도 같이 공부가 되었네요!  이번 PR은 여기까지로 어프드릴게요. 추후에 `MultiBoardSelectResponse`와 같이 리스트 조회가 필요하게 될 때 제네릭을 사용해서 일관성있게 데이터를 내려주는 것을 연습해봐도 좋을 것 같아요.

2021-08-10 14:43 UTC, sefide commented on src/main/java/com/project/kodesalon/model/board/service/dto/MultiBoardSelectResponse.java
> +    private List<BoardSelectResponse> removeLastIfOverloaded(final List<BoardSelectResponse> boards) {
메소드명이 명확해서 좋네요 👍🏽

2021-08-19 14:16 UTC, seonghun127 approved these changes
리뷰가 꽤 길었네요; Approve 하겠습니다~
@sefide 님이 말씀해주신 것처럼 `MultiBoardSelectResponse` 클래스는 Generic을 사용해서 공통으로 사용할 수 있도록 리펙토링해보는 것도 좋아보입니다. 한번 고려해보세요!

2021-08-19 14:16 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/service/dto/MultiBoardSelectResponse.java
> +    private boolean checkLast(final List<BoardSelectResponse> boards, final int size) {
보통 `boolean` 타입을 반환한다면 메서드명이 `is/can`로 시작하도록 명명해줍니다.
`check`, `validate` 등으로 시작하는 메서드들은 대부분 유효성 검증에 사용되며 `void` 반환타입을 가져요. 내부에선 유효하지 않다고 판단될 때 throw를 하고요.

2021-08-19 14:16 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/board/service/dto/MultiBoardSelectResponse.java
> +        return boardSelectResponses;
불변 리스트로 반환하는건 어떨까요?
내부에서 이미 `LinkedList`로 복사하고 있어 데이터 복사가 여러번 일어나는게 조금 애매하다고 생각이 되어지지만 한번 고려해볼 필요가 있어보이네요~

2021-09-11 18:15 UTC, merged