Feature/#57/jwt 적용
kodesalon/project pull request #58
Opened 2021-07-02 08:24 UTC by seongbeenkim

### 개요
- 이슈 번호 : #57 
- 내용 : JWT 적용

### 작업 사항
- JWT, Cors 적용
- Interceptor, ArgumentResolver 구현

### 기타
- Board(게시판) 같은 경우에는 develop 브랜치에서 Member(회원)과 연결이 되어 있지 않아 JWT 적용을 하지 않았으며, 해당 부분은 다른 브랜치에서 수정하도록 하겠습니다!
- WebConfig에 대해서는 테스트 코드를 작성하지 못했습니다. 혹시 WebConfig은 어떻게 테스트 코드를 작성해야 하는 지 조언해주실 수 있으실까요?

2021-07-07 16:16 UTC, seonghun127 requested changes
jwt를 직접 구현하시느라 정말 고생많았습니다. 👏👏👏
몇가지 피드백 남겼으니 확인부탁해요~

추가로 이야기해보면 좋을 내용도 남겨봅니다.
`RefreshToken`을 DB에 저장해야하는지에 대한 내용인데요. 기한이 만료된 refresh token은 더이상 의미없는 데이터가 되고 마는데요. 이를 영구히 저장해놓을 필요가 전혀 없어보입니다. 로그도 그런 차원에 DB에 저장하지 않죠. (물론, 로그성 도메인 데이터를 DB에 저장하긴 하는데 이는 시간이 지나도 통계나 히스토리 검색 목적으로 사용되는 경우가 있어 refresh token 보단 사용성이 있습니다. 그리고 이런 경우 DB 파티셔닝을 이용해서 관리합니다.)
데이터의 생명주기가 상대적으로 짧고 생명이 다했을 때 더이상 유의미하지 않다면 이는 지속적 삭제가 요구되는데요. DB에 저장했던 많은 데이터를 (아마 이는 사용자와 1:N 로 생성되는 데이터가 되겠죠?) 다시 삭제하는 것도 비용입니다.
Redis와 같은 캐시 스토리지를 사용하는 것을 추천드려요. 캐시는 데이터의 저장 기간을 같이 설정할 수 있어 시간이 만료되면 자동으로 삭제됩니다. 이는 나중에 Advanced로 빼서 작업해도 좋아보이네요. Redis는 현업에도 정말 많이 사용되기 때문에 경험을 쌓으면 분명 도움이 되는 라이브러리입니다.

2021-07-07 16:16 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/common/interceptor/LoginInterceptor.java
> +        request.setAttribute(LOG_ID, uuid);
요청 헤더에 LogId를 설정해주는 이유가 무엇인가요?
현재 사용처를 보니 이 인터셉터에서 요청 전, 후에 로그를 찍는 데만 사용이 돼보이네요.
혹시 요청을 처리하는 동일 스레드가 남긴 로그임을 확인하기 위해서라면 `MDC` 개념을 찾아보면 좋을 거 같습니다.

2021-07-07 16:16 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/common/interceptor/LoginInterceptor.java
> +    public void afterCompletion(HttpServletRequest request, HttpServletResponse response, Object handler, Exception ex) throws Exception {
`postHandle()`이 아닌 이 메서드를 구현한 이유는 무엇인가요?

2021-07-07 16:16 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/authentication/service/AuthenticationTokenService.java
> +                        }
로그인 시마다 refresh token을 갱신하는 이유는 무엇인가요?
최초 저장은 필요할 수 있겠지만 그 이후에는 불필요한 DB I/O가 발생하는 걸로 보여저서요.

2021-07-07 16:16 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/common/config/WebConfig.java
> +                .allowedOrigins(serverUrl);
이 부분은 serverUrl로 설정해야하나요?

2021-07-07 16:18 UTC, seonghun127 commented
참고로 커밋수가 많아서 2차 피드백을 또 드릴 수도 있습니다. 한번에 다 할려고하니 쉽지 않아서 분명 빼먹은 부분들도 있을거에요. 다음에 다시 살펴보면서 추가로 남길 피드백이 있다면 또 남겨놓겠습니다. :)

2021-07-08 03:55 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/common/JwtUtils.java
> +    private long accessExpirationMs;
토큰과 관련된 정보는 중요한 정보라고 생각했습니다.
그렇기 때문에 토큰 비밀 키, 액세스, 리프레스 만료 시간을 감추는 것이 좋다고 생각하여 yaml을 통해 주입받는 방식으로 하였습니다.
현재 로컬 yaml, 운영 EC2 서버 내 yaml이 따로 존재하여 
로컬에서는 로컬테스트용 토큰 정보 값, 운영 서버에는 운영용 토큰 정보 값을 담고 있는데
상수로 모두 빼주는게 나은건가요?

2021-07-08 03:56 UTC, seongbeenkim commented on src/main/resources/application.yml
> +    accessExpirationMs: 60000
https://github.com/kodesalon/project/pull/58#discussion_r665851400
해당 부분 위에서 말씀드린것과 같이 로컬용으로 설정한 값입니다!
실제 운영 서버용 yaml에서는 더 긴 시간으로 설정되어 있습니다!

2021-07-08 03:57 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/common/interceptor/LoginInterceptor.java
> +        request.setAttribute(LOG_ID, uuid);
> 혹시 요청을 처리하는 동일 스레드가 남긴 로그임을 확인

넵 말씀하신 것처럼 동일 스레드의 로그를 남기기 위해서 한 부분으로 `MDC` 개념 공부하여 적용해보도록 하겠습니다!

2021-07-08 04:23 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/common/interceptor/LoginInterceptor.java
> +    public void afterCompletion(HttpServletRequest request, HttpServletResponse response, Object handler, Exception ex) throws Exception {
http 요청이 수행된 후 정보 + 에러 관련 정보를 확인하고 싶어서 `afterCompletion`을 구현하였습니다!

2021-07-08 04:39 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/authentication/service/AuthenticationTokenService.java
> +                        }
`Refresh Token`의 만료 기간이 2주일 경우

- 회원가입 후 최초 로그인 시에는 `Refresh Token` + `AccessToken` 모두 발급
- 이후 로그인 시에는 `Refresh Token` 확인 후 `Access Token`만 재발급을 해주며, 2주 만료가 될 때 `Refresh Token` 재발급해도 됩니다.

하지만 `Refresh token`이 탈취될 경우 해당 `Refresh token`의 2주 만료 기간이 다 할때까지 계속 `Access Token`을 재발급하여 로그인/서비스 이용을 할 수 있기 때문에 서버에서는 이러한 접속이 실제 사용자인지를 판단하지 못하게 되어 보안적인 이슈가 발생하게 된다고 합니다.
이러한 문제를 보완하기 위해서 한 번 사용한 `Refresh token`은 폐기 처리 후 재발급하는 방식을 많이 사용하고 있다고 하여 위와 같이 갱신하는 방식으로 변경을 해주었습니다.

말씀하신대로 불필요한 DB I/O가 발생한다는 단점이 있지만, 일단 trade off로 생각하여 보안적인 문제를 우선시 두어 위와 같이 개발을 하였습니다!

2021-07-08 04:39 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/common/config/WebConfig.java
> +                .allowedOrigins(serverUrl);
이 부분 안해줘도 될 것 같습니다😂 
수정하겠습니다!

2021-07-08 04:42 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/common/JwtUtils.java
> +public class JwtUtils {
넵넵 이 부분은 더 적합한 이름을 고민해보고 수정하도록 하겠습니다!

2021-07-08 04:48 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/authentication/service/AuthenticationTokenService.java
> +    private void validateExpiration(RefreshToken refreshToken) {
넵넵 맞네요! 해당 부분 도메인으로 옮기도록 하겠습니다~

2021-07-08 04:48 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/common/interceptor/LoginInterceptor.java
> +        String token = request.getHeader("Authorization").substring(BEARER_LENGTH);
해당 부분도 try, catch로 수정하도록 하겠습니다!

2021-07-08 04:49 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/service/dto/LoginResponse.java
> +    private String refreshToken;
프론트와 이야기를 했을 때, 안넣어줘도 괜찮지 않을까라고 이야기를 나누었었는데
이 부분 프론트와 다시 이야기하고 수정해주도록 하겠습니다!

2021-07-08 04:50 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/common/JwtUtils.java
> +    private long accessExpirationMs;
넵넵 맞네요 수정하겠습니다!

2021-07-08 05:05 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/authentication/service/AuthenticationTokenService.java
> +        validateExpiration(refreshToken);
`Access token`이 만료되었을 때 새로운 `Access token`을 발급받기 위한 상황에서 호출이 됩니다.

클라이언트가 `Refresh token`을 담아 서버 API(`/api/v1/auth/refreshtoken`)를 호출하면서 `refreshToken()`이 수행이 되는데
메서드가 성공적으로 수행됐을 경우 새로운 Access token + Refresh token을 발급해주며
실패했을 경우(만료 및 유효하지 않은 토큰) 로그인 요청 에러 코드를 보내게 됩니다!

refreshToken()의 의미는 `Access Token`을 재발급 받기 위한 메소드인데 이름을 더 명확하게 표현하게 수정해야겠다는 생각이 지금 듭니다! 이 부분도 수정하겠습니다.

2021-07-11 02:57 UTC, sefide requested changes
너무 늦은 리뷰 죄송합니다 🙏😭

전반적으로 jwt를 적용하기 위해 구조를 잘 잡으신 것 같아요.
jwt의 장점은 IO가 따로 필요없다는 것인데 AccessToken이 탈취될 수 있는 경우를 고려해서 refreshToken을 도입한게 인상적이네요. 몇가지 코멘트 남겼으니 확인 부탁드립니다 !

2021-07-11 02:57 UTC, sefide commented on src/main/java/com/project/kodesalon/model/authentication/controller/AuthenticationTokenController.java
> +    public ResponseEntity<JwtResponse> reissueAccessAndRefreshToken(@RequestBody @Valid final TokenRefreshRequest tokenRefreshRequest) {
`AccessToken`의 만료에 대해 연장을 요청하는 API로 보이는데 클라이언트가 해당 API를 호출하는 시점은 어떻게 될까요 ? 궁금해서 여쭤봅니다 ~

2021-07-11 10:48 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/common/JwtManager.java
> +                .claim("memberId", memberId)
넵넵 ! 해당 부분 상수화 해주었습니다!

2021-07-11 10:49 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/common/interceptor/LoginInterceptor.java
> +            log.error("afterCompletion error : ", ex.getMessage());
앗.. 해당 부분 `{}` 추가해주었습니다!

2021-07-11 10:49 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +        log.info("test22 {}", member.getId(), member.getAlias());
제대로 확인을 안했었네요ㅠㅠ 해당 부분 제거해주었습니다!

2021-07-11 10:52 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/service/MemberService.java
> +    public Member findById(final Long memberId) {
넵넵 맞습니다! 해당 부분 private으로 다시 수정해주었습니다!!

2021-07-11 11:03 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/authentication/domain/RefreshTokenTest.java
> +    private final LocalDateTime expiryDate = LocalDateTime.now();
오.. 고려를 해보지 않았었던 부분이었네요!
저희 프로젝트에서는 이슈가 없지만 추후 주말 등 공휴일과 관련된 로직이 추가될 경우 코멘트주신 부분처럼 적용해야겠네요!!
공유해주셔서 감사합니다~!

2021-07-11 11:15 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/authentication/controller/AuthenticationTokenController.java
> +    public ResponseEntity<JwtResponse> reissueAccessAndRefreshToken(@RequestBody @Valid final TokenRefreshRequest tokenRefreshRequest) {
https://github.com/kodesalon/project/pull/58#discussion_r665872231
1. 클라이언트에서 API 요청과 함께 Access Token을 전달할텐데 Access Token 유효성 검증 시 Access token이 만료되었다면, 
2. 서버는 요청된 API를 수행하지 않고 클라이언트에게 만료된 토큰에 대한 예외 코드(ex) J001)를 전달해줍니다. 
3. 클라이언트가 J001이라는 코드를 전달받을 경우, 새로운 Access token을 발급받기 위해서 Refresh token을 담아 해당 API를 호출하게 됩니다.

클라이언트가 Refresh token을 담아 서버 API(/api/v1/auth/refreshtoken)를 호출하면서 reissueAccessAndRefreshToken()이 수행이 되는데
메서드가 성공적으로 수행됐을 경우 새로운 Access token + Refresh token을 발급해주며
실패했을 경우(만료 및 유효하지 않은 토큰) 로그인 요청 에러 코드를 보내게 됩니다!여 

왜 refresh 까지 새로 발급을 받아야하지? 라는 생각을 하실 수 있는데 이 부분은 
https://github.com/kodesalon/project/pull/58#discussion_r665864067 에 남긴 댓글 확인해주시면 됩니다!

2021-07-11 14:03 UTC, sefide commented on src/main/java/com/project/kodesalon/model/authentication/controller/AuthenticationTokenController.java
> +    public ResponseEntity<JwtResponse> reissueAccessAndRefreshToken(@RequestBody @Valid final TokenRefreshRequest tokenRefreshRequest) {
클라이언트는 토큰 만료 예외 코드(ex) J001)를 통해 본인이 들고 있던 토큰이 만료했음을 인지하는것이군요. 
상세한 답변 감사합니다 !

2021-07-16 04:12 UTC, merged

2021-07-22 14:37 UTC, sefide reviewed
역할이 모호하거나 명확하지 않은 부분을 잡아내고 싶었는데 깔끔히 작성해주셔서 리뷰가 어렵네요 !
그래서 몇가지 간단한 코멘트만 남겼습니다~

추가적으로
1. Exception 관련 클래스는 따로 패키지를 분리하는게 어떨까요? `BaseEntity`나 `jwtManager`와 같은 패키지의 같은 레벨에 존재하니 어색하게 느껴지네요. 
2. WebConfig의 테스트에 대한 질문을 주셔서 (첫 리뷰 때 답변을 깜빡했네요 😭) 고민해봤는데 테스트용 config로 통합테스트는 진행해본적 있어도 config class에 대한 테스트는 따로 해본적이 없었던 것 같아요 :0 @seonghun127 님 좋은 방법이 있을까요?

2021-07-22 14:37 UTC, sefide commented on src/test/java/com/project/kodesalon/common/argumentresolver/LoginMemberArgumentResolverTest.java
> +    void supportsParameter() {
`DisplayName`에서 타입이 `Member`가 아니라 `Long`인 것 같아요~ 그리고 메소드명을 아래 supportParameter 테스트 메소드(line 62)와 같이 통일하는게 어떨까요 ?

2021-07-22 14:37 UTC, sefide commented on src/test/java/com/project/kodesalon/common/interceptor/LoginInterceptorTest.java
> +    public void afterCompletion() {
요 테스트만 따로 public으로 설정한 이유가 있을까요?

2021-08-08 06:40 UTC, seonghun127 reviewed
jwt 관련 피드백 드리는걸 한동안 잊고있다가 이제 리뷰남기네요.
별다른 코멘트를 남길게 없어보입니다. (1개 남겼는데 한번 확인해주세요~)
코드 퀄리티가 예전보다 많이 올라왔네요.

2021-08-08 06:40 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/authentication/service/AuthenticationTokenServiceTest.java
> +    void refreshToken_throw_exception_with_expired_token() {
이 테스트 코드는 없어도 될 것 같아요.
`validationExpiryDate()` 메서드가 도메인으로 이동하면서 이미 도메인 테스트 코드에서 관련 사항을 검증하고 있다고 생각합니다. `reissueAccessAndRefreshToken()`에선 `validationExpiryDate()` 메서드에서 예외가 발생하던 말던 신경쓰지 않고 있네요.

2021-09-16 19:03 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/common/JwtManager.java
> +
앗 리뷰 남겨주신 부분을 제가 확인하지 못했었네요ㅠㅠ 죄송합니다ㅠㅠ
줄바꿈 처리가 `JwtManager` 선언부 아래 한 줄 말씀하시는건가요??

그렇다면, 해당 부분 저와 다른 팀원이 선언하는 방식이 달라서 이 부분 관련 컨벤션 찾아봤지만 명확하게 제시한 글을 찾지 못해서 모든 클래스 한 줄씩 띄자라고 통일해준 부분이었는데 혹시 컨벤션에 위반되는 건가요?!
다른 개발자분들의 코드를 봐도 다 다르더라구요ㅠㅠ


> 1. Exception 관련 클래스는 따로 패키지를 분리하는게 어떨까요? `BaseEntity`나 `jwtManager`와 같은 패키지의 같은 레벨에 존재하니 어색하게 느껴지네요.


해당 부분 #70 브랜치에서 수정해주었습니다 :)

2021-09-16 19:04 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/common/JwtManager.java
> +        SignatureAlgorithm signatureAlgorithm = SignatureAlgorithm.HS256;
앗 enum을 가져와서 다시 저장하는 구조로 작성을 했었네요..
해당 부분 수정해주었습니다!

2021-09-16 19:08 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/common/argumentresolver/LoginMemberArgumentResolverTest.java
> +    void supportsParameter() {
그러네요! Long 타입으로 변경해주었고
테스트 메소드명도 변경해주었습니다 :)

2021-09-16 19:11 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/common/interceptor/LoginInterceptorTest.java
> +    public void afterCompletion() {
테스트 코드 자동 생성하면서 생긴 접근자로
모든 테스트 메서드 public 제거해주었습니다 :)

2021-09-16 19:16 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/authentication/service/AuthenticationTokenServiceTest.java
> +    void refreshToken_throw_exception_with_expired_token() {
그러네요 아래 코드처럼 도메인에서 예외를 던지게 해놓았는데 이미 도메인 테스트는 검증이 되어있고,
`reissueAccessAndRefreshToken()`에선 어떠한 처리도 해주지 않고 있네요!
``` java
willThrow(new JwtException(INVALID_JWT_TOKEN))
                .given(refreshToken)
                .validateExpiryDate(any(LocalDateTime.class));
```

해당 부분 제거해주었습니다!

2021-09-18 05:04 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/common/JwtManager.java
> +
이 부분은 따로 컨벤션이 없는 걸로 알고 있어요. 혹시 있다면 해당 컨벤션으로 지키고 따로 없다면 팀내 컨벤션을 정해서 통일만 시켜주면 좋을 것 같슴돠~