Feature/#67/base entity 적용
kodesalon/project pull request #69
Opened 2021-07-19 08:45 UTC by sdrs6921

### 개요
- 이슈 번호 : #67 base entity 적용
- 내용 : base entity 적용

### 작업 사항
- base entity 적용하기

### 기타
-

2021-07-29 12:50 UTC, seonghun127 requested changes
몇가지 피드백 남겼어요~ 확인부탁드려요!

추가로 로컬에서 DB 연동하실 때 application.yml을 변경해서 h2 -> mysql로 변경하고 work bench 이용해서 접근하시는 것 같은데 다른 방법도 있으니 공유해봅니다~
h2 DB를 tcp 서버로 열고 intellij database 툴에서 접근할 수 있습니다.
[이 글](http://homoefficio.github.io/2019/10/09/IntelliJ%EC%97%90%EC%84%9C-H2-%EC%97%B0%EA%B2%B0%ED%95%98%EA%B3%A0-JPA-Console-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0/) 참고하시면서 적용해보는 것도 좋아보여요~ flyway + docker + mysql 도입전까지 사용봐도 좋을 것으로 판단됩니다.
(물론 application 자체를 띄워야만 DB 접근이 가능할텐데요. 그리고 휘발성 메모리라 application을 종료하면 데이터가 모두 날라가는 단점이 있습니다.)

2021-07-29 12:50 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/common/BaseEntity.java
>      protected LocalDateTime deletedDate;
삭제 시간이 있는 이유는 무엇인가요?
`lastModifiedDateTime` 를 이용하면 되지 않을까요?
이 부분은 단순 궁금해서 여쭤봅니다~

2021-07-29 12:50 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
> +        this.createdDateTime = createdDateTime;
lastModifiedDateTime도 같이 초기화해주는건 어떨까요?

2021-07-29 12:50 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/member/service/dto/ChangePasswordRequestTest.java
> +    private final ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
이런 것도 있었군뇨. 👍
테스트 코드가 점점 더 풍부해지는 느낌이네요~

2021-07-29 12:50 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
>          if (hasSamePassword(newPassword)) {
이 메서드 관련해서 타고 가보다가 보니까 `Password` VO 가 `isSame()`이라는 메서드를 가지고 있는데 사용처가 없네요.
`equals()` 사용을 대체시키던지 지우던지 해야겠네요.

2021-07-29 12:50 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
> +        if (Objects.isNull(lastModifiedDateTime)) {
null 체크 로직에 대해 고민을 할 필요가 있어보여요.
java에선 NPE 가 상당히 거슬리면서 위험한대요. 이를 어떻게 관리할지 정해보면 좋을 것 같습니다.
철저하게 NPE를 피하기 위해 메서드로 넘어오는 모든 인자에 대해 null 체크를 한다던지 (엘레강트 오프젝트에서 이야기하는 것처럼) null 체크를 하지 않는다던지 또 다른 방식으로 처리한더던지...
분명 트레이드 오프가 있겠는데요.
전자를 택할 경우
* 장점 : NPE 위험을 상당 부분 줄일 수 있다.
* 단점 : 메서드 로직이 복잡해진다. (인자가 많아지면 많아질수록... null 체크도 비용이기에 귀찮은 부분이 많겠죠.)

후자를 택할 경우
* 장점 : 메서드 로직을 간결하게 유지할 수 있다.
* 단점 : NPE 위험이 높아진다. (클라이언트를 전적으로 믿는건 무슨 일이 일어날지 모르기에 위험한건 사실입니다.)

어떤 방향으로 가던지, 컨벤션을 정하고 코드 통일성을 유지하는게 바람직해보입니다~

2021-07-29 12:50 UTC, seonghun127 commented on src/test/java/com/project/kodesalon/model/member/service/MemberServiceTest.java
> -    public void changePassword() {
이 테스트코드 37번째 줄에서 객체 초기화하면서 줄바꿈이 일어나고 있는데, `=` 를 쓰고 그 다음 줄 바꾸는게 자바 컨벤션 아닌가요?
이제 발견한건데 확인해보면 좋겠어요~

2021-07-29 12:50 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/common/config/WebConfig.java
> +                .allowedMethods("*");
`allowedOrigins()`, `allowedMethods()` 모두 와일드카드로 열어둔다면 설정해주지 않아도 돼보입니다. (테스트를 해봤는데 해당 설정을 제거해도 같은 응답이 내려오네요.)
만약 명시해주고 싶다면 둘다 명시해주는 것도 좋아보이네요~

2021-07-30 07:23 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/common/config/WebConfig.java
> +                .allowedMethods("*");
말씀해주신 것처럼 
`allowedOrigins()`는 default `*`로 되어있어서 제거해주었고
`allowedMethods()`는 default `Allow "simple" methods GET, HEAD and POST.`로 되어 있어 모든 method 열어주기 위해 `*`로 설정해주었었습니다!

2021-07-30 07:28 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
> +        this.createdDateTime = createdDateTime;
생각해보니 생성도 수정과 연관이 있다고 생각하기 때문에, 초기화해주었습니다!

2021-07-30 07:38 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
>          if (hasSamePassword(newPassword)) {
`equals()`로 사용하기로 하였습니다!!

2021-07-30 07:41 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/model/member/domain/Member.java
> +        if (Objects.isNull(lastModifiedDateTime)) {
넵넵 모든 인자 null 체크할 시, 로직이 복잡해지고 프로젝트에서 DTO에서 Null 체크를 해주고 있기 때문에,
도메인 관련 객체에서는 Null 체크 하지 않는 방향으로 통일하기로 했습니다!!

2021-07-30 07:55 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/model/member/service/MemberServiceTest.java
> -    public void changePassword() {
앗.. 잘못 선언한 `=` 모두 수정해주었습니다!

2021-07-30 13:46 UTC, sefide requested changes
공통으로 사용하는 값에 대한 처리군요 ! 고생하셨어요👏🏼 
앞선 리뷰를 꼼꼼히 해주셔서 이리 저리 살펴보다.. 커밋 이력이 없는 부분이지만 해당 PR 내용과 관련이 있어보여 코멘트 남깁니닷 
- `Board`쪽 확인해보다가 게시물 삭제 날짜에 대한 null 체크는 그대로 있는것 같아서요 ! [날짜에 대한 null 체크 관련](https://github.com/kodesalon/project/pull/69#discussion_r679719246)해서 Dto에게 위임하기로 했다고 하셔서  ~ `validateDateTime` 메소드 한번 확인해주시면 좋을것 같아요. 
- `ErrorCode`에 `INVALID_BOARD_ID`가 사용하지 않는것으로 보이는데 남겨둔 이유가 있을까요?

2021-07-30 15:31 UTC, seongbeenkim commented
> * `Board`쪽 확인해보다가 게시물 삭제 날짜에 대한 null 체크는 그대로 있는것 같아서요 ! [날짜에 대한 null 체크 관련](https://github.com/kodesalon/project/pull/69#discussion_r679719246)해서 Dto에게 위임하기로 했다고 하셔서  ~ `validateDateTime` 메소드 한번 확인해주시면 좋을것 같아요.

확인해보니 @sdrs6921님이 게시물 조회 기능 브랜치의 https://github.com/kodesalon/project/pull/55/commits/7c74ac5ad9e39512f13082147c7f84c5831b4861 커밋에서 Board의 `validateDateTime` 제거해주었네요 혼란드려서 죄송합니다!

> * `ErrorCode`에 `INVALID_BOARD_ID`가 사용하지 않는것으로 보이는데 남겨둔 이유가 있을까요?

앗.. 다른 에러 코드로 적용하면서 삭제해주지 않은 것 같습니다 해당 부분 제거해주겠습니다!

2021-08-02 11:32 UTC, sefide approved these changes
변경사항 확인했습니다 ~ 고생하셨어요 👏🏼

2021-08-02 14:48 UTC, seonghun127 approved these changes
approve 할게요~ 구현하느라 고생하셨습니다! 
코멘트 하나 남겼는데 간단한거라 반영하시로 바로 merge 하면 될 것 같습니다 :)

2021-08-02 14:48 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/common/BaseEntity.java
>      @Column(name = "last_modified_date_time")
도메인 초기화 시 위 필드도 같이 초기화해주고 있으니 nullable = false 설정을 추가해주면 좋겠네요~

2021-08-04 05:05 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/common/BaseEntity.java
>      @Column(name = "last_modified_date_time")
넵 그러네요! 수정하였습니다~!

2021-08-04 05:14 UTC, merged