Feature/#68/패키지 구조 수정
kodesalon/project pull request #70
Opened 2021-07-28 04:34 UTC by sdrs6921

### 개요
- 이슈 번호 : #68 패키지-구조-수정
- 내용 : 패키지 구조 변경

### 작업 사항
- 패키지 구조 변경

### 기타
-

2021-07-30 14:11 UTC, sefide requested changes
[refactor : #22 게시물 다중 조회시 마지막 게시물인지 여부 응답값 추가 구현](https://github.com/kodesalon/project/pull/70/commits/0f0804a3dcd457c2c7067c4044d12f8df772170c)
위 커밋 이후로 몇군데에 `MultiBoardSelectResponse`에 대한 import가 빠져서 빌드가 안되네요 ~ 이 부분 확인 부탁드려요.
- argumentResolver 하위의 annotation 패키지는 상위 레벨로 옮기는건 어떨까요? 추후에 커스텀 어노테이션이 추가될 경우가 있지 않을까 싶어서요.
- 추가적으로 이제서야 물어보는데 혹시 `vertical line` 기준이 얼마나 되시나요? 
     - Intellij를 사용하신다면, 아래와 같이 확인하실 수 있어요. 
     **Preference > Code Style > Hard Wrap at** 
     - 개인적으로 `vertical line`이 120을 넘지 않는 컨벤션을 선호하는데 따로 잡은 기준이 있는것 같아 여쭤봐요.

2021-07-30 16:04 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/domain/Board.java
> +import static com.project.kodesalon.common.ErrorCode.NOT_AUTHORIZED_MEMBER;
> 추가적으로 이제서야 물어보는데 혹시 `vertical line` 기준이 얼마나 되시나요?
> * Intellij를 사용하신다면, 아래와 같이 확인하실 수 있어요.
>   **Preference > Code Style > Hard Wrap at**
> * 개인적으로 `vertical line`이 120을 넘지 않는 컨벤션을 선호하는데 따로 잡은 기준이 있는것 같아 여쭤봐요.

말씀해주신대로 Intellij에서 default로 되어 있는 120을 기준으로 화면에 그려진 선에 맞춰서 프로젝트를 진행하기로 했지만, 지키지 않고 있네요..😂  

이전에 다른 리뷰어분께서
현대 사회에서 사용하는 모니터, 노트북의 화면 크기가 커짐에 따라 `vertical line`에 대한 제약이 많이 없어져 보통 120 ~ 150을 사용한다고 말씀을 해주셨었는데 해당 부분 @sdrs6921님과 다시 한번 이야기 해보고 길이 컨벤션 적용하도록 하겠습니다!

2021-07-30 16:09 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/domain/Board.java
> +import static com.project.kodesalon.common.ErrorCode.NOT_AUTHORIZED_MEMBER;
> 위 커밋 이후로 몇군데에 MultiBoardSelectResponse에 대한 import가 빠져서 빌드가 안되네요 ~ 이 부분 확인 부탁드려요.

> `ErrorCode` 클래스가 com.project.kodesalon.exception으로 옮겨졌네요 !

패키지 구조 수정 후 제대로 변경되었는지 확인을 안하고 push를 올려서 발생한 문제로 확인됩니다!

해당 부분 다시 수정해주었습니다!

2021-08-02 06:14 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/domain/Board.java
> +import static com.project.kodesalon.common.ErrorCode.NOT_AUTHORIZED_MEMBER;
> * argumentResolver 하위의 annotation 패키지는 상위 레벨로 옮기는건 어떨까요? 추후에 커스텀 어노테이션이 추가될 경우가 있지 않을까 싶어서요.

현재는 argumentResolver 관련 annotation만 존재하기 때문에 기존 그대로 유지하고,
추후 다른 annotaion이 추가될 시 @sefide님께서 말씀해주신 것처럼 패키지의 레벨 등 구조를 수정하는 방향으로 이야기를 하였습니다!

2021-08-02 11:45 UTC, sefide commented on src/main/java/com/project/kodesalon/domain/Board.java
> +import static com.project.kodesalon.common.ErrorCode.NOT_AUTHORIZED_MEMBER;
> 모든 코드를 120으로 적용해봤는데, 코드의 인덴트 추가 및 통일성이 없어져 가독성이 떨어지는 느낌을 받았습니다.
기본 120을 가되, 살짝 초과한다면 라인을 그대로 유지하고 너무 길 경우에는 다음 라인으로 나누는 건 어떨까라는 생각이 드는데, 어떻게 생각하시나요??

120이 오히려 가독성을 해치고 깔끔한 코드를 유지하기에 짧다고 느껴진다면 더 큰 값으로 기준을 잡아도 될 것 같아요 ! 제가 여쭤봤던건 현재 코드에서 잡힌 `vertical line`의 기준이 궁금해서였습니다 ~ 너무 길다고 느껴지는 기준을 잡아두고 @sdrs6921 와 통일만 해주면 될 것 같습니다. 

> 현재는 argumentResolver 관련 annotation만 존재하기 때문에 기존 그대로 유지하고,
추후 다른 annotaion이 추가될 시 @sefide님께서 말씀해주신 것처럼 패키지의 레벨 등 구조를 수정하는 방향으로 이야기를 하였습니다!

넵 좋습니다 지금은 레벨이 크게 차이가 나는게 아니라 추후에 추가되는 스펙에 따라 변경해줘도 좋을 것 같아요.
실제 현업에서는 멀티 모듈 + 레거시 레포지토리인 경우 패키지 구조 변경이 어려울수도 있어 초기 구성을 잘해야 한다는 점만 기억해주시면 될 것 같아용

2021-08-02 14:04 UTC, seonghun127 approved these changes
레이어드 아키텍처대로 잘 구현하신 것 같습니다. 바로 Approve 할게요!

추가로 하나 이야기하자면 respository, service, controller 레이어도 domain 영역처럼 도메인별 패키지를 나누면 어떨까 라는 생각이 듭니다. 지금은 괜찮지만 해당 레이어에 클래스가 많아질수록 관리가 점점 어려워질 것 같네요.

2021-08-08 02:19 UTC, sefide approved these changes
변경된 부분 확인했습니다 ~ 고생했어요 👏🏼

2021-09-11 18:16 UTC, merged