Feature/#64/이미지 첨부 기능 구현
kodesalon/project pull request #76
Opened 2021-08-13 03:41 UTC by sdrs6921

### 개요
- 이슈 번호 : #64 
- 내용 : 이미지 첨부 기능 구현

### 작업 사항
- 게시물 이미지 첨부 기능 구현

### 기타
- TDD 방식으로 개발

2021-08-14 16:55 UTC, seonghun127 requested changes
처음 사용해보는 라이브러리들이 있었는데도 되게 잘 구현해주셨네요. s3mock 사용도 좋아보이네요.👍
가능하다면 advanced로 localstack으로 테스트 환경을 변환해보는 작업을 해도 될 것 같습니다. (그땐 docker도 같이 사용해보면 더 좋지 않을까 싶어요~)

몇가지 피드백들 남겨놨습니다. 확인부탁드려요!

2021-08-14 16:55 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/service/board/BoardService.java
> +            imageRepository.save(image);
`Board` 엔티티에 설정된 `Image`의 Cascade 설정이 ALL인데 이를 이용해서 이 로직은 없애는건 어떨까요?
다만 그렇게 되면 `new Image()`로 생성된 객체의 사용처가 없어서 로직이 조금 이상해보일 수 있겠는데요, `Board`의 addImage() 메서드를 편의메서드로 개선해서 사용해도 괜찮을 것 같네요.

`BoardService`와 `ImageService`(Repository)의 양방향 관계를 푸는데 많은 고민하신걸로 알고 있는데 `BoardService`에서 `ImageRepository`에 대한 의존도 없앨 수 있다면 없애는게 좋아보입니다.

2021-08-14 16:55 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/service/image/ImageService.java
> +        Board board = boardService.findById(boardId);
`ImageService`에서 꼭 `BoardService`를 알아야하나 싶은 생각이 들어요.

지금 `add()` 메서드는 `boardId`를 받아서 전달받은 이미지를 추가해주는 역할을 수행하는데요,
이 행위는 `Board`에 대한 수정이라고도 볼 수 있을 것 같아요. 즉, `BoardService`로 옮겨도 되지 않을까 싶습니다.

그러면 `ImageService` 에서는 단순히 `Image`객체를 생성해주는 역할만 수행하면 될 것 같아요.
그러면 `Image`를 추가해줄 때나 게시물을 생성할 때 (이미지를 생성해주는 부분) `ImageService`의 `Image`생성 메서드만 호출해주면 코드가 훨씬 깔끔해질 것 같습니다.

정리하면 아래 이점을 가져갈 수 있겠네요.
* `BoardService` 불필요한 의존 제거 가능 (`S3Uploader`, `directory`)
* `BoardService`, `ImageService`의 양방향 관계 문제 해결
* `Image` 도메인에 종속적인 `S3Uploader` 객체의 의존을 `ImageService` 하나로 국한시킬 수 있음

---
이 부분은 변경사항이 많아서 나중에 라이브로 리펙토링하는 과정을 같이 봐도 좋을 것 같습니다~

2021-08-14 16:55 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/repository/board/BoardRepository.java
> +    @Query("select b from Board b join fetch b.writer left outer join b.images where b.id = :boardId")
fetch join 이 필요해보이네요. (distinct도요~)

2021-08-16 14:45 UTC, sefide requested changes
이미지 등록 기능까지 추가되니 게시물 쪽이 점점 더 복잡해지네요. 
그래도 이후에 남겨주신 커밋 이후 `BoardService`와 `ImageService`의 역할이 좀 더 명확해진 것 같아요. 몇 가지 코멘트 남겼으니 확인 부탁드려요 :)

2021-08-16 14:45 UTC, sefide commented on src/main/java/com/project/kodesalon/service/S3Uploader.java
> +        File convertFile = new File(file.getOriginalFilename());
지금 이미지 파일을 프로젝트 디렉토리 상단에 이미지가 임시로 저장되는 것으로 보이는데 따로 이미지 디렉토리를 지정해주는게 좋을 것 같아요.

2021-08-16 14:45 UTC, sefide commented on src/main/java/com/project/kodesalon/service/S3Uploader.java
> +        String imageUrl = putS3(file, fileName);
해당 메소드에서 `SdkClientException` 혹은 `AmazonServiceException`가 발생한다면 
앞의 과정에서 생성된 이미지 파일이 remove되지 않을것으로 보이는데 이런 경우에는 어떻게 처리할 예정인가요?

2021-08-16 14:45 UTC, sefide commented on src/test/java/com/project/kodesalon/service/S3UploaderTest.java
> +    void upload() throws IOException {
불필요한 Exception 처리는 제거해주는게 좋겠네요 ~

2021-08-18 05:18 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/controller/board/BoardController.java
> +                                     @RequestParam(required = false) final Optional<List<MultipartFile>> images) {
아 이부분은 multipart/form-data`@ModelAttribute` 이미지와 게시물 정보를 한 번에 받아오도록 변경하였습니다. 다만 밑에 테스트가 왜 통과되는 현상에 대해서는 아직 발견하지 못했습니다!

2021-08-18 06:57 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/service/ImageService.java
> +            imageRepository.save(image);
이미지 5개로 제한하였으며 각 이미지당 크기 3MB, 요청당 받을 수 있는 최대 크기 15MB로 제한하였습니다!

2021-08-18 08:07 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/repository/board/BoardRepository.java
> +    @Query("select b from Board b join fetch b.writer left outer join b.images where b.id = :boardId")
이 부분 반영되었습니다!

2021-08-19 10:09 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/service/board/BoardService.java
> +    private List<BoardImageResponse> getBoardImageResponses(final Board board) {
넵!! `selectBoards` 와 `selectMyBoards` 그리고 `getBoardImageResponses` 의 메서드 위치를 변경하였습니다!

2021-08-19 14:00 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/service/S3Uploader.java
> +        File convertFile = new File(file.getOriginalFilename());
넵!! `resources` 하위에 `images` 디렉토리를 만들어서 지정해주었습니다!!

2021-08-19 14:14 UTC, sdrs6921 commented on src/test/java/com/project/kodesalon/service/S3UploaderTest.java
> +    void upload() throws IOException {
넵!! 제거하였습니다!

2021-08-19 14:26 UTC, sefide commented on src/main/java/com/project/kodesalon/controller/board/BoardController.java
> +                                     @RequestParam(required = false) final Optional<List<MultipartFile>> images) {
혹시 다들 어떻게 테스트 하셨나용 ? 
일단 전 e2bc40c 커밋전으로 돌려서 **postman**으로 테스트 해봤는데요.. 
- **content-Type** : multipart/form-data, **Body** : form-data로 전송 
=> 메세지컨 버터로 `BoardCreateRequest` 파라미터 바인딩 시 적절한 컨버터를 찾지 못해 HttpMediaTypeNotSupportedException 발생
- **content-Type** : application/json, **Body** : form-data로 전송 
=> postman에서 Body를 form-data로 전송하면 multipart/form-data로 설정되어 위와 동일한 결과 발생
- **content-Type** : application/json, **Body** : JSON 형식으로 전송 
=> `MappingJackson2HttpMessageConverter`에 의해 바인딩 성공, 하지만 json 형식으로 이미지 전송은 불가능해 이미지 없는 게시물 등록만 가능

이 부분에서 보셔야 할게, `save` 메소드는 아래와 같이 총 3가지의 파라미터를 받는데요. 
```
   public ResponseEntity<Void> save(@Login final Long memberId, @RequestBody @Valid final BoardCreateRequest boardCreateRequest,
                                     @RequestParam(required = false) final Optional<List<MultipartFile>> images) 
```
Spring에서는 request로 받은 값을 파라미터에 바인딩할때 선언한 순서대로 바인딩을 해요. (`save`메소드 같은 경우 memberId, boardCreateRequest, images 순으로 바인딩하겠죠? ) 여기서 content-Type이 **multipart/form-data**일 때 HttpMediaTypeNotSupportedException가 발생하는건 그 중 두번째 값인 `BoardCreateRequest`에 바인딩이 실패했기 때문이예요. 
controller test에서는 **application/json**으로 보내기 때문에 `MappingJackson2HttpMessageConverter`에 의해 `BoardCreateRequest` 파라미터에 값이 정상적으로 바인딩이 되어 다음 3번째 파라미터인 `images`를 바인딩할 수 있는 기회가 오는데요. 여기가 포인트인 것 같아요.
- **multipart/form-data**로 보내는 경우에는 2번째 파라미터 바인딩 시 Exception 발생
-  **application/json**로 보내는 경우에는 2번째 파라미터 통과, 3번째 파라미터 `images` 바인딩 시도

실제 controller test에서 넘겨준 이미지가 어떻게 바인딩되는지는 바인딩 시 사용되는 resolver를 탐색하는 부분(`HandlerMethodArgumentResolverComposite`의 `getArgumentResolver` 메소드)과 탐색하여 선택된 resolver가 동작하는 부분(`RequestParamMethodArgumentResolver의 resolveName`메소드)을 보시면 될 것 같은데.. 제가 정확한 과정까지는 확인못했는데.. 이걸로 질문의 답은 찾을 수 있을것 같아요! 맞을까요 디버깅하면서 정리가 잘 안되어서 질문 남겨주시면 답변드릴게욧

+ 파라미터 순서대로 바인딩하는 과정은. `InvocableHandlerMethod`의 `getMethodArgumentValues` 메소드를 확인하시면 된답니다 :)

2021-08-19 15:02 UTC, seonghun127 reviewed
아직, 리뷰 반영중인 것 같지만 추가 코멘트 남겨요~

2021-08-19 15:02 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/service/image/ImageService.java
> +                .collect(Collectors.toList());
리펙토링 방향이 두가지일 것 같아요.

첫번째, `add()` 메서드 제거
* 이미지 다건 업로드가 `S3Uploader`로 이동한다면 `BoardService`에선 게시물 생성 시 `ImageService`를 의존하는 것이 아닌 `S3Uploader`를 의존하도록 변경할 수 있을 것 같습니다. -> 어쩌면 `ImageService` 자체가 제거될 수 있을 것 같기도 하네요.

두번째, `add()` 메서드 역할 변경
* 여러 방향으로 역할을 변경할 수 있을 것 같은데요, 생각이 드는건 `Image` 엔티티 생성 역할 추가입니다.
* 이로 인해 가질 수 있는 장점은 아래와 같을 것 같습니다.
   1. `Image` 엔티티 생성 로직을 한 곳에서 관리 (추후 이미지를 사용하는 다른 기능이 나오더라도 `ImageService`만 호춣하면 됨)
   2. `S3Uploader` 사용처를 `ImageService` 한 곳으로 국한시킬 수 있음 -> 현재 `add()` 메서드의 로직은 충분히 `S3Uploader`로 뺄 수 있고 (빼는게 맞다고 생각합니다.) 그렇게 된다면 `S3Uploader`의 의존이 다양하게 형성될 수 있음 e.g. `BoardService`

2021-08-20 02:46 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/controller/board/BoardController.java
> +        if (bindingResult.hasErrors()) {
`ModelAttribute` 에서 발생한 `@Valid` 예외를 `MethodArgumentNotValidException` 에서 `GlobalExceptionHandler`에서 잡지 못해서 추가해줬었는데, `ModelAttribute`에서 발생한 `@Valid`예외를 `BindException`으로 잡을 수 있어서 이 로직은 삭제하고 `GlobalExceptionHandler` 에서 잡는 예외를 `BindException`으로 변경하였습니다.

2021-08-20 03:34 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/service/S3Uploader.java
> +        String imageUrl = putS3(file, fileName);
예외가 발생했을 때 파일이 삭제되지 않는 문제는 고려하지 못했습니다. 이 부분은 두 예외가 모두 상속하는 `AmazonClientException`으로 catch 해서 예외를 발생시키도록 구현하였고, finally를 활용해서 예외가 발생했을 때와 발생하지 않을 경우 모두 삭제를 하도록 처리하는 방법으로 변경하였습니다.

2021-08-20 03:50 UTC, sdrs6921 commented on src/test/java/com/project/kodesalon/service/dto/request/BoardCreateRequestTest.java
> +            = new BoardCreateRequest("게시물 제목", "게시물 내용", LocalDateTime.parse("2021-06-01T23:59:59.999999"), Optional.empty());
`Java Convention`을 헷갈렸습니다. 바로 변경하겠습니다!!

2021-08-20 03:54 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/service/board/BoardService.java
>          log.info("Member alias : {}, Board Id : {}", member.getAlias(), createdBoard.getId());
넵! log를 찍어주는 위치를 변경하였습니다!

2021-08-20 04:35 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/service/board/BoardService.java
> +        urls.forEach(url -> new Image(url, createdBoard));
이 부분도 함께 고려해봤는데 `Image` 엔티티의 `Board`가 변경되는 것을 막기 위해서 생성자로만 생성하도록 하였습니다.

2021-08-29 08:24 UTC, seonghun127 reviewed
추가 피드백 남겨놨어요~ 확인부탁드려요!

2021-08-29 08:24 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/service/board/BoardService.java
> +        imageRepository.deleteAll(images);
기본으로 제공되는 `deleteAll()` 메서드를 보니 단건으로 삭제 쿼리를 날리네요.
직접 (1) jpql을 짜거나, (2)`deleteInBatch()` 메서드를 사용하는게 좋겠네요.
주의할 점은 (1), (2) 모두 영속성 컨텍스트를 무시하고 쿼리를 발생시키기 때문에 그 다음 호출되는 로직이 영속성 컨텍스트를 사용한다면 이슈가 발생한다는 점입니다. 이부분 고려해서 리펙토링해보면 좋을 것 같아요~
참고 자료입니다.
* https://jojoldu.tistory.com/235
* https://stackoverflow.com/questions/26142261/spring-jparepostory-delete-vs-deleteinbatch

2021-08-29 08:24 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/service/S3Uploader.java
> +        keys.forEach(this::delete);
아래 API가 제공되네요. 이걸 사용하면 더 좋을 것 같습니다~
* com.amazonaws.services.s3.AmazonS3#deleteObjects

2021-08-29 08:24 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/service/board/BoardService.java
> +        s3Uploader.delete(imageKeys);
**[한번 고려해보면 좋을 것 같아서 피드백 남겨요. 당장 반영할 필요는 없고 이런 개념이 있구나 하고 넘어가도 좋습니다.]**

이 메서드는 S3에 올라간 이미지를 제거하는 메서드인데요, 이 트랜잭션에 같이 묶일 필요가 있을까 싶은 생각이 들어요.
결국 외부 리소스와(amazon sdk를 이용해서 S3 bucket와) 네트워크 통신을 하기때문에 큰 비용이라고 생각이 드는데 이 삭제 처리 API의 response time이 커지는 요인 중 하나라고 생각합니다.

이 부분을 트랜잭션 밖에서 비동기로 처리하면 response time을 더 빨리 가져갈 수 있을 것입니다. 이 메서드가 반환하는 값을 가지고 어떤 것을 하는 것이 아니기 때문에 처리가 완료될 때까지 기다릴 필요가 없죠.
물론, 한가지 고려해야할 것이 S3에 이미지 삭제 실패 시 이를 보장을 못받는 것인데요. 이런 상황이 발생할 경우 이 문제를 어떻게 처리할 것인지 고민해봐야겠지만 설령 그런 상황이 발생해도 DB 데이터는 제거됐기 때문에 현 어플리케이션이 동작하는데는 전혀 문제를 주진 않기 때문에 트랜잭션을 분리해도 괜찮아보여요.

만약 이 피드백을 반영하고 싶다면 아래 키워드에 한번 찾아보시면 좋을거에요.
* `@EnableAsync` / `@Async`

2021-08-29 08:27 UTC, seonghun127 commented on src/main/java/com/project/kodesalon/service/S3Uploader.java
>          File file = convert(multipartFile)
> 현재 S3Uploader 테스트 코드도 복잡해진 것으로 판단되네요.
만약 클래스를 분리한다면 SpringExtension없이 mock 객체를 생성해서 적절한 stubbing으로 테스트 코드를 보다 간소화할 수 있지 않을까 싶습니다.

이 부분에 대한 이야기는 integration test와 unit test에 관한 이야기이므로 그냥 넘어가도 좋을 것 같습니다.
현재 `S3UploaderTest`는 integration test로 보여서 충분한 검증을하고 있다고 생각이 듭니다. 위 코멘트는 unit test를 고려해서 말씀드린 거였는데 현재 unit test는 필요없어 보이네요~

2021-08-29 10:40 UTC, sefide approved these changes
안녕하세용 
사실 저는 생각지 못했는데 @seonghun127 님께서 좋은 리뷰를 남겨주셔서 클래스별 구분이 더 명확해졌고 충분히 구분이 되었다고 생각이 드네요..! S3Uploader에서는 S3에 관련된 역할에 집중하고 그 외 파일을 업로드하는건 FileService에서 하고요.  이후에 추가되는 파일 관련된 로직은 FileService에서 녹여낼 수 있을것 같아요.
+) 추가적으로 궁금한게 있는데요. 현재는 게시물 등록 시에 이미지를 받고 있는데 게시물 업데이트 시에는 이미지 수정은 제공해주지 않는걸까요?

2021-08-29 10:40 UTC, sefide commented on src/main/java/com/project/kodesalon/controller/board/BoardController.java
> +    @PostMapping("/add-images/{boardId}")
POST 메소드를 사용했다는 것에서 이미지를 추가한다는 의미를 줄 수 있기 때문에 url에 동사는 안넣어도 될 것 같아요~

2021-08-29 10:40 UTC, sefide commented on src/main/java/com/project/kodesalon/controller/board/BoardController.java
> +    @DeleteMapping("/remove-images/{imageIds}")
여기도 위와 같은 의견입니다!

2021-08-30 04:01 UTC, sdrs6921 commented on src/test/java/com/project/kodesalon/service/FileServiceTest.java
> +        file.delete();
넵! `teardown`으로 삭제할 파일이 존재할 경우 삭제하도록 처리하였습니다!

2021-08-30 04:05 UTC, sdrs6921 commented on src/main/java/com/project/kodesalon/service/FileService.java
> +    private static final char EXTENSION_SEPARATOR = '.';
깜빡했습니다.. 컨벤션에 맞춰 코드를 변경하였습니다!

2021-08-30 04:29 UTC, sdrs6921 commented on src/test/java/com/project/kodesalon/service/S3UploaderTest.java
> +        s3Mock.stop();
넵넵!! 말씀해주신대로 `@Bean` 어노테이션에서 `initMethod`와 `destroyMethod` 속성을 활용하였습니다. 이전에 `stop`메서드를 사용했던 이유는  `shutdown` 메서드를 활용했었는데 `s3mock`을 `start`메서드로 실행할 경우 `shutdown`을 두 번 호출했을 때 무한 루프를 돌아서 `stop`으로 변경했었습니다.

2021-08-30 07:12 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/service/board/BoardService.java
> +        imageRepository.deleteAll(images);
넵넵 영속성 컨텍스트 관련 문제 숙지하였으며 `deleteInBatch()`로 수정해주었습니다!

2021-08-30 07:13 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/service/S3Uploader.java
> +        keys.forEach(this::delete);
매번 `delete0bject`로 삭제하는 것보다 `deleteObjects`로 한번에 삭제하는 편이 더 좋네요! 수정하였습니다!

2021-08-30 07:15 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/service/board/BoardService.java
> +        s3Uploader.delete(imageKeys);
해당 부분 @EnableAsync / @Async 적용해주어 분리해주었습니다!
DB 정합성 문제는 리팩토링 모두 마친 후 Batch를 사용하여 삭제 작업 일괄 처리하기로 하였습니다!

2021-08-30 07:17 UTC, seongbeenkim commented on src/test/java/com/project/kodesalon/service/board/BoardServiceTest.java
> +    private Image image;
넵넵 사용하지 않는 객체 제거해주었습니다 :)

2021-08-30 07:36 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/controller/board/BoardController.java
> +    @PostMapping("/add-images/{boardId}")
`add-imges` -> `images` 로 수정해줬습니다!

2021-08-30 07:36 UTC, seongbeenkim commented on src/main/java/com/project/kodesalon/controller/board/BoardController.java
> +    @DeleteMapping("/remove-images/{imageIds}")
`remove-imges` -> `images` 로 수정해줬습니다!

2021-09-16 17:44 UTC, merged