[PULL REQUEST] : Logback 설정
kodesalon/project pull request #8
Opened 2021-05-10 10:52 UTC by sdrs6921

### 개요
- 이슈 번호 : 
- 내용 : Logback 및 LogbackStash 추가

### 작업 사항
- 

### 기타
-

2021-05-10 11:13 UTC, seongbeenkim reviewed
`fix`는 버그 수정과 같은 곳에 사용하는 컨벤션이기 때문에
앞으로 이와 같은 비슷한 내용을 커밋 할 경우에는 `chore` 로 남기는게 좋을 것 같습니다!

2021-05-10 11:39 UTC, sefide commented
feature 대신 간단하게 feat으로 작성해도 좋을 것 같아요 
지난 PR에 성빈님께서는 feat으로 작성하셔서., 저도 보다 명료한 feat을 추천드립니당 !

2021-05-10 12:06 UTC, sefide reviewed
아직 개발전인 것 같긴한데.. 간단한 코멘트 하나 남겼습니다 ~ 

더불어서 커밋 메세지 타입으로 feature 대신 간단하게 feat으로 작성해도 좋을 것 같아요.
지난 PR에 성빈님께서는 feat으로 작성하셔서., 저도 보다 명료한 feat을 추천드립니당

2021-05-10 12:06 UTC, sefide commented on src/main/resources/logback-spring.xml
> +</configuration>
파일의 끝에는 개행을 추가해주는 것이 좋습니당
posix 명세에서 '파일은 행들의 집합이고, 개행(CRLF)으로 끝낸다.' 와 같이 파일에 대한 정의를 하고 있는데요. 파일 간의 구분을 위해 개행을 추가한다고 해요 

자세한 사항은 [블로그 참고](https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/)해보고 사용하시는 IDE에 설정을 추가해줘도 좋을 것 같아요.

2021-05-10 12:16 UTC, seongbeenkim commented on src/main/resources/logback-spring.xml
> +</configuration>
> 지난 PR에 성빈님께서는 feat으로 작성하셔서., 저도 보다 명료한 feat을 추천드립니당

넵 맞아요 지난번에 제가 `feat` 으로 남기고 생각해보니 `feat`보다는 `chore`를 사용한다면 `feat`은 완전히 프로덕션 코드에서 기능 추가를 사용할 때 사용하는 컨벤션으로 사용할 수 있게 되고, `chore`는 빌드 추가 수정과 같은 곳에 사용하게 된다면 더 컨벤션을 명확하게 나누면서 사용하는 것이지 않을까 생각해서 의견드려봤습니다!

2021-05-10 12:17 UTC, sdrs6921 commented on src/main/resources/logback-spring.xml
> +</configuration>
다음 커밋 메세지에 반영하겠습니다!!

2021-05-10 12:24 UTC, sefide commented on src/main/resources/logback-spring.xml
> +</configuration>
앗 제 말이 오해의 소지가 있었던것 같아요. 
feature에서 'ure'를 뺀 'feat'으로 간단하게 작성하는게 어떻겠냐는 코멘트였습니다 ㅎㅎ
feat과 chore의 역할에 대해서는 성빈님 말씀에 동감합니다 !

2021-05-10 15:32 UTC, seonghun127 requested changes
logback이 처음 설정해보면 xml이라 헷갈리고 어려울 수 있는데 잘 적용한 거 같음~
몇가지 피드백 남겼으니 확인해봐!!

+ commit message prefix 로 feature 기능 구현에 대해서 feat으로 남기는 거 저도 찬성~
+ PR 날릴 때 PR comment에 템플릿화 되어있는거 정말 좋은데 거기에 리뷰받아보고 싶은 내용이나 추가 궁금한 것들, 작업하면서 어려웠던 부분들도 같이 적어주면 앞으로 리뷰하는데 더 도움이 될 거 같애. 다음 PR 부턴 그 내용도 같이 적어주면 좋을 듯~
+ 지금 PR을 보니까 develop에서 master로 날리고 있는데 git flow를 다시 정리해볼 필요가 있는 거 같애.
아래 순으로 git flow를 그리고 있는데 혹시 맞을까? 이게 아니라 다른 방식으로 진행한다면 여기 코멘트나 슬랙으로 알려주고!
```
develop -> checkout feature -> merge into develop (PR) -> ci develop after merge -> merge into master -> deploy 
```

2021-05-10 15:32 UTC, seonghun127 commented on src/main/resources/logback-spring.xml
> +            <maxFlushTime>0</maxFlushTime>
비동기 로그를 설정해줄 때는 `<maxFlushTime>` 설정 뿐만 아니라 다른 설정들도 줄 수 있는데,
`<neverBlock>` 설정이라던지 다른 설정값들도 찾아보고 같이 설정해주면 좋을 거 같애~

비동기 로그를 남기는 장점은 단연 로그를 남기는 리소스를 main 스레드가 부담하지 않아서 전체 로직 처리 속도를 빠르게 가져갈 수 있지만 Blocking Queue 자료구조를 이용했기 때문에 이 자료구조에 문제가 생겼을 때 많은 문제가 일어날 수 있다는 단점이 있어.
로그 정보는 중요하기 때문에 큐에 문제가 발생할 경우 어떻게 처리할 것인지 한번 고민해보면 좋을 거 같음~

참고자료
* http://logback.qos.ch/manual/appenders.html#AsyncAppender
* https://kwonnam.pe.kr/wiki/java/logback/asyncappender

2021-05-10 15:32 UTC, seonghun127 commented on src/main/resources/logback-spring.xml
> +        <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
로컬(profile = local) 환경이라면 파일로 로그를 남길 필요가 있을까? 실시간으로 콘솔에서 로그를 보는게 더 편하지 않을까 라는 생각이 듭니다~
그리고 지금 remote repo에 로그 파일도 같이 올라오고 있는데, 이는 로컬 환경에선 콘솔로그로 남도록 수정하던지 추가로 .gitignore에 log 파일을 추가하면 좋을 거 같애.

2021-05-10 15:32 UTC, seonghun127 commented on src/main/resources/application.yml
>      root: info
기본 로깅 레벨 설정은 `logback-spring.xml` 에서 이미 해주고 있어서 yaml 파일에선 지워도 될 듯

2021-05-10 15:32 UTC, seonghun127 commented on src/main/resources/logback-spring.xml
> +            <file>${LOG_PATH}app.log</file>
지금 `LOG_PATH`를 `property` 변수로 받을 필요가 있을까?
나중에 파일이 분리되거나 중복이 발생하면 그때 추출시켜주면 좋을 거 같어~
미리 해놓은거라면 그것대로 좋지만 그 사실을 모르고 보면 파일을 읽는데 헷갈리게 되더라고

2021-05-11 01:42 UTC, seongbeenkim commented
test~

2021-05-11 03:04 UTC, sdrs6921 commented on src/main/resources/logback-spring.xml
> +            <file>${LOG_PATH}app.log</file>
지금은 `property` 변수로 받지 않고 직접 지정해주고 나중에 필요하다면 따로 `propert`  변수로 받아서 사용하는게 더 좋겠다는 말씀 맞나요?

2021-05-11 11:55 UTC, seonghun127 approved these changes
리뷰 반영 굳~

추가로 희상이가 남긴 코멘트에 답을 하자면 제대로 이해한 거 같어.
다만 위 PR에선 develop에서 master로 PR을 날렸길래 확인차 물어본거였고~

근데 git flow엔 정답이 없어서 다른 방식이 더 좋은 거 같다고 판단이 되면 그거대로 진행해도 좋아~ 같이 이야기해봐도 좋고 :)

2021-05-11 11:55 UTC, seonghun127 commented on src/main/resources/logback-spring.xml
> +            <neverBlock>true</neverBlock>
`<neverBlock>` 설정에 대해서 혹시 정리가 됐을까?
일요일에 간단하게나마 이야기 해보면 좋을 거 같아요~

2021-05-11 11:55 UTC, seonghun127 commented on src/main/resources/application.yml
> +    active: "local"
profile default 설정 👍

2021-05-11 11:55 UTC, seonghun127 commented on src/main/resources/logback-spring.xml
> +        <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
분리 좋아요~

2021-05-11 11:55 UTC, seonghun127 commented on src/main/resources/logback-spring.xml
> +            <file>${LOG_PATH}app.log</file>
네엡 👍

2021-05-11 12:21 UTC, sefide approved these changes
빠른 반영 👍🏼 👍🏼 

다음 pr에 .gitignore에도 개행을 추가해주면 좋을 것 같네용 ~

2021-05-11 12:32 UTC, sdrs6921 commented
> 다음 pr에 .gitignore에도 개행을 추가해주면 좋을 것 같네용 ~

IDE 설정을 추가했는데도 반영이 안되었나요?? 다음 PR에 반영하겠습니다.

2021-05-11 12:32 UTC, merged